package smilesim

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"gorm.io/gorm"

	"github.com/vislake/speed/go/dbkit"
	"github.com/vislake/speed/go/jobs"
)

// simulationsTable is SimulationStore's persisted table name.
const simulationsTable = "smilesim_simulations"

// createSimulationsTableSQL is executed imperatively, with a plain CREATE
// TABLE IF NOT EXISTS -- the exact bootstrapping pattern ReservationStore's
// own createCreditReservationsTableSQL uses and documents (see that
// constant's doc comment for why this app's own bookkeeping tables do not
// go through dbkit.MigrationRegistry's cross-module machinery). The
// statement is portable across both dbkit dialects, like its sibling:
// VARCHAR/TIMESTAMP columns, application-generated ids, no PostgreSQL- or
// SQLite-specific syntax. The column set and types match the GORM model
// tags below exactly.
const createSimulationsTableSQL = `CREATE TABLE IF NOT EXISTS ` + simulationsTable + ` (
	job_id          VARCHAR(64)  NOT NULL PRIMARY KEY,
	tenant_id       VARCHAR(64)  NOT NULL,
	photo_object_id VARCHAR(64)  NOT NULL,
	options_json    VARCHAR(256) NOT NULL,
	created_at      TIMESTAMP    NOT NULL
)`

// createSimulationsTenantPhotoIndexSQL is the lookup index behind
// ListSimulationsByPhoto's per-photo enumeration. Kept as its own statement
// (CREATE INDEX IF NOT EXISTS is accepted by both SQLite and PostgreSQL)
// because the composite index cannot be declared portably inside the CREATE
// TABLE above.
const createSimulationsTenantPhotoIndexSQL = `CREATE INDEX IF NOT EXISTS idx_smilesim_simulations_tenant_photo ON ` + simulationsTable + ` (tenant_id, photo_object_id)`

// simulationRecord is the durable record of one simulation generation
// request: which photo it was generated from, which effective option set
// produced it, and which image-generation job carries its outcome. The row
// is written the moment Simulate's enqueue succeeds and is never deleted or
// updated -- it is this package's append-only per-photo index, the data
// source the smile gallery's "simulations of this photo" list reads
// through Service.ListSimulationsByPhoto, with each record's live status
// and output object read from the job at query time (the job's own
// persisted row is the outcome's source of truth; see
// ListSimulationsByPhoto's doc comment).
//
// Unlike creditReservation -- platform data by design, because the credit
// reconciliation sweep must list across every tenant in one query -- this
// row is tenant data: every access path (save, get, listByPhoto) runs under
// the owning tenant from the pkgcore context, never from a request. It
// therefore follows the exact shape of the reference app's other
// tenant-domain model, notes.Note (internal/notes/model.go): it embeds
// dbkit.TenantModel for its tenant_id column and GetTenantID method, with
// the tenant filter injected by dbkit's tenant-scoping plugin and by
// dbkit.Repository[simulationRecord] itself -- never written by hand (see
// go/dbkit/tenant_scope.go). Embedding TenantModel -- a plain, non-key
// tenant_id column -- is the right shape here for the same reason Note's
// own doc comment gives for it: JobID is this record's primary key and is
// application-generated by the go/jobs queue (already globally unique on
// its own), so no composite (tenant_id, job_id) key is needed.
type simulationRecord struct {
	// JobID is the go/ai-gateway image-generation job's id -- Simulate's
	// own return value, and the key the outcome is retrieved under.
	JobID string `gorm:"column:job_id;primaryKey;size:64"`

	// TenantModel promotes the tenant_id column and GetTenantID method
	// (satisfying dbkit.TenantScoped) -- see the doc comment above for why
	// this record embeds it instead of declaring TenantID directly, and
	// Note's identical choice in internal/notes/model.go.
	dbkit.TenantModel

	// PhotoObjectID is the go/storage object id of the patient photo the
	// simulation was generated from -- the smile gallery's grouping key.
	PhotoObjectID string `gorm:"column:photo_object_id;size:64;not null"`

	// OptionsJSON is the canonical JSON of the EFFECTIVE option set that
	// produced this simulation -- after defaults were applied, exactly the
	// set whose rendering became the job's vendor prompt. Stored as JSON
	// text in a VARCHAR column (the dual-dialect-portable spelling of a
	// JSON document; SQLite has no native JSON column type) rather than as
	// discrete columns, because the option set is this package's own
	// shape: it may grow new dimensions without a schema change, and
	// nothing ever queries an individual option in SQL.
	OptionsJSON string `gorm:"column:options_json;size:256;not null"`

	// CreatedAt records when the generation was requested. The enumeration
	// read orders by it, newest first.
	CreatedAt time.Time `gorm:"column:created_at;autoCreateTime"`
}

// TableName pins simulationRecord to simulationsTable, so it does not depend
// on GORM's pluralization of the (unexported) type name.
func (simulationRecord) TableName() string { return simulationsTable }

// options decodes the record's OptionsJSON back into the typed option set.
// A row whose JSON fails to decode is a corrupted record; the error is
// surfaced rather than guessed at.
func (r simulationRecord) options() (SimulationOptions, error) {
	var o SimulationOptions
	if err := json.Unmarshal([]byte(r.OptionsJSON), &o); err != nil {
		return SimulationOptions{}, err
	}
	return o, nil
}

// compile-time check that simulationRecord satisfies dbkit.TenantScoped.
var _ dbkit.TenantScoped = simulationRecord{}

// SimulationStore is smilesim's tenant-scoped data-access type for
// simulationRecord -- the app-side mirror of notes' Repository shape
// (internal/notes/repository.go): it embeds dbkit.Repository[simulationRecord]
// instead of holding a plain *gorm.DB (the multi-tenant isolation
// discipline), so Create is promoted from
// the embedded base -- which resolves the tenant from the ctx itself and
// fails closed when ctx carries none -- while the two lookups
// Repository[T]'s deliberately minimal surface cannot express live here as
// their own methods, each running inside
// dbkit.WithTenantSession exactly as notes' own listSoftDeletedBefore and
// listByCreator do, with the tenant half of the WHERE clause injected by
// dbkit's tenant-scoping plugin from the ctx tenant (go/dbkit/tenant_scope.go)
// -- never written by hand. ReservationStore, by contrast, stays a
// plain-gorm store because creditReservation is platform data that must NOT
// implement dbkit.TenantScoped (see reservation_store.go's own doc comment).
//
// The zero value is not ready to use; construct one with
// NewSimulationStore.
type SimulationStore struct {
	*dbkit.Repository[simulationRecord]

	// db is the *gorm.DB the embedded Repository was built over, kept here
	// for the WithTenantSession calls below. It is the very connection the
	// embedded Repository already uses -- never a second pool -- exactly as
	// notes' own Repository holds the db it was built over for its own
	// tenant-session queries (the precedent this shape follows).
	db *gorm.DB
}

// NewSimulationStore returns a SimulationStore backed by db, expected to
// come from dbkit.Open (directly, or through dbkit/dbtest in tests) --
// mirroring NewReservationStore's identical contract, and see
// dbkit.Repository's own doc comment for why db is expected to come from
// Open specifically. It performs no I/O; call EnsureSchema once before
// first use.
func NewSimulationStore(db *gorm.DB) *SimulationStore {
	return &SimulationStore{Repository: dbkit.NewRepository[simulationRecord](db), db: db}
}

// EnsureSchema creates SimulationStore's table and its per-photo lookup
// index if they do not already exist -- see
// createSimulationsTableSQL's own doc comment for why this is a plain,
// idempotent CREATE rather than a versioned dbkit.MigrationRegistry
// migration. Call it once, before Simulate or ListSimulationsByPhoto ever
// run (internal/app's own wiring does this alongside
// ReservationStore.EnsureSchema).
func (s *SimulationStore) EnsureSchema(ctx context.Context) error {
	if err := s.db.WithContext(ctx).Exec(createSimulationsTableSQL).Error; err != nil {
		return err
	}
	return s.db.WithContext(ctx).Exec(createSimulationsTenantPhotoIndexSQL).Error
}

// save durably records that one generation request -- jobID over
// photoObjectID under the ctx's tenant, produced by options -- exists.
// Called by Simulate exactly once per successful GenerateImage call,
// immediately after the job id becomes known. JobID is the primary key, so
// a repeated save of the same job would conflict rather than duplicate;
// Simulate never calls it twice for one job.
//
// The row's tenant comes from the ctx, never from a parameter: the
// embedded Repository.Create resolves it via pkgcore.MustTenantFromContext
// and fails closed with pkgcore's own error before the database is touched
// when ctx carries none (see dbkit.Repository.Create's doc comment), so a
// caller cannot cause a row to be recorded under a tenant other than the
// ctx's -- the identical overwrite-the-caller guarantee every Repository
// write carries.
func (s *SimulationStore) save(ctx context.Context, jobID jobs.JobID, photoObjectID string, options SimulationOptions) error {
	data, err := json.Marshal(options)
	if err != nil {
		return err
	}
	return s.Create(ctx, &simulationRecord{
		JobID:         string(jobID),
		PhotoObjectID: photoObjectID,
		OptionsJSON:   string(data),
	})
}

// get returns ctx's tenant's record for jobID, and whether one exists --
// false with a nil error means no record is on file under that tenant
// (never simulated through this package, or simulated under another
// tenant). The lookup runs inside dbkit.WithTenantSession, exactly as
// notes' listSoftDeletedBefore precedent does: the tenant-scope plugin
// injects the tenant half of the WHERE clause from the ctx tenant (see
// go/dbkit/tenant_scope.go), so no tenant_id filter is written here by
// hand, and the answer can never name another tenant's row.
func (s *SimulationStore) get(ctx context.Context, jobID jobs.JobID) (simulationRecord, bool, error) {
	var row simulationRecord
	err := dbkit.WithTenantSession(ctx, s.db, func(tx *gorm.DB) error {
		return tx.Where("job_id = ?", string(jobID)).First(&row).Error
	})
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return simulationRecord{}, false, nil
	}
	if err != nil {
		return simulationRecord{}, false, err
	}
	return row, true, nil
}

// listByPhoto returns every record ctx's tenant has on file for
// photoObjectID, newest first (created_at descending, with job id as a
// stable tiebreak for two records created within the same timestamp tick).
// The query runs inside dbkit.WithTenantSession with the tenant half of the
// WHERE clause injected by the tenant-scope plugin from the ctx tenant --
// never a post-query filter and never a hand-written tenant_id clause (see
// go/dbkit/tenant_scope.go) -- so a caller can only ever enumerate its own
// tenant's rows.
func (s *SimulationStore) listByPhoto(ctx context.Context, photoObjectID string) ([]simulationRecord, error) {
	var rows []simulationRecord
	err := dbkit.WithTenantSession(ctx, s.db, func(tx *gorm.DB) error {
		return tx.Where("photo_object_id = ?", photoObjectID).
			Order("created_at DESC, job_id DESC").
			Find(&rows).Error
	})
	if err != nil {
		return nil, err
	}
	return rows, nil
}
