package main

// smilesim_flow_test.go drives go/ai-gateway round 2's image-generation
// pipeline end to end through the composed HTTP stack -- the
// authn+tenancy middleware chain, a real temp-file SQLite database
// (carrying storage's, ai-gateway's and every other module's real
// migrations), a real jobs.StandaloneQueue, and the hand-written
// smile-simulation routes (cmd/server/smilesim.go) -- against a fake
// OpenAI-compatible images endpoint (fakeOpenAIImageServer below),
// standing in for the real vendor: no live API key is available or
// needed, since the OpenAI-compatible images-edits multipart/form-data
// schema is fully testable this way (see go/ai-gateway/AGENTS.md's own
// reference-app-consumer section for round 2).
//
// The one leg covers the round's acceptance shape: a patient photo,
// uploaded through storage's own real HTTP surface, produces one async
// smile-simulation job whose completion is observed by polling
// smilesim's own job-status route -- proving the whole chain: the job
// handler read the uploaded photo's real bytes back out of storage, sent
// them to the fake vendor as a genuine multipart/form-data request (image
// file, model and prompt fields all present and correct), and wrote the
// vendor's generated bytes back into storage as a brand new object,
// distinct from the input, that this app's own storage HTTP surface can
// read back.
//
// Known, non-flaky WARN log this test deterministically surfaces: the
// uploaded photo's own storage.object.derive.thumbnail job (enqueued by
// its Complete) and this round's ai-gateway.image.generate job for the
// SAME request now run concurrently on buildServer's one shared
// jobs.StandaloneQueue (WorkerCount 4 by default) against the app's one
// file-backed SQLite database -- an ordinary single-writer contention
// between two independent worker goroutines, not the AuditBus
// same-goroutine self-deadlock go/dbkit/AGENTS.md's "Known limitation"
// section describes (that one, per its own doc comment, is NOT fixed by a
// busy timeout; this one would be, by ordinary SQLite `busy_timeout`
// contention-retry semantics -- ordinary contention, unlike a
// self-deadlock, resolves once the other writer's transaction commits).
// go/jobs' own retry/backoff is the existing, working mitigation: the
// losing attempt logs "job attempt failed, scheduling retry" with error
// "storage.internal_error: database is locked (5) (SQLITE_BUSY)" and
// succeeds on its very next attempt, which is why this test's own
// assertions (including on Attempts via the job's final state) still pass
// deterministically. Genuinely removing the WARN line would mean either a
// dbkit-wide SQLite DSN change (a `busy_timeout` pragma) or a queue
// concurrency change in this app's own wiring (examples/reference-app/
// cmd/server/server.go's shared StandaloneQueue) -- both cross-cutting
// changes outside go/ai-gateway's own round, so this is recorded here and
// in go/ai-gateway/AGENTS.md's "Known limitations / deferred" section
// rather than silently worked around inside this round's tests.

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"io"
	"mime"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"
)

// fakeOpenAIImageServer answers every POST /images/edits with a fixed,
// generated PNG image as a base64 "data" entry plus a fixed usage block --
// the wire shape go/ai-gateway's OpenAICompatibleImageProvider parses
// (go/ai-gateway/openai_compatible_image.go's openaiImageResponseWire). It
// records the last request's decoded multipart form, so a test can assert
// on exactly what this app's wiring sent -- including the uploaded image
// file's own bytes.
type fakeOpenAIImageServer struct {
	*httptest.Server

	generatedPNG []byte

	lastModel    string
	lastPrompt   string
	lastImageRaw []byte
}

func newFakeOpenAIImageServer(t *testing.T) *fakeOpenAIImageServer {
	t.Helper()

	// A tiny, deterministic PNG stands in for the vendor's "simulated
	// smile" output -- distinct pixel content from the uploaded photo, so
	// a test can tell the two apart by more than just object id.
	img := image.NewRGBA(image.Rect(0, 0, 4, 4))
	for y := 0; y < 4; y++ {
		for x := 0; x < 4; x++ {
			img.SetRGBA(x, y, color.RGBA{R: 200, G: 200, B: 200, A: 255})
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatalf("encode fake generated png: %v", err)
	}

	f := &fakeOpenAIImageServer{generatedPNG: buf.Bytes()}
	f.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/images/edits" {
			http.NotFound(w, r)
			return
		}
		_, params, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
		if err != nil {
			http.Error(w, "malformed content-type", http.StatusBadRequest)
			return
		}
		mr := multipart.NewReader(r.Body, params["boundary"])
		form, err := mr.ReadForm(10 << 20)
		if err != nil {
			http.Error(w, "malformed multipart body", http.StatusBadRequest)
			return
		}
		defer func() { _ = form.RemoveAll() }()

		if vals := form.Value["model"]; len(vals) > 0 {
			f.lastModel = vals[0]
		}
		if vals := form.Value["prompt"]; len(vals) > 0 {
			f.lastPrompt = vals[0]
		}
		if files := form.File["image"]; len(files) > 0 {
			fh, openErr := files[0].Open()
			if openErr != nil {
				http.Error(w, "cannot open image part", http.StatusBadRequest)
				return
			}
			raw, readErr := io.ReadAll(fh)
			_ = fh.Close()
			if readErr != nil {
				http.Error(w, "cannot read image part", http.StatusBadRequest)
				return
			}
			f.lastImageRaw = raw
		}
		// This app's smile-simulation route only ever drives ImageToImage
		// (no mask), so an "image_edits" request here must never carry a
		// mask part -- proving the mask field is genuinely conditional.
		if masks := form.File["mask"]; len(masks) > 0 {
			http.Error(w, "unexpected mask part for an image-to-image request", http.StatusBadRequest)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data": []map[string]string{
				{"b64_json": base64.StdEncoding.EncodeToString(f.generatedPNG)},
			},
			"usage": map[string]any{
				"image_count": 1,
				"steps":       30,
				"size":        "1024x1024",
			},
		})
	}))
	t.Cleanup(f.Close)
	return f
}

// buildSmileSimTestServer wires up buildServer's real output behind an
// httptest.Server, with the ai-gateway image platform credential pointed
// at imgServer -- the same test-only-override pattern
// buildConsultTestServer already establishes for the chat credential.
func buildSmileSimTestServer(t *testing.T, imgServer *fakeOpenAIImageServer) (*httptest.Server, serverConfig) {
	t.Helper()

	cfg := testConfig(t)
	cfg.AIGatewayImageBaseURL = imgServer.URL
	cfg.AIGatewayImageAPIKey = "sk-test-smilesim-key"

	handler, cleanup, err := buildServer(t.Context(), cfg)
	if err != nil {
		t.Fatalf("buildServer: %v", err)
	}
	t.Cleanup(func() {
		if err := cleanup(); err != nil {
			t.Errorf("cleanup: %v", err)
		}
	})

	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	return srv, cfg
}

// smileSimRequest issues method against path on srv, authenticated as
// token -- neither smile-simulation route checks a demo-user-keyed
// permission of its own, so no X-Demo-User header is needed, mirroring
// consultSuggestRequest's identical shape for round 1's chat route.
func smileSimRequest(t *testing.T, srv *httptest.Server, method, path, token string, body []byte) *http.Response {
	t.Helper()

	var reader *bytes.Reader
	if body != nil {
		reader = bytes.NewReader(body)
	} else {
		reader = bytes.NewReader(nil)
	}
	req, err := http.NewRequest(method, srv.URL+path, reader)
	if err != nil {
		t.Fatalf("build request: %v", err)
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := srv.Client().Do(req)
	if err != nil {
		t.Fatalf("%s %s: %v", method, path, err)
	}
	return resp
}

// waitForSmileSimSucceeded polls the job-status route until it reports
// "succeeded" or deadline passes, decoding and returning the final
// response body either way -- the HTTP-level counterpart of go/jobs' own
// example_test.go's waitForTerminal, since this test observes the job
// only through smilesim's own route, never jobs.Queue directly.
func waitForSmileSimSucceeded(t *testing.T, srv *httptest.Server, token, jobID string, deadline time.Time) map[string]any {
	t.Helper()

	for {
		resp := smileSimRequest(t, srv, http.MethodGet, smileJobPathPrefix+jobID, token, nil)
		var out map[string]any
		if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
			resp.Body.Close()
			t.Fatalf("decode job status: %v", err)
		}
		resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			t.Fatalf("GET %s status = %d, want %d; body = %+v", smileJobPathPrefix+jobID, resp.StatusCode, http.StatusOK, out)
		}
		status, _ := out["status"].(string)
		if status == "succeeded" || status == "dead_letter" || status == "cancelled" {
			return out
		}
		if time.Now().After(deadline) {
			t.Fatalf("job %s did not reach a terminal status before the deadline; last status = %q, body = %+v", jobID, status, out)
		}
		time.Sleep(10 * time.Millisecond)
	}
}

// TestSmileSimulation_ImageToImage_EndToEnd is round 2's mandatory
// end-to-end proof: a patient photo really travels through
// internal/smilesim.Service, through go/ai-gateway's Gateway.GenerateImage
// async pipeline (credential resolution, model routing, the enqueued
// jobs.Task, the job handler's storage read, the
// OpenAICompatibleImageProvider's real multipart HTTP call, and the
// job handler's storage write), to a fake OpenAI-compatible images
// endpoint and back, landing as a brand new go/storage object this app's
// own storage HTTP surface can read.
func TestSmileSimulation_ImageToImage_EndToEnd(t *testing.T) {
	imgServer := newFakeOpenAIImageServer(t)
	srv, cfg := buildSmileSimTestServer(t, imgServer)

	token := registerAndAuthenticate(t, srv, cfg, "tenant-acme", "smilesim-owner")

	// Upload and complete a patient photo through storage's own real HTTP
	// surface -- the same helper storage_flow_test.go's own suite uses.
	photo := jpegWithExif(t)
	completedPhoto := uploadAndComplete(t, srv, token, photo, "")
	if completedPhoto.State != "completed" {
		t.Fatalf("photo state = %q, want completed", completedPhoto.State)
	}

	// storage's own completion pipeline strips the photo's EXIF metadata
	// (go/storage's structural sanitizer), so the bytes actually stored --
	// and therefore the bytes the job handler must read back and forward
	// to the vendor -- are shorter than what was uploaded. Read the
	// STORED content back through storage's own HTTP surface so this
	// test's later byte-for-byte comparison is against the real ground
	// truth, not the pre-sanitized upload.
	contentResp := storageRequest(t, srv, http.MethodGet,
		"/api/v1/storage/objects/"+completedPhoto.ID+"/content", token, demoOwnerUserID, "", nil)
	storedPhoto, err := io.ReadAll(contentResp.Body)
	contentResp.Body.Close()
	if err != nil {
		t.Fatalf("read stored photo content: %v", err)
	}
	if contentResp.StatusCode != http.StatusOK {
		t.Fatalf("GET stored photo content status = %d, want %d", contentResp.StatusCode, http.StatusOK)
	}

	// Enqueue the simulation.
	simulateBody, err := json.Marshal(map[string]string{"photo_object_id": completedPhoto.ID})
	if err != nil {
		t.Fatalf("marshal simulate request: %v", err)
	}
	resp := smileSimRequest(t, srv, http.MethodPost, smileSimulatePath, token, simulateBody)
	var simulateOut struct {
		JobID string `json:"job_id"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&simulateOut); err != nil {
		resp.Body.Close()
		t.Fatalf("decode simulate response: %v", err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusAccepted {
		t.Fatalf("POST %s status = %d, want %d; body = %+v", smileSimulatePath, resp.StatusCode, http.StatusAccepted, simulateOut)
	}
	if simulateOut.JobID == "" {
		t.Fatal("simulate response carries no job_id")
	}

	// Poll until the async job completes.
	final := waitForSmileSimSucceeded(t, srv, token, simulateOut.JobID, time.Now().Add(5*time.Second))
	if status, _ := final["status"].(string); status != "succeeded" {
		t.Fatalf("final job status = %v, want \"succeeded\"; body = %+v", final["status"], final)
	}
	outputObjectID, _ := final["output_object_id"].(string)
	if outputObjectID == "" {
		t.Fatalf("succeeded job carries no output_object_id: %+v", final)
	}
	if outputObjectID == completedPhoto.ID {
		t.Fatalf("output object id %q must never equal the input photo's own id -- the job handler must write a NEW object", outputObjectID)
	}
	usage, _ := final["usage"].(map[string]any)
	if usage == nil {
		t.Fatalf("succeeded job carries no usage: %+v", final)
	}
	if imageCount, _ := usage["image_count"].(float64); imageCount != 1 {
		t.Fatalf("usage.image_count = %v, want 1", usage["image_count"])
	}
	if steps, _ := usage["steps"].(float64); steps != 30 {
		t.Fatalf("usage.steps = %v, want 30 -- the fake server's own scripted usage dimension", usage["steps"])
	}
	if tier, _ := usage["resolution_tier"].(string); tier != "1024x1024" {
		t.Fatalf("usage.resolution_tier = %q, want %q", tier, "1024x1024")
	}

	// The fake server's own recorded request proves this app's wiring
	// (aigateway.WithModelRoute(smilesim.LogicalModel, ...) in server.go)
	// actually ran end to end, rather than the test somehow
	// short-circuiting the gateway: the vendor model id is the routed
	// "dall-e-3", never the logical "image:smile-simulation" key business
	// code asked for, and the uploaded photo's own bytes traveled all the
	// way to the fake vendor as the multipart "image" part.
	if imgServer.lastModel != "dall-e-3" {
		t.Fatalf("fake server saw model = %q, want the routed vendor model %q, never the logical key", imgServer.lastModel, "dall-e-3")
	}
	if imgServer.lastPrompt == "" {
		t.Fatal("fake server saw an empty prompt")
	}
	if !bytes.Equal(imgServer.lastImageRaw, storedPhoto) {
		t.Fatalf("fake server's received image part (%d bytes) does not match the photo's stored bytes (%d bytes) -- the job handler must read the SAME bytes back from storage", len(imgServer.lastImageRaw), len(storedPhoto))
	}

	// The generated image is readable back through storage's own HTTP
	// surface, as a genuinely separate, completed object.
	getResp := storageRequest(t, srv, http.MethodGet, "/api/v1/storage/objects/"+outputObjectID, token, demoOwnerUserID, "", nil)
	outputObject := decodeStorageObject(t, getResp, http.StatusOK, "GET the generated simulation object")
	if outputObject.State != "completed" {
		t.Fatalf("generated object state = %q, want completed", outputObject.State)
	}
	if outputObject.MimeType != "image/png" {
		t.Fatalf("generated object mime = %q, want image/png", outputObject.MimeType)
	}
}
