//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// OrgAcceptInvitationRequest defines model for OrgAcceptInvitationRequest.
type OrgAcceptInvitationRequest struct {
	Token string `json:"token"`
}

// OrgCreateInvitationRequest defines model for OrgCreateInvitationRequest.
type OrgCreateInvitationRequest struct {
	// Email The invitee's address.
	Email string `json:"email"`

	// Locale The RECIPIENT's preferred language for the invitation email, an IETF tag such as "en-US" or "zh-CN" -- something the inviting operator, who knows the invitee, supplies explicitly, since the server has no request of the invitee's own to read a language preference from at invite-creation time. Omitted, or naming a language the platform carries no message catalog for, falls back to the platform default; it is NEVER inferred from the inviting operator's own browser or UI language.
	Locale *string `json:"locale,omitempty"`

	// NodeID The node the invitee will be bound to on acceptance.
	NodeID string `json:"nodeId"`
}

// OrgCreateNodeRequest defines model for OrgCreateNodeRequest.
type OrgCreateNodeRequest struct {
	Kind *string `json:"kind,omitempty"`
	Name string  `json:"name"`

	// ParentID Absent or "" creates the tenant's root node instead of a child.
	ParentID *string `json:"parentId,omitempty"`
}

// OrgError The structured {code, params} error envelope every speed API returns instead of localized text (backend coding standard §6.2; docs/internal/11-cross-cutting.md) -- a client resolves code through its own i18n catalog, populated from this module's Locales() resources for the codes documented in AGENTS.md's error index.
type OrgError struct {
	// Code Example: org.node_not_found
	Code   *string                 `json:"code,omitempty"`
	Params *map[string]interface{} `json:"params,omitempty"`
}

// OrgInvitation A pending (or resolved) offer to join the tenant. The invitee's address is deliberately absent from this schema: it is PII, encrypted at rest, and org's own convention (see invite.go) is never to echo it into anything that leaves the process boundary. emailIndex is the address's HMAC blind index -- safe to display for de-duplication purposes, and not reversible to the address without the index key.
type OrgInvitation struct {
	CreatedAt  *time.Time `json:"createdAt,omitempty"`
	EmailIndex *string    `json:"emailIndex,omitempty"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`
	ID         *string    `json:"id,omitempty"`
	NodeID     *string    `json:"nodeId,omitempty"`

	// Status One of "pending", "accepted", "revoked".
	Status *string `json:"status,omitempty"`
}

// OrgListInvitationsResponse defines model for OrgListInvitationsResponse.
type OrgListInvitationsResponse struct {
	Invitations *[]OrgInvitation `json:"invitations,omitempty"`
}

// OrgListMembersResponse defines model for OrgListMembersResponse.
type OrgListMembersResponse struct {
	Members *[]OrgMembership `json:"members,omitempty"`
}

// OrgListNodesResponse defines model for OrgListNodesResponse.
type OrgListNodesResponse struct {
	Nodes *[]OrgNode `json:"nodes,omitempty"`
}

// OrgMembership One person's binding to a node of a tenant's organization tree.
type OrgMembership struct {
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	MembershipID *string    `json:"membershipId,omitempty"`
	NodeID       *string    `json:"nodeId,omitempty"`

	// Status One of "active", "invited", "suspended".
	Status *string `json:"status,omitempty"`

	// UserID An id in authn's users table, carried as an opaque string -- org stores no other identity data about the user (root CLAUDE.md's module-boundary rule).
	UserID *string `json:"userId,omitempty"`
}

// OrgMoveNodeRequest defines model for OrgMoveNodeRequest.
type OrgMoveNodeRequest struct {
	// ParentID The new parent's id.
	ParentID string `json:"parentId"`
}

// OrgNode One node of a tenant's organization tree.
type OrgNode struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Depth The number of ancestors; 0 on the tenant root.
	Depth *int `json:"depth,omitempty"`

	// ID Application-generated UUID.
	ID *string `json:"id,omitempty"`

	// Kind The tenant's own business classification of the node (for example "group", "region", "store"); org does not enumerate legal values.
	Kind *string `json:"kind,omitempty"`
	Name *string `json:"name,omitempty"`

	// ParentID The parent node's id, or "" on the tenant root.
	ParentID *string `json:"parentId,omitempty"`

	// Path The materialized path from the tenant root down to and including this node (see go/org/path.go). Read-only.
	Path      *string    `json:"path,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// OrgRenameNodeRequest defines model for OrgRenameNodeRequest.
type OrgRenameNodeRequest struct {
	Name string `json:"name"`
}

// NodeID defines model for NodeID.
type NodeID = string

// OrgListMembersParams defines parameters for OrgListMembers.
type OrgListMembersParams struct {
	NodeID *string `form:"nodeId,omitempty" json:"nodeId,omitempty"`
}

// OrgListNodesParams defines parameters for OrgListNodes.
type OrgListNodesParams struct {
	ParentID *string `form:"parentId,omitempty" json:"parentId,omitempty"`
}

// OrgDeleteNodeParams defines parameters for OrgDeleteNode.
type OrgDeleteNodeParams struct {
	Cascade *bool `form:"cascade,omitempty" json:"cascade,omitempty"`
}

// OrgCreateInvitationJSONRequestBody defines body for OrgCreateInvitation for application/json ContentType.
type OrgCreateInvitationJSONRequestBody = OrgCreateInvitationRequest

// OrgAcceptInvitationJSONRequestBody defines body for OrgAcceptInvitation for application/json ContentType.
type OrgAcceptInvitationJSONRequestBody = OrgAcceptInvitationRequest

// OrgCreateNodeJSONRequestBody defines body for OrgCreateNode for application/json ContentType.
type OrgCreateNodeJSONRequestBody = OrgCreateNodeRequest

// OrgRenameNodeJSONRequestBody defines body for OrgRenameNode for application/json ContentType.
type OrgRenameNodeJSONRequestBody = OrgRenameNodeRequest

// OrgMoveNodeJSONRequestBody defines body for OrgMoveNode for application/json ContentType.
type OrgMoveNodeJSONRequestBody = OrgMoveNodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// OrgListInvitations List the caller's tenant's pending invitations.
	// (GET /api/v1/org/invitations)
	OrgListInvitations(w http.ResponseWriter, r *http.Request)
	// OrgCreateInvitation Invite a person into the caller's tenant, at a node.
	// (POST /api/v1/org/invitations)
	OrgCreateInvitation(w http.ResponseWriter, r *http.Request)
	// OrgAcceptInvitation Accept an invitation, becoming a member of the caller's tenant.
	// (POST /api/v1/org/invitations/accept)
	OrgAcceptInvitation(w http.ResponseWriter, r *http.Request)
	// OrgListMembers List the members bound to a node's subtree.
	// (GET /api/v1/org/members)
	OrgListMembers(w http.ResponseWriter, r *http.Request, params OrgListMembersParams)
	// OrgRemoveMember Remove a member from the caller's tenant.
	// (DELETE /api/v1/org/members/{userId})
	OrgRemoveMember(w http.ResponseWriter, r *http.Request, userID string)
	// OrgListNodes List nodes of the caller's tenant's organization tree.
	// (GET /api/v1/org/nodes)
	OrgListNodes(w http.ResponseWriter, r *http.Request, params OrgListNodesParams)
	// OrgCreateNode Create a node in the caller's tenant's organization tree.
	// (POST /api/v1/org/nodes)
	OrgCreateNode(w http.ResponseWriter, r *http.Request)
	// OrgDeleteNode Delete a node.
	// (DELETE /api/v1/org/nodes/{nodeId})
	OrgDeleteNode(w http.ResponseWriter, r *http.Request, nodeID NodeID, params OrgDeleteNodeParams)
	// OrgGetNode Get one node of the caller's tenant's organization tree.
	// (GET /api/v1/org/nodes/{nodeId})
	OrgGetNode(w http.ResponseWriter, r *http.Request, nodeID NodeID)
	// OrgRenameNode Rename a node.
	// (PATCH /api/v1/org/nodes/{nodeId})
	OrgRenameNode(w http.ResponseWriter, r *http.Request, nodeID NodeID)
	// OrgMoveNode Re-parent a node, carrying its whole subtree with it.
	// (POST /api/v1/org/nodes/{nodeId}/move)
	OrgMoveNode(w http.ResponseWriter, r *http.Request, nodeID NodeID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// OrgListInvitations operation middleware
func (siw *ServerInterfaceWrapper) OrgListInvitations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgListInvitations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgCreateInvitation operation middleware
func (siw *ServerInterfaceWrapper) OrgCreateInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgCreateInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgAcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) OrgAcceptInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgAcceptInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgListMembers operation middleware
func (siw *ServerInterfaceWrapper) OrgListMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgListMembersParams

	// ------------- Optional query parameter "nodeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "nodeId", r.URL.Query(), &params.NodeID, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "nodeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nodeId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgListMembers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgRemoveMember operation middleware
func (siw *ServerInterfaceWrapper) OrgRemoveMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgRemoveMember(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgListNodes operation middleware
func (siw *ServerInterfaceWrapper) OrgListNodes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgListNodesParams

	// ------------- Optional query parameter "parentId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "parentId", r.URL.Query(), &params.ParentID, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "parentId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parentId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgListNodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgCreateNode operation middleware
func (siw *ServerInterfaceWrapper) OrgCreateNode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgCreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgDeleteNode operation middleware
func (siw *ServerInterfaceWrapper) OrgDeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "nodeId" -------------
	var nodeID NodeID

	err = runtime.BindStyledParameterWithOptions("simple", "nodeId", r.PathValue("nodeId"), &nodeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nodeId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OrgDeleteNodeParams

	// ------------- Optional query parameter "cascade" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cascade", r.URL.Query(), &params.Cascade, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cascade"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cascade", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgDeleteNode(w, r, nodeID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgGetNode operation middleware
func (siw *ServerInterfaceWrapper) OrgGetNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "nodeId" -------------
	var nodeID NodeID

	err = runtime.BindStyledParameterWithOptions("simple", "nodeId", r.PathValue("nodeId"), &nodeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgGetNode(w, r, nodeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgRenameNode operation middleware
func (siw *ServerInterfaceWrapper) OrgRenameNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "nodeId" -------------
	var nodeID NodeID

	err = runtime.BindStyledParameterWithOptions("simple", "nodeId", r.PathValue("nodeId"), &nodeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgRenameNode(w, r, nodeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrgMoveNode operation middleware
func (siw *ServerInterfaceWrapper) OrgMoveNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "nodeId" -------------
	var nodeID NodeID

	err = runtime.BindStyledParameterWithOptions("simple", "nodeId", r.PathValue("nodeId"), &nodeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrgMoveNode(w, r, nodeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/org/nodes", wrapper.OrgListNodes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/org/nodes", wrapper.OrgCreateNode)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/org/nodes/{nodeId}", wrapper.OrgDeleteNode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/org/nodes/{nodeId}", wrapper.OrgGetNode)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/org/nodes/{nodeId}", wrapper.OrgRenameNode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/org/nodes/{nodeId}/move", wrapper.OrgMoveNode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/org/members", wrapper.OrgListMembers)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/org/members/{userId}", wrapper.OrgRemoveMember)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/org/invitations", wrapper.OrgListInvitations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/org/invitations", wrapper.OrgCreateInvitation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/org/invitations/accept", wrapper.OrgAcceptInvitation)

	return m
}
