-- integration_webhook_subscriptions.secret stores CIPHERTEXT written
-- through WebhookSecretSerializerName's GORM serializer (webhook_model.go),
-- never plaintext: AES-256-GCM ciphertext is effectively random binary
-- data, which is not valid UTF-8 text almost every time it is generated.
-- PostgreSQL enforces its configured client/server encoding (UTF8, this
-- project's only supported one) on every VARCHAR/TEXT value, so the column
-- must be BYTEA on this dialect; a VARCHAR column would refuse a genuine
-- encrypted secret with "invalid byte sequence for encoding \"UTF8\"".
--
-- go/org's identically-shaped precedent -- org_invitations.email,
-- encrypted under EmailSerializerName the exact same way -- stores the
-- same class of value as BYTEA on PostgreSQL
-- (go/org/migrations/postgres/0003_create_org_invitations.sql) and BLOB on
-- SQLite (go/org/migrations/sqlite/0003_create_org_invitations.sql); this
-- column follows that precedent.
--
-- No sqlite/ sibling accompanies this file, unlike every other migration
-- in this module: SQLite's TEXT/VARCHAR columns have no fixed encoding to
-- violate -- SQLite's dynamic type system stores arbitrary binary through
-- a VARCHAR-declared column without error -- so nothing on that dialect
-- needs to change. The asymmetry is deliberate and applies cleanly:
-- dbkit.MigrationRegistry.Apply reads each dialect's own subdirectory
-- independently and has no cross-dialect pairing requirement
-- (go/dbkit/migrations.go's own migrationFiles), so a dialect-only
-- migration like this one stands alone.
--
-- The column is dropped and re-added rather than converted in place with
-- a USING cast: no existing ciphertext on this dialect needs preserving by
-- a cast, and a cast's own encoding assumptions would be exactly as
-- fragile as the type mismatch it papers over.
ALTER TABLE integration_webhook_subscriptions DROP COLUMN secret;
ALTER TABLE integration_webhook_subscriptions ADD COLUMN secret BYTEA NOT NULL DEFAULT '';
ALTER TABLE integration_webhook_subscriptions ALTER COLUMN secret DROP DEFAULT;
