package authn

import (
	"errors"
	"sync"
	"testing"
	"time"

	"gorm.io/gorm"

	"github.com/vislake/speed/go/authn/internal/testutil"
	"github.com/vislake/speed/go/dbkit"
	"github.com/vislake/speed/go/pkgcore"
)

// newTestUserRepository builds a UserRepository over db with the test
// blind-index key.
func newTestUserRepository(t *testing.T, db *gorm.DB) *UserRepository {
	t.Helper()

	emailIndex, err := dbkit.NewBlindIndexer("email_index", testutil.BlindIndexKey(), dbkit.NormalizeEmail)
	if err != nil {
		t.Fatalf("build the email blind indexer: %v", err)
	}
	phoneIndex, err := dbkit.NewBlindIndexer("phone_index", testutil.BlindIndexKey(), dbkit.NormalizePhoneE164)
	if err != nil {
		t.Fatalf("build the phone blind indexer: %v", err)
	}
	repo, err := NewUserRepository(db, emailIndex, phoneIndex)
	if err != nil {
		t.Fatalf("NewUserRepository() error = %v", err)
	}
	return repo
}

// newTestSessionRepository, newTestRefreshTokenRepository and
// newTestLoginAttemptRepository keep the constructor's error out of each
// test's own scope, so the tests below read as one flow rather than as a
// sequence of construction checks. The constructors' rejection behaviour is
// covered once, in TestRepositoryConstructors_RejectAMissingDependency.
func newTestSessionRepository(t *testing.T, db *gorm.DB) *SessionRepository {
	t.Helper()
	repo, err := NewSessionRepository(db)
	if err != nil {
		t.Fatalf("NewSessionRepository() error = %v", err)
	}
	return repo
}

func newTestRefreshTokenRepository(t *testing.T, db *gorm.DB) *RefreshTokenRepository {
	t.Helper()
	repo, err := NewRefreshTokenRepository(db)
	if err != nil {
		t.Fatalf("NewRefreshTokenRepository() error = %v", err)
	}
	return repo
}

func newTestLoginAttemptRepository(t *testing.T, db *gorm.DB) *LoginAttemptRepository {
	t.Helper()
	repo, err := NewLoginAttemptRepository(db)
	if err != nil {
		t.Fatalf("NewLoginAttemptRepository() error = %v", err)
	}
	return repo
}

func TestUserRepository_CreateAndFindByID(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestUserRepository(t, db)
	ctx := t.Context()

	user := &User{Email: "round.trip@example.com", DisplayName: "Round Trip", PasswordHash: "hash"}
	if err := repo.Create(ctx, user); err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if user.ID == "" {
		t.Fatal("Create() left the ID empty; ids are generated by the application")
	}

	got, err := repo.FindByID(ctx, user.ID)
	if err != nil {
		t.Fatalf("FindByID() error = %v", err)
	}
	if got.Email != user.Email || got.DisplayName != "Round Trip" {
		t.Errorf("FindByID() = %+v, want the created user", got)
	}
	if got.Status != UserStatusActive {
		t.Errorf("Status = %q, want %q by default", got.Status, UserStatusActive)
	}

	if _, err := repo.FindByID(ctx, "no-such-id"); !errors.Is(err, ErrNotFound) {
		t.Errorf("FindByID(missing) error = %v, want ErrNotFound", err)
	}
}

// TestUserRepository_FindByEmail_IsSpellingInsensitive is the whole point of
// the blind index: the address is encrypted, so no query can filter on it,
// yet an exact lookup still has to work regardless of how the address was
// typed.
func TestUserRepository_FindByEmail_IsSpellingInsensitive(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestUserRepository(t, db)
	ctx := t.Context()

	user := &User{Email: "Casing.Matters@Example.COM", PasswordHash: "hash"}
	if err := repo.Create(ctx, user); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	for _, spelling := range []string{
		"Casing.Matters@Example.COM",
		"casing.matters@example.com",
		"  casing.matters@EXAMPLE.com  ",
		"CASING.MATTERS@EXAMPLE.COM",
	} {
		got, err := repo.FindByEmail(ctx, spelling)
		if err != nil {
			t.Fatalf("FindByEmail(%q) error = %v", spelling, err)
		}
		if got.ID != user.ID {
			t.Errorf("FindByEmail(%q) found %s, want %s", spelling, got.ID, user.ID)
		}
	}

	if _, err := repo.FindByEmail(ctx, "someone.else@example.com"); !errors.Is(err, ErrNotFound) {
		t.Errorf("FindByEmail(unknown) error = %v, want ErrNotFound", err)
	}
}

// TestUserRepository_FindByPhone_IsFormattingInsensitive is the same property
// for phone numbers, whose canonical form is E.164.
func TestUserRepository_FindByPhone_IsFormattingInsensitive(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestUserRepository(t, db)
	ctx := t.Context()

	user := &User{Phone: "+86 138 0000 0000", PasswordHash: "hash"}
	if err := repo.Create(ctx, user); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	for _, spelling := range []string{
		"+86 138 0000 0000",
		"+8613800000000",
		"+86-138-0000-0000",
		"+86(138)0000.0000",
	} {
		got, err := repo.FindByPhone(ctx, spelling)
		if err != nil {
			t.Fatalf("FindByPhone(%q) error = %v", spelling, err)
		}
		if got.ID != user.ID {
			t.Errorf("FindByPhone(%q) found %s, want %s", spelling, got.ID, user.ID)
		}
	}

	// A bare national number has no E.164 canonical form -- dbkit's
	// normalizer refuses to guess a country -- so it is reported as an
	// invalid phone rather than silently indexed under a wrong country.
	if _, err := repo.FindByPhone(ctx, "13800000000"); !hasCode(err, ErrInvalidPhone.Code) {
		t.Errorf("FindByPhone(national form) error = %v, want code %q", err, ErrInvalidPhone.Code)
	}
}

// TestUserRepository_DuplicateIdentifierIsRejectedByTheDatabase proves the
// UNIQUE index is on the blind index, which is what makes "one account per
// real-world address" true rather than "one account per spelling".
func TestUserRepository_DuplicateIdentifierIsRejectedByTheDatabase(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestUserRepository(t, db)
	ctx := t.Context()

	if err := repo.Create(ctx, &User{Email: "unique@example.com", PasswordHash: "hash"}); err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	// A different spelling of the same address must still collide.
	if err := repo.Create(ctx, &User{Email: "UNIQUE@Example.com", PasswordHash: "hash"}); err == nil {
		t.Fatal("a second account with the same address in a different casing was accepted")
	}
}

// TestUserRepository_AccountsWithoutAPhoneCoexist proves the nullable unique
// index behaves as intended: the second account with no phone number must not
// collide with the first.
func TestUserRepository_AccountsWithoutAPhoneCoexist(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestUserRepository(t, db)
	ctx := t.Context()

	for _, address := range []string{"first@example.com", "second@example.com", "third@example.com"} {
		user := &User{Email: address, PasswordHash: "hash"}
		if err := repo.Create(ctx, user); err != nil {
			t.Fatalf("Create(%s) error = %v; accounts without a phone number must not collide", address, err)
		}
		if user.PhoneIndex != nil {
			t.Errorf("PhoneIndex = %v, want nil for an account with no phone", *user.PhoneIndex)
		}
	}
}

// TestUserRepository_SaveRecomputesTheIndex proves a changed address cannot
// leave a stale index behind, which would leave the account findable under
// its old address and not under its new one.
func TestUserRepository_SaveRecomputesTheIndex(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestUserRepository(t, db)
	ctx := t.Context()

	user := &User{Email: "before@example.com", PasswordHash: "hash"}
	if err := repo.Create(ctx, user); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	user.Email = "after@example.com"
	if err := repo.Save(ctx, user); err != nil {
		t.Fatalf("Save() error = %v", err)
	}

	if _, err := repo.FindByEmail(ctx, "before@example.com"); !errors.Is(err, ErrNotFound) {
		t.Errorf("the old address still finds the account: err = %v", err)
	}
	got, err := repo.FindByEmail(ctx, "after@example.com")
	if err != nil {
		t.Fatalf("FindByEmail(new address) error = %v", err)
	}
	if got.ID != user.ID {
		t.Errorf("FindByEmail(new address) found %s, want %s", got.ID, user.ID)
	}
}

func TestUserRepository_RejectsAnUnusableIdentifier(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestUserRepository(t, db)
	ctx := t.Context()

	if err := repo.Create(ctx, &User{Email: "   ", PasswordHash: "hash"}); !hasCode(err, ErrInvalidEmail.Code) {
		t.Errorf("Create(blank email) error = %v, want code %q", err, ErrInvalidEmail.Code)
	}
	if err := repo.Create(ctx, &User{Phone: "not a number", PasswordHash: "hash"}); !hasCode(err, ErrInvalidPhone.Code) {
		t.Errorf("Create(unusable phone) error = %v, want code %q", err, ErrInvalidPhone.Code)
	}
}

// TestSessionRepository_RevokeHasExactlyOneWinner covers the conditional
// update: the status is part of the WHERE clause, so a second revocation of
// the same session reports that it changed nothing.
func TestSessionRepository_RevokeHasExactlyOneWinner(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestSessionRepository(t, db)
	ctx := t.Context()
	now := time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC)

	session := &Session{UserID: "user-1", CreatedAt: now, LastSeenAt: now, ExpiresAt: now.Add(time.Hour)}
	if err := repo.Create(ctx, session); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	first, err := repo.Revoke(ctx, session.ID, RevokeReasonLogout, now)
	if err != nil {
		t.Fatalf("Revoke() error = %v", err)
	}
	if !first {
		t.Fatal("the first Revoke() reported no change")
	}

	second, err := repo.Revoke(ctx, session.ID, RevokeReasonLogout, now)
	if err != nil {
		t.Fatalf("Revoke() error = %v", err)
	}
	if second {
		t.Error("the second Revoke() reported a change; the status must be part of the WHERE clause")
	}

	stored, err := repo.FindByID(ctx, session.ID)
	if err != nil {
		t.Fatalf("FindByID() error = %v", err)
	}
	if stored.Status != SessionStatusRevoked || stored.RevokedAt == nil {
		t.Errorf("stored session = %+v, want a revoked status and a revocation timestamp", stored)
	}
}

func TestSessionRepository_SetCurrentTenantAndListByUser(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestSessionRepository(t, db)
	ctx := t.Context()
	base := time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC)

	var ids []string
	for i := range 3 {
		s := &Session{
			UserID: "user-1", CurrentTenantID: "tenant-a",
			CreatedAt: base.Add(time.Duration(i) * time.Minute), LastSeenAt: base, ExpiresAt: base.Add(time.Hour),
		}
		if err := repo.Create(ctx, s); err != nil {
			t.Fatalf("Create() error = %v", err)
		}
		ids = append(ids, s.ID)
	}
	// A session belonging to someone else must never appear in the list.
	other := &Session{UserID: "user-2", CreatedAt: base, LastSeenAt: base, ExpiresAt: base.Add(time.Hour)}
	if err := repo.Create(ctx, other); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	listed, err := repo.ListByUser(ctx, "user-1")
	if err != nil {
		t.Fatalf("ListByUser() error = %v", err)
	}
	if len(listed) != 3 {
		t.Fatalf("ListByUser() returned %d sessions, want 3", len(listed))
	}
	if listed[0].ID != ids[2] {
		t.Errorf("ListByUser()[0] = %s, want the newest session %s", listed[0].ID, ids[2])
	}

	if setErr := repo.SetCurrentTenant(ctx, ids[0], pkgcore.TenantID("tenant-b")); setErr != nil {
		t.Fatalf("SetCurrentTenant() error = %v", setErr)
	}
	stored, err := repo.FindByID(ctx, ids[0])
	if err != nil {
		t.Fatalf("FindByID() error = %v", err)
	}
	if stored.CurrentTenantID != "tenant-b" {
		t.Errorf("CurrentTenantID = %q, want %q", stored.CurrentTenantID, "tenant-b")
	}
}

// TestRefreshTokenRepository_ConsumeHasExactlyOneWinnerUnderConcurrency is the
// single-winner property replay detection rests on. Twenty goroutines race to
// consume one token; exactly one must succeed, because the loser is what the
// caller reads as a replay.
func TestRefreshTokenRepository_ConsumeHasExactlyOneWinnerUnderConcurrency(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestRefreshTokenRepository(t, db)
	ctx := t.Context()
	now := time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC)

	token := &RefreshToken{
		SessionID: "session-1", UserID: "user-1", FamilyID: "family-1",
		TokenHash: "hash-1", CreatedAt: now, ExpiresAt: now.Add(time.Hour),
	}
	if err := repo.Create(ctx, token); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	const racers = 20
	var (
		wg      sync.WaitGroup
		mu      sync.Mutex
		winners int
		failure error
	)
	wg.Add(racers)
	for range racers {
		go func() {
			defer wg.Done()
			won, err := repo.Consume(ctx, token.ID, now)
			mu.Lock()
			defer mu.Unlock()
			if err != nil {
				failure = err
				return
			}
			if won {
				winners++
			}
		}()
	}
	wg.Wait()

	if failure != nil {
		t.Fatalf("Consume() error = %v", failure)
	}
	if winners != 1 {
		t.Fatalf("Consume() reported %d winners across %d concurrent calls, want exactly 1", winners, racers)
	}

	stored, err := repo.FindByHash(ctx, "hash-1")
	if err != nil {
		t.Fatalf("FindByHash() error = %v", err)
	}
	if stored.Status != RefreshTokenStatusRotated || stored.ConsumedAt == nil {
		t.Errorf("stored token = %+v, want a rotated status and a consumption timestamp", stored)
	}
}

func TestRefreshTokenRepository_RevokeFamilyAndBySession(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestRefreshTokenRepository(t, db)
	ctx := t.Context()
	now := time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC)

	mk := func(hash, family, session string) *RefreshToken {
		token := &RefreshToken{
			SessionID: session, UserID: "user-1", FamilyID: family,
			TokenHash: hash, CreatedAt: now, ExpiresAt: now.Add(time.Hour),
		}
		if err := repo.Create(ctx, token); err != nil {
			t.Fatalf("Create(%s) error = %v", hash, err)
		}
		return token
	}
	mk("h1", "family-1", "session-1")
	mk("h2", "family-1", "session-1")
	untouched := mk("h3", "family-2", "session-2")

	revoked, err := repo.RevokeFamily(ctx, "family-1", now)
	if err != nil {
		t.Fatalf("RevokeFamily() error = %v", err)
	}
	if revoked != 2 {
		t.Errorf("RevokeFamily() revoked %d tokens, want 2", revoked)
	}

	stored, err := repo.FindByHash(ctx, "h3")
	if err != nil {
		t.Fatalf("FindByHash() error = %v", err)
	}
	if stored.Status != RefreshTokenStatusActive {
		t.Errorf("an unrelated family's token was revoked: %+v", stored)
	}

	if _, revokeErr := repo.RevokeBySession(ctx, untouched.SessionID, now); revokeErr != nil {
		t.Fatalf("RevokeBySession() error = %v", revokeErr)
	}
	stored, err = repo.FindByHash(ctx, "h3")
	if err != nil {
		t.Fatalf("FindByHash() error = %v", err)
	}
	if stored.Status != RefreshTokenStatusRevoked {
		t.Errorf("Status = %q, want %q after RevokeBySession", stored.Status, RefreshTokenStatusRevoked)
	}
}

func TestLoginAttemptRepository_ListByUserIsNewestFirstAndBounded(t *testing.T) {
	t.Parallel()

	db := testutil.NewDB(t)
	repo := newTestLoginAttemptRepository(t, db)
	ctx := t.Context()
	base := time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC)

	for i := range 5 {
		attempt := &LoginAttempt{
			UserID: "user-1", Method: MethodPassword, Result: LoginResultFailure,
			FailureReason: FailureReasonBadPassword,
			CreatedAt:     base.Add(time.Duration(i) * time.Minute),
		}
		if err := repo.Create(ctx, attempt); err != nil {
			t.Fatalf("Create() error = %v", err)
		}
	}
	if err := repo.Create(ctx, &LoginAttempt{
		UserID: "user-2", Method: MethodPassword, Result: LoginResultSuccess, CreatedAt: base,
	}); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	listed, err := repo.ListByUser(ctx, "user-1", 3)
	if err != nil {
		t.Fatalf("ListByUser() error = %v", err)
	}
	if len(listed) != 3 {
		t.Fatalf("ListByUser(limit 3) returned %d rows, want 3", len(listed))
	}
	if !listed[0].CreatedAt.After(listed[2].CreatedAt) {
		t.Error("ListByUser() is not newest-first")
	}
	for _, attempt := range listed {
		if attempt.UserID != "user-1" {
			t.Errorf("ListByUser() returned another user's attempt: %+v", attempt)
		}
	}

	all, err := repo.ListByUser(ctx, "user-1", 0)
	if err != nil {
		t.Fatalf("ListByUser(no limit) error = %v", err)
	}
	if len(all) != 5 {
		t.Errorf("ListByUser(no limit) returned %d rows, want all 5 under the default bound", len(all))
	}
}

func TestRepositoryConstructors_RejectAMissingDependency(t *testing.T) {
	t.Parallel()

	emailIndex, err := dbkit.NewBlindIndexer("email_index", testutil.BlindIndexKey(), dbkit.NormalizeEmail)
	if err != nil {
		t.Fatalf("build the email blind indexer: %v", err)
	}

	if _, err := NewUserRepository(nil, emailIndex, emailIndex); err == nil {
		t.Error("NewUserRepository(nil db) error = nil, want a rejection")
	}
	if _, err := NewUserRepository(testutil.NewDB(t), nil, nil); err == nil {
		t.Error("NewUserRepository(no indexers) error = nil, want a rejection")
	}
	if _, err := NewSessionRepository(nil); err == nil {
		t.Error("NewSessionRepository(nil) error = nil, want a rejection")
	}
	if _, err := NewRefreshTokenRepository(nil); err == nil {
		t.Error("NewRefreshTokenRepository(nil) error = nil, want a rejection")
	}
	if _, err := NewLoginAttemptRepository(nil); err == nil {
		t.Error("NewLoginAttemptRepository(nil) error = nil, want a rejection")
	}
}

func TestRegisterPIISerializer_RejectsANilCipher(t *testing.T) {
	t.Parallel()

	if err := RegisterPIISerializer(nil); err == nil {
		t.Error("RegisterPIISerializer(nil) error = nil, want a rejection")
	}
}
