//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// SharingAccessLogEntry One recorded access attempt against a share, granted or denied alike.
type SharingAccessLogEntry struct {
	// ID Application-generated UUID.
	ID *string `json:"id,omitempty"`

	// IP The viewer's address as the access request observed it.
	IP         *string    `json:"ip,omitempty"`
	OccurredAt *time.Time `json:"occurredAt,omitempty"`

	// Outcome "granted" or "denied" -- deliberately never which of Access's five refusal reasons applied; see this operation's own description.
	Outcome *string `json:"outcome,omitempty"`

	// Referrer The viewer's Referer header value, as given.
	Referrer *string `json:"referrer,omitempty"`

	// UserAgent The viewer's User-Agent header value, as given.
	UserAgent *string `json:"userAgent,omitempty"`
}

// SharingCreateShareRequest defines model for SharingCreateShareRequest.
type SharingCreateShareRequest struct {
	// ExpiresAt An explicit expiry, which must lie strictly in the future and no more than 30 days from now -- the platform's maximum share lifetime (rule 2's ceiling); anything else is refused with sharing.expiry_out_of_range. Omit to use the tenant's configured default (falling back to a fixed default when none is configured).
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Forever Requests a share that never expires. Always refused with sharing.expiry_required -- there is no way to make this surface create a never-expiring share; the field exists so a deliberate attempt to do so fails loudly and specifically.
	Forever *bool `json:"forever,omitempty"`

	// MaxViews Caps the number of granted accesses. Must be positive when given; omit for unlimited views.
	MaxViews *int `json:"maxViews,omitempty"`

	// Password An optional additional access password. Never stored or returned as given; see SharingShare's own passwordProtected field.
	Password *string `json:"password,omitempty"`

	// ResourceRef The opaque reference to the resource being shared, typically another module's own key scheme (e.g. a go/storage object id). Never interpreted by this module.
	ResourceRef string `json:"resourceRef"`

	// Sensitive Marks the shared resource as carrying sensitive personal information (rule 4). A true value fires this module's one audit action.
	Sensitive *bool `json:"sensitive,omitempty"`
}

// SharingCreateShareResponse defines model for SharingCreateShareResponse.
type SharingCreateShareResponse struct {
	// Share One share's own metadata, as its owner sees it. Deliberately carries no token (see sharing_createShare's own description for why) and no password (Share.PasswordHash is never serialized anywhere on this surface -- only whether one is set).
	Share SharingShare `json:"share"`

	// Token The share's bearer token, in the exact form /api/v1/sharing/access's token query parameter expects. Returned here exactly once -- see this operation's own description.
	Token string `json:"token"`
}

// SharingError defines model for SharingError.
type SharingError struct {
	// Code The structured error code, one of this module's error index entries (AGENTS.md).
	Code string `json:"code"`

	// Params Structured parameters for the code, when any apply.
	Params *map[string]interface{} `json:"params,omitempty"`
}

// SharingListAccessLogResponse defines model for SharingListAccessLogResponse.
type SharingListAccessLogResponse struct {
	// Entries The share's access log, newest first.
	Entries *[]SharingAccessLogEntry `json:"entries,omitempty"`
}

// SharingListSharesResponse defines model for SharingListSharesResponse.
type SharingListSharesResponse struct {
	// Shares Every share of the caller's tenant, newest first.
	Shares *[]SharingShare `json:"shares,omitempty"`
}

// SharingShare One share's own metadata, as its owner sees it. Deliberately carries no token (see sharing_createShare's own description for why) and no password (Share.PasswordHash is never serialized anywhere on this surface -- only whether one is set).
type SharingShare struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// ExpiresAt When this share stops being accessible. Never absent -- rule 2 forbids a share with no expiry.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// ID Application-generated UUID.
	ID *string `json:"id,omitempty"`

	// MaxViews The view ceiling this share was created with; absent when unlimited.
	MaxViews *int `json:"maxViews,omitempty"`

	// PasswordProtected Whether an access password is required. Never the password or its hash.
	PasswordProtected *bool `json:"passwordProtected,omitempty"`

	// ResourceRef The opaque reference to the resource this share exposes.
	ResourceRef *string `json:"resourceRef,omitempty"`

	// RevokedAt When this share was revoked; absent for a live share.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`

	// Sensitive Whether this share was created against a resource carrying sensitive personal information (rule 4's sensitive-resource confirmation).
	Sensitive *bool `json:"sensitive,omitempty"`

	// ViewCount How many accesses have been granted so far.
	ViewCount *int `json:"viewCount,omitempty"`
}

// ShareID defines model for ShareID.
type ShareID = string

// SharingAccessShareParams defines parameters for SharingAccessShare.
type SharingAccessShareParams struct {
	// Token The share's bearer token, exactly as returned once by the owner-facing Service.Create call. Never the share's own id, and never accepted from anywhere but this query parameter (root CLAUDE.md's multi-tenant isolation rule's spirit extended to this module's own bearer credential: there is exactly one legitimate source for it).
	Token string `form:"token" json:"token"`

	// XSharingPassword The share's access password, presented only when the share requires one (Share.PasswordHash set). Carried as a header, deliberately not a second query parameter: a query parameter routinely lands in server access logs and in a subsequently loaded page's Referer header, and this module's own established rule (repository.go's byTokenHash doc comment) is that a credential this module verifies never travels anywhere past the caller who presented it. The bearer token itself is this module's one already-accepted exception to that rule -- it is the URL itself, by round-1's own design (Share's doc comment) -- so putting the SECOND credential a share may require in the URL too would be a strictly weaker property than what this module already ships, not merely an equally weak one.
	XSharingPassword *string `json:"X-Sharing-Password,omitempty"`
}

// SharingCreateShareJSONRequestBody defines body for SharingCreateShare for application/json ContentType.
type SharingCreateShareJSONRequestBody = SharingCreateShareRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SharingAccessShare Access a share's content by bearer token.
	// (GET /api/v1/sharing/access)
	SharingAccessShare(w http.ResponseWriter, r *http.Request, params SharingAccessShareParams)
	// SharingListShares List every share of the caller's tenant, newest first.
	// (GET /api/v1/sharing/shares)
	SharingListShares(w http.ResponseWriter, r *http.Request)
	// SharingCreateShare Create a new share link in the caller's tenant.
	// (POST /api/v1/sharing/shares)
	SharingCreateShare(w http.ResponseWriter, r *http.Request)
	// SharingGetShare Get one share's own metadata.
	// (GET /api/v1/sharing/shares/{shareId})
	SharingGetShare(w http.ResponseWriter, r *http.Request, shareID ShareID)
	// SharingListShareAccessLog List every recorded access attempt against a share, newest first.
	// (GET /api/v1/sharing/shares/{shareId}/access-log)
	SharingListShareAccessLog(w http.ResponseWriter, r *http.Request, shareID ShareID)
	// SharingRevokeShare Revoke a share, with immediate effect.
	// (POST /api/v1/sharing/shares/{shareId}/revoke)
	SharingRevokeShare(w http.ResponseWriter, r *http.Request, shareID ShareID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SharingAccessShare operation middleware
func (siw *ServerInterfaceWrapper) SharingAccessShare(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SharingAccessShareParams

	// ------------- Required query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Sharing-Password" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Sharing-Password")]; found {
		var XSharingPassword string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Sharing-Password", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Sharing-Password", valueList[0], &XSharingPassword, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Sharing-Password", Err: err})
			return
		}

		params.XSharingPassword = &XSharingPassword

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SharingAccessShare(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SharingListShares operation middleware
func (siw *ServerInterfaceWrapper) SharingListShares(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SharingListShares(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SharingCreateShare operation middleware
func (siw *ServerInterfaceWrapper) SharingCreateShare(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SharingCreateShare(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SharingGetShare operation middleware
func (siw *ServerInterfaceWrapper) SharingGetShare(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shareId" -------------
	var shareID ShareID

	err = runtime.BindStyledParameterWithOptions("simple", "shareId", r.PathValue("shareId"), &shareID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shareId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SharingGetShare(w, r, shareID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SharingListShareAccessLog operation middleware
func (siw *ServerInterfaceWrapper) SharingListShareAccessLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shareId" -------------
	var shareID ShareID

	err = runtime.BindStyledParameterWithOptions("simple", "shareId", r.PathValue("shareId"), &shareID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shareId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SharingListShareAccessLog(w, r, shareID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SharingRevokeShare operation middleware
func (siw *ServerInterfaceWrapper) SharingRevokeShare(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shareId" -------------
	var shareID ShareID

	err = runtime.BindStyledParameterWithOptions("simple", "shareId", r.PathValue("shareId"), &shareID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shareId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SharingRevokeShare(w, r, shareID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sharing/access", wrapper.SharingAccessShare)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sharing/shares", wrapper.SharingListShares)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/sharing/shares", wrapper.SharingCreateShare)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sharing/shares/{shareId}", wrapper.SharingGetShare)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/sharing/shares/{shareId}/revoke", wrapper.SharingRevokeShare)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sharing/shares/{shareId}/access-log", wrapper.SharingListShareAccessLog)

	return m
}
