package metering

import (
	"context"
	"math"
	"time"
)

// maxMetadataEntries and maxMetadataFieldLength bound UsageEvent.Metadata:
// small, bounded context, never a dumping ground for arbitrary payloads.
// Both are enforced by UsageEvent.validate.
const (
	maxMetadataEntries     = 20
	maxMetadataFieldLength = 256
)

// UsageEvent is one unit of measured usage, the single shape both
// reliability tiers (AnalyticsRecorder.Record and the billing-grade
// Enqueue) accept.
//
// TenantID is an explicit field rather than read off ctx by
// pkgcore.TenantFromContext, unlike the tenant-scoped HTTP API surfaces
// this codebase otherwise mandates (root CLAUDE.md: "do not accept a
// caller-supplied tenant_id at the API layer"). That rule targets an
// externally reachable API boundary where a caller-supplied tenant would
// let one tenant impersonate another; UsageEvent is an internal Go-level
// call a business module makes from code that already knows which
// tenant's usage it measured, and the analytics and billing-grade
// pipelines both need to carry that tenant across an asynchronous
// boundary (a background goroutine, a poller reading a persisted outbox
// row) where the original request ctx is long gone -- the same reason
// dbkit's WriteCapturedEvent and tenancy's SystemContextEnteredEvent
// embed TenantID as a plain field rather than leaving it for a subscriber
// to re-derive from ctx.
type UsageEvent struct {
	// TenantID is the tenant this usage belongs to.
	TenantID string
	// Feature is the quota/billing dimension this event measures, for
	// example "ai.generation" or "api.calls". It has no closed
	// enumeration in this round -- see AGENTS.md's Known limitations for
	// why there is no "unknown feature" validation yet.
	Feature string
	// Quantity is how much of Feature this event measures. Zero is legal;
	// negative, NaN and infinite are rejected.
	Quantity float64
	// IdempotencyKey is caller-derived and dedupes a retried Record or
	// Enqueue call for what is really the same unit of usage -- never
	// randomly generated by the caller, the same discipline
	// go/jobs demands of a job's idempotency key. The billing-grade
	// Enqueue path enforces this at the database level (a unique index on
	// (tenant_id, idempotency_key)); AnalyticsRecorder does not persist
	// seen keys at all, so a retried analytics-grade Record call is not
	// deduped -- see AnalyticsRecorder's doc comment.
	IdempotencyKey string
	// OccurredAt is when the usage actually happened. A zero value is
	// treated as "now" by Aggregator.Ingest.
	OccurredAt time.Time
	// Metadata is small, bounded context carried alongside the event (at
	// most maxMetadataEntries entries, each key and value at most
	// maxMetadataFieldLength bytes) -- never a dumping ground for
	// arbitrary payloads. It has no defined schema this round; a business
	// module wanting structured billing detail should encode what it
	// needs into Feature or wait for a future round's richer shape.
	Metadata map[string]string
}

// validate checks the fields every ingestion path (Record, Enqueue,
// Aggregator.Ingest itself) requires, returning one of this file's
// sentinel errors decorated with the offending value.
func (e UsageEvent) validate() error {
	if e.TenantID == "" {
		return ErrMissingTenantID
	}
	if e.Feature == "" {
		return ErrMissingFeature
	}
	if e.IdempotencyKey == "" {
		return ErrMissingIdempotencyKey
	}
	if math.IsNaN(e.Quantity) || math.IsInf(e.Quantity, 0) || e.Quantity < 0 {
		return ErrInvalidQuantity.WithParam("quantity", e.Quantity)
	}
	if len(e.Metadata) > maxMetadataEntries {
		return ErrMetadataTooLarge.
			WithParam("entry_count", len(e.Metadata)).
			WithParam("max_entries", maxMetadataEntries)
	}
	for k, v := range e.Metadata {
		if len(k) > maxMetadataFieldLength || len(v) > maxMetadataFieldLength {
			return ErrMetadataTooLarge.
				WithParam("max_field_length", maxMetadataFieldLength)
		}
	}
	return nil
}

// Recorder is the one interface business modules call to report usage.
// Business code depends on this interface only -- never on
// AnalyticsRecorder or the outbox helper directly -- matching this
// repository's seam philosophy for every other infrastructure dependency
// (pkgcore.EventBus, pkgcore.KVStore, and so on): a caller that only knows
// Recorder can be handed any implementation without changing a line.
//
// AnalyticsRecorder is this round's one Recorder implementation, wired for
// analytics-grade (fail-open) usage. The billing-grade tier is
// deliberately NOT behind this interface: Enqueue's signature
// (Enqueue(ctx, tx, event)) requires the caller's own transaction handle,
// which Recorder's Record(ctx, event) shape has no room for -- billing-grade
// callers use Enqueue directly, per its own doc comment.
type Recorder interface {
	// Record reports event. Whether this can fail without losing event is
	// entirely a property of the implementation -- see AnalyticsRecorder's
	// doc comment for what "fail-open" means concretely for the one
	// implementation this round ships.
	Record(ctx context.Context, event UsageEvent) error
}
