package metering

import (
	"context"
	"math"
	"time"
)

// maxMetadataEntries and maxMetadataFieldLength bound UsageEvent.Metadata:
// small, bounded context, never a dumping ground for arbitrary payloads.
// Both are enforced by UsageEvent.validate.
const (
	maxMetadataEntries     = 20
	maxMetadataFieldLength = 256
)

// maxTenantIDLength, maxFeatureLength and maxIdempotencyKeyLength bound
// the three fixed-width identifier fields of UsageEvent, mirroring the
// VARCHAR widths of the columns those fields land in on every table of
// this module, on both dialects: tenant_id is VARCHAR(64), feature is
// VARCHAR(128), and idempotency_key (the outbox column) / id (the
// IngestReceipt primary-key column, which holds the same value) are
// VARCHAR(200) -- see the postgres/ and sqlite/ migration files.
//
// The bounds are enforced by UsageEvent.validate as BYTE lengths, the
// conservative direction: a value within a byte bound is always within
// the column's character bound on PostgreSQL, where VARCHAR(n) counts
// characters, whatever the value's encoding. These bounds are not merely
// tidy: SQLite does not enforce a VARCHAR's declared length at all, so
// without them an over-long value writes happily on SQLite and is
// rejected by PostgreSQL with SQLSTATE 22001 -- inside the caller's own
// transaction when the write is Enqueue's, aborting it (see Enqueue's doc
// comment on the poisoned-transaction class).
const (
	maxTenantIDLength       = 64
	maxFeatureLength        = 128
	maxIdempotencyKeyLength = 200
)

// UsageEvent is one unit of measured usage, the single shape both
// reliability tiers (AnalyticsRecorder.Record and the billing-grade
// Enqueue) accept.
//
// TenantID is an explicit field rather than read off ctx by
// pkgcore.TenantFromContext, unlike the tenant-scoped HTTP API surfaces
// this codebase otherwise mandates (root CLAUDE.md: "do not accept a
// caller-supplied tenant_id at the API layer"). That rule targets an
// externally reachable API boundary where a caller-supplied tenant would
// let one tenant impersonate another; UsageEvent is an internal Go-level
// call a business module makes from code that already knows which
// tenant's usage it measured, and the analytics and billing-grade
// pipelines both need to carry that tenant across an asynchronous
// boundary (a background goroutine, a poller reading a persisted outbox
// row) where the original request ctx is long gone -- the same reason
// dbkit's WriteCapturedEvent and tenancy's SystemContextEnteredEvent
// embed TenantID as a plain field rather than leaving it for a subscriber
// to re-derive from ctx.
type UsageEvent struct {
	// TenantID is the tenant this usage belongs to, at most
	// maxTenantIDLength bytes.
	TenantID string
	// Feature is the quota/billing dimension this event measures, for
	// example "ai.generation" or "api.calls", at most maxFeatureLength
	// bytes. It has no closed enumeration in this round -- see AGENTS.md's
	// Known limitations for why there is no "unknown feature" validation
	// yet.
	//
	// Feature is also the aggregation key the two reliability tiers share,
	// which makes one feature belong to exactly one reliability tier: the
	// same Feature must never be recorded through both the fail-open
	// AnalyticsRecorder.Record and the billing-grade Enqueue path. Both
	// tiers fold into the SAME per-tenant, per-feature, per-period counter
	// entry and UsageSummary row, and neither carries a tier marker, so a
	// feature measured through both tiers is a blend no reader can
	// attribute -- billing-grade quantities silently seeded with data the
	// analytics tier may drop by design, and a retried analytics-grade
	// Record is not deduplicated either, so it can fold a second time into
	// the same row. A feature whose records must not be lost is recorded
	// through the billing-grade path alone, which already feeds the same
	// counters and summary rows the analytics tier feeds. This is caller
	// discipline, not something the pipeline enforces -- see AGENTS.md's
	// "Reliability tiers" section for the full statement.
	Feature string
	// Quantity is how much of Feature this event measures. Zero is legal;
	// negative, NaN and infinite are rejected.
	Quantity float64
	// IdempotencyKey is caller-derived and dedupes a retried Record or
	// Enqueue call for what is really the same unit of usage -- never
	// randomly generated by the caller, the same discipline
	// go/jobs demands of a job's idempotency key. It is at most
	// maxIdempotencyKeyLength bytes. The billing-grade Enqueue path
	// enforces this at the database level (a unique index on
	// (tenant_id, idempotency_key)); AnalyticsRecorder does not persist
	// seen keys at all, so a retried analytics-grade Record call is not
	// deduped -- see AnalyticsRecorder's doc comment.
	IdempotencyKey string
	// OccurredAt is when the usage actually happened. A zero value is
	// treated as "now" by Aggregator.Ingest.
	OccurredAt time.Time
	// Metadata is small, bounded context carried alongside the event (at
	// most maxMetadataEntries entries, each key and value at most
	// maxMetadataFieldLength bytes) -- never a dumping ground for
	// arbitrary payloads. It has no defined schema this round; a business
	// module wanting structured billing detail should encode what it
	// needs into Feature or wait for a future round's richer shape.
	Metadata map[string]string
}

// validate checks the fields every ingestion path (Record, Enqueue,
// Aggregator.Ingest itself) requires, returning one of this file's
// sentinel errors decorated with the offending value.
func (e UsageEvent) validate() error {
	if e.TenantID == "" {
		return ErrMissingTenantID
	}
	if len(e.TenantID) > maxTenantIDLength {
		return ErrFieldTooLong.
			WithParam("field", "tenant_id").
			WithParam("max_length", maxTenantIDLength)
	}
	if e.Feature == "" {
		return ErrMissingFeature
	}
	if len(e.Feature) > maxFeatureLength {
		return ErrFieldTooLong.
			WithParam("field", "feature").
			WithParam("max_length", maxFeatureLength)
	}
	if e.IdempotencyKey == "" {
		return ErrMissingIdempotencyKey
	}
	if len(e.IdempotencyKey) > maxIdempotencyKeyLength {
		return ErrFieldTooLong.
			WithParam("field", "idempotency_key").
			WithParam("max_length", maxIdempotencyKeyLength)
	}
	if math.IsNaN(e.Quantity) || math.IsInf(e.Quantity, 0) || e.Quantity < 0 {
		return ErrInvalidQuantity.WithParam("quantity", e.Quantity)
	}
	if len(e.Metadata) > maxMetadataEntries {
		return ErrMetadataTooLarge.
			WithParam("entry_count", len(e.Metadata)).
			WithParam("max_entries", maxMetadataEntries)
	}
	for k, v := range e.Metadata {
		if len(k) > maxMetadataFieldLength || len(v) > maxMetadataFieldLength {
			return ErrMetadataTooLarge.
				WithParam("max_field_length", maxMetadataFieldLength)
		}
	}
	return nil
}

// Recorder is the one interface business modules call to report usage.
// Business code depends on this interface only -- never on
// AnalyticsRecorder or the outbox helper directly -- matching this
// repository's seam philosophy for every other infrastructure dependency
// (pkgcore.EventBus, pkgcore.KVStore, and so on): a caller that only knows
// Recorder can be handed any implementation without changing a line.
//
// AnalyticsRecorder is this round's one Recorder implementation, wired for
// analytics-grade (fail-open) usage. The billing-grade tier is
// deliberately NOT behind this interface: Enqueue's signature
// (Enqueue(ctx, tx, event)) requires the caller's own transaction handle,
// which Recorder's Record(ctx, event) shape has no room for -- billing-grade
// callers use Enqueue directly, per its own doc comment.
type Recorder interface {
	// Record reports event. Whether this can fail without losing event is
	// entirely a property of the implementation -- see AnalyticsRecorder's
	// doc comment for what "fail-open" means concretely for the one
	// implementation this round ships.
	Record(ctx context.Context, event UsageEvent) error
}
