//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for BillingCreditTransactionStatus.
const (
	Confirmed BillingCreditTransactionStatus = "confirmed"
	Pending   BillingCreditTransactionStatus = "pending"
	Refunded  BillingCreditTransactionStatus = "refunded"
)

// Valid indicates whether the value is a known member of the BillingCreditTransactionStatus enum.
func (e BillingCreditTransactionStatus) Valid() bool {
	switch e {
	case Confirmed:
		return true
	case Pending:
		return true
	case Refunded:
		return true
	default:
		return false
	}
}

// Defines values for BillingCreditTransactionType.
const (
	Deduct BillingCreditTransactionType = "deduct"
	Expire BillingCreditTransactionType = "expire"
	Grant  BillingCreditTransactionType = "grant"
)

// Valid indicates whether the value is a known member of the BillingCreditTransactionType enum.
func (e BillingCreditTransactionType) Valid() bool {
	switch e {
	case Deduct:
		return true
	case Expire:
		return true
	case Grant:
		return true
	default:
		return false
	}
}

// BillingCreditBalance The caller's tenant credit balance. The two buckets never overlap: a credit is in exactly one of available or reserved. The number a credit view renders is available -- what the tenant can spend right now.
type BillingCreditBalance struct {
	// Available The freely spendable credit count.
	Available int64 `json:"available"`

	// Reserved The credit count set aside by reservations whose jobs have not reached a terminal status yet (each one a deduct row at status "pending" in the ledger).
	Reserved int64 `json:"reserved"`

	// UpdatedAt When the balance row was last touched by a ledger mutation.
	UpdatedAt time.Time `json:"updatedAt"`
}

// BillingCreditTransaction One append-only entry in the tenant's credit ledger. Amount is always positive; the entry's direction is implied by type and status together, never a signed value. A deduct row is inserted at status "pending" by the reservation half of the two-phase pattern, then moved in place to "confirmed" (permanent spend) or "refunded" (released back to available) -- the refund IS that status transition on the same row, never a second row.
type BillingCreditTransaction struct {
	// Amount The credit count this entry moves, always positive: a confirmed deduct permanently removed it, a refunded deduct removed nothing net, a grant added it, an expire removed it.
	Amount int64 `json:"amount"`

	// CreatedAt When the entry was written.
	CreatedAt time.Time `json:"createdAt"`

	// ID The ledger row's id: an application-generated UUID for a grant or expire row, or the caller's own idempotency key for a deduct row. Not globally unique across tenants.
	ID string `json:"id"`

	// Reason A short note recorded when the entry was written (for example "smilesim:<job id>" for a smile-simulation reservation, "demo:seed" for a boot-time demo grant). Free text on the ledger; the credit view may display it verbatim.
	Reason string `json:"reason"`

	// Status The entry's resolution state. Grant and expire rows are single-phase and always "confirmed". A deduct row is "pending" while its reservation is outstanding, "confirmed" after the reservation was settled as a permanent spend, "refunded" after it was released back to the balance.
	Status BillingCreditTransactionStatus `json:"status"`

	// Type The entry's kind: "grant" is a top-up (a plan's included credits, an admin top-up), "deduct" the two-phase reservation, "expire" a single-phase deduction. "refund" is deliberately not a row type -- a refund is a deduct row whose status became "refunded" (see status).
	Type BillingCreditTransactionType `json:"type"`
}

// BillingCreditTransactionStatus The entry's resolution state. Grant and expire rows are single-phase and always "confirmed". A deduct row is "pending" while its reservation is outstanding, "confirmed" after the reservation was settled as a permanent spend, "refunded" after it was released back to the balance.
type BillingCreditTransactionStatus string

// BillingCreditTransactionType The entry's kind: "grant" is a top-up (a plan's included credits, an admin top-up), "deduct" the two-phase reservation, "expire" a single-phase deduction. "refund" is deliberately not a row type -- a refund is a deduct row whose status became "refunded" (see status).
type BillingCreditTransactionType string

// BillingError The structured {code, params} error envelope every speed API returns instead of localized text (backend coding standard §6.2; docs/internal/11-cross-cutting.md) -- a client resolves code through its own i18n catalog, populated from this module's Locales() resources for the codes documented in AGENTS.md's error index.
type BillingError struct {
	// Code Example: billing.invalid_limit
	Code   string                  `json:"code"`
	Params *map[string]interface{} `json:"params,omitempty"`
}

// BillingListCreditTransactionsResponse One page of the tenant's recent credit transactions.
type BillingListCreditTransactionsResponse struct {
	// Transactions At most limit rows, newest first; empty when the tenant has no ledger rows yet.
	Transactions []BillingCreditTransaction `json:"transactions"`
}

// BillingListCreditTransactionsParams defines parameters for BillingListCreditTransactions.
type BillingListCreditTransactionsParams struct {
	// Limit The page size, from 1 through 100. Defaults to 50.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// BillingGetCreditBalance Read the caller's tenant credit balance.
	// (GET /api/v1/billing/credits/balance)
	BillingGetCreditBalance(w http.ResponseWriter, r *http.Request)
	// BillingListCreditTransactions List the caller's tenant's recent credit transactions, newest first.
	// (GET /api/v1/billing/credits/transactions)
	BillingListCreditTransactions(w http.ResponseWriter, r *http.Request, params BillingListCreditTransactionsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// BillingGetCreditBalance operation middleware
func (siw *ServerInterfaceWrapper) BillingGetCreditBalance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BillingGetCreditBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BillingListCreditTransactions operation middleware
func (siw *ServerInterfaceWrapper) BillingListCreditTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BillingListCreditTransactionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BillingListCreditTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/billing/credits/balance", wrapper.BillingGetCreditBalance)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/billing/credits/transactions", wrapper.BillingListCreditTransactions)

	return m
}
