package flowtests

// smilesim_flow_test.go drives go/ai-gateway's image-generation
// pipeline end to end through the composed HTTP stack -- the
// authn+tenancy middleware chain, a real temp-file SQLite database
// (carrying storage's, ai-gateway's and every other module's real
// migrations), a real jobs.StandaloneQueue, and the smile-simulation
// surface (internal/app/smilesim.go, the app-side implementation of the
// generated interface its internal/smilesim/api fragment declares, whose
// mount patterns the generated HandlerFromMux derives from the fragment
// itself) -- against a fake
// OpenAI-compatible images endpoint (fakeOpenAIImageServer below),
// standing in for the real vendor: no live API key is available or
// needed, since the OpenAI-compatible images-edits multipart/form-data
// schema is fully testable this way.
//
// The one leg covers the surface's acceptance shape: a patient photo,
// uploaded through storage's own real HTTP surface, produces one async
// smile-simulation job whose completion is observed by polling
// smilesim's own job-status route -- proving the whole chain: the job
// handler read the uploaded photo's real bytes back out of storage, sent
// them to the fake vendor as a genuine multipart/form-data request (image
// file, model and prompt fields all present and correct), and wrote the
// vendor's generated bytes back into storage as a brand new object,
// distinct from the input, that this app's own storage HTTP surface can
// read back.
//
// Two further legs live at the bottom of this file: TestSmileSimulation_ParameterizedOptions_ReachTheVendorAndTheResultIndex
// drives an options-carrying simulate body end to end (the rendered
// option clauses reach the fake vendor's prompt, the job-status response
// echoes the recorded options, a same-photo same-options regenerate is a
// distinct generation, and the per-photo enumeration route lists every
// generation with its options, status and output object), and
// TestSmileSimulation_InvalidOptions_RefusedWithCodedErrors proves an
// out-of-vocabulary or out-of-range option set is refused with its coded
// 400 before the vendor is ever reached.
//
// Known, non-flaky WARN log this test deterministically surfaces: the
// uploaded photo's own storage.object.derive.thumbnail job (enqueued by
// its Complete) and the ai-gateway.image.generate job for the
// SAME request run concurrently on BuildServer's one shared
// jobs.StandaloneQueue (WorkerCount 4 by default) against the app's one
// file-backed SQLite database. The root cause is precise: the
// derive job's gate (go/storage/repository.go's insertDerivativeIfAbsent)
// is a read-then-write transaction, and SQLite answers such a
// transaction's write -- upgrading the SHARED lock its earlier gate
// SELECT holds -- with an immediate SQLITE_BUSY whenever another
// connection holds the write lock, refusing the upgrade without
// consulting the busy handler, so no busy_timeout setting changes the
// outcome (the ~13 ms duration_ms on the WARN is that immediacy; the
// boundary is spelled out in go/dbkit's own "SQLite busy timeout"
// documentation). It is neither the AuditBus same-goroutine self-deadlock
// nor ordinary
// busy-timeout contention. go/jobs' own retry/backoff is the existing,
// working convergence mechanism: the losing attempt logs "job attempt
// failed, scheduling retry" with error "storage.internal_error: database
// is locked (5) (SQLITE_BUSY)" and succeeds on its very next attempt,
// which is why this test's own assertions (including on Attempts via the
// job's final state) still pass deterministically. A busy_timeout pragma
// does not cure it: the immediate-`SQLITE_BUSY` failure is a
// deterministic property of the gate's transaction shape, pinned in
// isolation by go/dbkit/dialect/sqlite/busy_timeout_test.go's
// read-then-write-upgrade test. Whether a given run actually hits the
// collision is scheduling-dependent, and a WARN-free run does not mean
// the failure mode is gone. The WARN stays by design: removing it would
// be go/storage work on the gate's transaction shape (taking the write
// lock first, e.g. BEGIN IMMEDIATE) or a queue-concurrency change in
// this app's own wiring (internal/app/server.go's shared StandaloneQueue)
// -- a boundary recorded here rather than worked around inside these
// tests.

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"io"
	"mime"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/vislake/speed/examples/reference-app/internal/app"
	"github.com/vislake/speed/examples/reference-app/internal/app/demo"
)

// fakeOpenAIImageServer answers every POST /images/edits with a fixed,
// generated PNG image as a base64 "data" entry plus a fixed usage block --
// the wire shape go/ai-gateway's OpenAICompatibleImageProvider parses
// (go/ai-gateway/openai_compatible_image.go's openaiImageResponseWire). It
// records the last request's decoded multipart form, so a test can assert
// on exactly what this app's wiring sent -- including the uploaded image
// file's own bytes.
type fakeOpenAIImageServer struct {
	*httptest.Server

	generatedPNG []byte

	// requests counts every request this server's handler was actually
	// invoked for (matching /images/edits or not) -- billing_credit_flow_
	// test.go's insufficient-balance scenario asserts this stays at zero to
	// prove go/ai-gateway, and therefore any real vendor, was never reached
	// once a credit reservation is refused.
	requests int

	lastModel    string
	lastPrompt   string
	lastImageRaw []byte

	// lastAuthorization is the request's Authorization header, recorded for
	// ai_gateway_flow_test.go's tenant-BYOK redirect proof -- which
	// credential's key the image provider presented is visible only here.
	lastAuthorization string
}

func newFakeOpenAIImageServer(t *testing.T) *fakeOpenAIImageServer {
	t.Helper()

	// A tiny, deterministic PNG stands in for the vendor's "simulated
	// smile" output -- distinct pixel content from the uploaded photo, so
	// a test can tell the two apart by more than just object id.
	img := image.NewRGBA(image.Rect(0, 0, 4, 4))
	for y := 0; y < 4; y++ {
		for x := 0; x < 4; x++ {
			img.SetRGBA(x, y, color.RGBA{R: 200, G: 200, B: 200, A: 255})
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatalf("encode fake generated png: %v", err)
	}

	f := &fakeOpenAIImageServer{generatedPNG: buf.Bytes()}
	f.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		f.requests++
		// Recorded for ai_gateway_flow_test.go's tenant-BYOK redirect
		// proof: which credential's key the image provider presented is
		// visible only in this header.
		f.lastAuthorization = r.Header.Get("Authorization")
		if r.Method != http.MethodPost || r.URL.Path != "/images/edits" {
			http.NotFound(w, r)
			return
		}
		_, params, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
		if err != nil {
			http.Error(w, "malformed content-type", http.StatusBadRequest)
			return
		}
		mr := multipart.NewReader(r.Body, params["boundary"])
		form, err := mr.ReadForm(10 << 20)
		if err != nil {
			http.Error(w, "malformed multipart body", http.StatusBadRequest)
			return
		}
		defer func() { _ = form.RemoveAll() }()

		if vals := form.Value["model"]; len(vals) > 0 {
			f.lastModel = vals[0]
		}
		if vals := form.Value["prompt"]; len(vals) > 0 {
			f.lastPrompt = vals[0]
		}
		if files := form.File["image"]; len(files) > 0 {
			fh, openErr := files[0].Open()
			if openErr != nil {
				http.Error(w, "cannot open image part", http.StatusBadRequest)
				return
			}
			raw, readErr := io.ReadAll(fh)
			_ = fh.Close()
			if readErr != nil {
				http.Error(w, "cannot read image part", http.StatusBadRequest)
				return
			}
			f.lastImageRaw = raw
		}
		// This app's smile-simulation route only ever drives ImageToImage
		// (no mask), so an "image_edits" request here must never carry a
		// mask part -- proving the mask field is genuinely conditional.
		if masks := form.File["mask"]; len(masks) > 0 {
			http.Error(w, "unexpected mask part for an image-to-image request", http.StatusBadRequest)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data": []map[string]string{
				{"b64_json": base64.StdEncoding.EncodeToString(f.generatedPNG)},
			},
			"usage": map[string]any{
				"image_count": 1,
				"steps":       30,
				"size":        "1024x1024",
			},
		})
	}))
	t.Cleanup(f.Close)
	return f
}

// buildSmileSimTestServer wires up BuildServer's real output behind an
// httptest.Server, with the ai-gateway image platform credential pointed
// at imgServer -- the same test-only-override pattern
// buildConsultTestServer already establishes for the chat credential.
func buildSmileSimTestServer(t *testing.T, imgServer *fakeOpenAIImageServer) (*httptest.Server, app.ServerConfig) {
	t.Helper()

	cfg := testConfig(t)
	cfg.AIGatewayImageBaseURL = imgServer.URL
	cfg.AIGatewayImageAPIKey = "sk-test-smilesim-key"

	handler, cleanup, _, err := app.BuildServer(t.Context(), cfg)
	if err != nil {
		t.Fatalf("BuildServer: %v", err)
	}
	t.Cleanup(func() {
		if err := cleanup(); err != nil {
			t.Errorf("cleanup: %v", err)
		}
	})

	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	return srv, cfg
}

// smileSimRequest issues method against path on srv, authenticated as
// token -- neither smile-simulation route checks a demo-user-keyed
// permission of its own, so no X-Demo-User header is needed, mirroring
// consultSuggestRequest's identical shape for the chat route.
func smileSimRequest(t *testing.T, srv *httptest.Server, method, path, token string, body []byte) *http.Response {
	t.Helper()

	var reader *bytes.Reader
	if body != nil {
		reader = bytes.NewReader(body)
	} else {
		reader = bytes.NewReader(nil)
	}
	req, err := http.NewRequest(method, srv.URL+path, reader)
	if err != nil {
		t.Fatalf("build request: %v", err)
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := srv.Client().Do(req)
	if err != nil {
		t.Fatalf("%s %s: %v", method, path, err)
	}
	return resp
}

// waitForSmileSimSucceeded polls the job-status route until it reports
// "succeeded" or deadline passes, decoding and returning the final
// response body either way -- the HTTP-level counterpart of go/jobs' own
// example_test.go's waitForTerminal, since this test observes the job
// only through smilesim's own route, never jobs.Queue directly.
func waitForSmileSimSucceeded(t *testing.T, srv *httptest.Server, token, jobID string, deadline time.Time) map[string]any {
	t.Helper()

	for {
		resp := smileSimRequest(t, srv, http.MethodGet, smileJobPathPrefix+jobID, token, nil)
		var out map[string]any
		if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
			resp.Body.Close()
			t.Fatalf("decode job status: %v", err)
		}
		resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			t.Fatalf("GET %s status = %d, want %d; body = %+v", smileJobPathPrefix+jobID, resp.StatusCode, http.StatusOK, out)
		}
		status, _ := out["status"].(string)
		if status == "succeeded" || status == "dead_letter" || status == "cancelled" {
			return out
		}
		if time.Now().After(deadline) {
			t.Fatalf("job %s did not reach a terminal status before the deadline; last status = %q, body = %+v", jobID, status, out)
		}
		time.Sleep(10 * time.Millisecond)
	}
}

// smileSimulateAndWait enqueues one /simulate job for the completed photo
// and polls the job-status route until it reaches a terminal status,
// requiring the enqueue itself to succeed (202 carrying a job_id). It is
// the shared orchestration TestSmileSimulation_ImageToImage_EndToEnd
// performed inline before this helper existed, and
// ai_gateway_flow_test.go's credential-redirect leg needs again -- it does
// NOT require the terminal status to be "succeeded", since a caller
// driving an unhappy path may legitimately land on dead_letter and wants
// to assert that itself.
func smileSimulateAndWait(t *testing.T, srv *httptest.Server, token string, photo testStorageObject, deadline time.Time) map[string]any {
	t.Helper()

	simulateBody, err := json.Marshal(map[string]string{"photo_object_id": photo.ID})
	if err != nil {
		t.Fatalf("marshal simulate request: %v", err)
	}
	return smileSimulateBodyAndWait(t, srv, token, simulateBody, deadline)
}

// smileSimulateBodyAndWait is smileSimulateAndWait's own implementation,
// parametrized on an arbitrary already-marshaled request body -- the
// parameterized-options tests need it to enqueue simulations whose
// body carries an "options" object (smile_style/tooth_shade/strength), which
// the plain photo-only helper cannot express.
func smileSimulateBodyAndWait(t *testing.T, srv *httptest.Server, token string, simulateBody []byte, deadline time.Time) map[string]any {
	t.Helper()

	resp := smileSimRequest(t, srv, http.MethodPost, smileSimulatePath, token, simulateBody)
	var simulateOut struct {
		JobID string `json:"job_id"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&simulateOut); err != nil {
		resp.Body.Close()
		t.Fatalf("decode simulate response: %v", err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusAccepted {
		t.Fatalf("POST %s status = %d, want %d; body = %+v", smileSimulatePath, resp.StatusCode, http.StatusAccepted, simulateOut)
	}
	if simulateOut.JobID == "" {
		t.Fatal("simulate response carries no job_id")
	}
	return waitForSmileSimSucceeded(t, srv, token, simulateOut.JobID, deadline)
}

// enumerateSimulations GETs the per-photo enumeration route for photoID and
// returns the decoded "simulations" array -- the smile gallery's data
// source, asserted on by the parameterized-options flow tests.
func enumerateSimulations(t *testing.T, srv *httptest.Server, token, photoID string) []map[string]any {
	t.Helper()

	path := "/api/v1/smile-simulation/photos/" + photoID + "/simulations"
	resp := smileSimRequest(t, srv, http.MethodGet, path, token, nil)
	var out struct {
		Simulations []map[string]any `json:"simulations"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		resp.Body.Close()
		t.Fatalf("decode enumeration response: %v", err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("GET %s status = %d, want %d; body = %+v", path, resp.StatusCode, http.StatusOK, out)
	}
	return out.Simulations
}

// assertOptionsIn asserts that map m's "options" object carries exactly the
// given effective option set -- the shape both the job-status route's
// options echo and the enumeration route's per-entry options field share.
func assertOptionsIn(t *testing.T, m map[string]any, wantStyle, wantShade string, wantStrength float64) {
	t.Helper()

	options, ok := m["options"].(map[string]any)
	if !ok {
		t.Fatalf("response carries no options object: %+v", m)
	}
	if style, _ := options["smile_style"].(string); style != wantStyle {
		t.Errorf("options.smile_style = %q, want %q (options: %+v)", style, wantStyle, options)
	}
	if shade, _ := options["tooth_shade"].(string); shade != wantShade {
		t.Errorf("options.tooth_shade = %q, want %q (options: %+v)", shade, wantShade, options)
	}
	if strength, _ := options["strength"].(float64); strength != wantStrength {
		t.Errorf("options.strength = %v, want %v (options: %+v)", strength, wantStrength, options)
	}
}

// TestSmileSimulation_ImageToImage_EndToEnd is the mandatory
// end-to-end proof: a patient photo really travels through
// internal/smilesim.Service, through go/ai-gateway's Gateway.GenerateImage
// async pipeline (credential resolution, model routing, the enqueued
// jobs.Task, the job handler's storage read, the
// OpenAICompatibleImageProvider's real multipart HTTP call, and the
// job handler's storage write), to a fake OpenAI-compatible images
// endpoint and back, landing as a brand new go/storage object this app's
// own storage HTTP surface can read.
func TestSmileSimulation_ImageToImage_EndToEnd(t *testing.T) {
	imgServer := newFakeOpenAIImageServer(t)
	srv, cfg := buildSmileSimTestServer(t, imgServer)

	token := registerAndAuthenticate(t, srv, cfg, "tenant-acme", "smilesim-owner")

	// Upload and complete a patient photo through storage's own real HTTP
	// surface -- the same helper storage_flow_test.go's own suite uses.
	photo := jpegWithExif(t)
	completedPhoto := uploadAndComplete(t, srv, token, photo, "")
	if completedPhoto.State != "completed" {
		t.Fatalf("photo state = %q, want completed", completedPhoto.State)
	}

	// storage's own completion pipeline strips the photo's EXIF metadata
	// (go/storage's structural sanitizer), so the bytes actually stored --
	// and therefore the bytes the job handler must read back and forward
	// to the vendor -- are shorter than what was uploaded. Read the
	// STORED content back through storage's own HTTP surface so this
	// test's later byte-for-byte comparison is against the real ground
	// truth, not the pre-sanitized upload.
	contentResp := storageRequest(t, srv, http.MethodGet,
		"/api/v1/storage/objects/"+completedPhoto.ID+"/content", token, demo.DemoOwnerUserID, "", nil)
	storedPhoto, err := io.ReadAll(contentResp.Body)
	contentResp.Body.Close()
	if err != nil {
		t.Fatalf("read stored photo content: %v", err)
	}
	if contentResp.StatusCode != http.StatusOK {
		t.Fatalf("GET stored photo content status = %d, want %d", contentResp.StatusCode, http.StatusOK)
	}

	// Enqueue the simulation and poll until the async job completes.
	final := smileSimulateAndWait(t, srv, token, completedPhoto, time.Now().Add(5*time.Second))
	if status, _ := final["status"].(string); status != "succeeded" {
		t.Fatalf("final job status = %v, want \"succeeded\"; body = %+v", final["status"], final)
	}
	outputObjectID, _ := final["output_object_id"].(string)
	if outputObjectID == "" {
		t.Fatalf("succeeded job carries no output_object_id: %+v", final)
	}
	if outputObjectID == completedPhoto.ID {
		t.Fatalf("output object id %q must never equal the input photo's own id -- the job handler must write a NEW object", outputObjectID)
	}
	usage, _ := final["usage"].(map[string]any)
	if usage == nil {
		t.Fatalf("succeeded job carries no usage: %+v", final)
	}
	if imageCount, _ := usage["image_count"].(float64); imageCount != 1 {
		t.Fatalf("usage.image_count = %v, want 1", usage["image_count"])
	}
	if steps, _ := usage["steps"].(float64); steps != 30 {
		t.Fatalf("usage.steps = %v, want 30 -- the fake server's own scripted usage dimension", usage["steps"])
	}
	if tier, _ := usage["resolution_tier"].(string); tier != "1024x1024" {
		t.Fatalf("usage.resolution_tier = %q, want %q", tier, "1024x1024")
	}

	// The fake server's own recorded request proves this app's wiring
	// (aigateway.WithModelRoute(smilesim.LogicalModel, ...) in internal/app/server.go)
	// actually ran end to end, rather than the test somehow
	// short-circuiting the gateway: the vendor model id is the routed
	// "dall-e-3", never the logical "image:smile-simulation" key business
	// code asked for, and the uploaded photo's own bytes traveled all the
	// way to the fake vendor as the multipart "image" part.
	if imgServer.lastModel != "dall-e-3" {
		t.Fatalf("fake server saw model = %q, want the routed vendor model %q, never the logical key", imgServer.lastModel, "dall-e-3")
	}
	if imgServer.lastPrompt == "" {
		t.Fatal("fake server saw an empty prompt")
	}
	if !bytes.Equal(imgServer.lastImageRaw, storedPhoto) {
		t.Fatalf("fake server's received image part (%d bytes) does not match the photo's stored bytes (%d bytes) -- the job handler must read the SAME bytes back from storage", len(imgServer.lastImageRaw), len(storedPhoto))
	}

	// The generated image is readable back through storage's own HTTP
	// surface, as a genuinely separate, completed object.
	getResp := storageRequest(t, srv, http.MethodGet, "/api/v1/storage/objects/"+outputObjectID, token, demo.DemoOwnerUserID, "", nil)
	outputObject := decodeStorageObject(t, getResp, http.StatusOK, "GET the generated simulation object")
	if outputObject.State != "completed" {
		t.Fatalf("generated object state = %q, want completed", outputObject.State)
	}
	if outputObject.MimeType != "image/png" {
		t.Fatalf("generated object mime = %q, want image/png", outputObject.MimeType)
	}
}

// TestSmileSimulation_CompletionNotifiesTheNamedRecipient proves the
// named-recipient addition end to end: a POST /simulate naming a
// recipient_user_id gets that recipient an SMS once the job succeeds --
// internal/smilesim's Service publishes EventSimulationCompleted (driven
// by the queue's terminal signal, with this test's own poll of the
// job-status route -- exactly like the earlier image-to-image test above
// -- riding along as the second leg),
// internal/app/demo/demo_notification.go's
// subscription turns that into a notification.Dispatch of
// demo.TypeKeySimulationReady, and the delivery job renders and sends it
// over the sms-only channel that type declares.
func TestSmileSimulation_CompletionNotifiesTheNamedRecipient(t *testing.T) {
	imgServer := newFakeOpenAIImageServer(t)

	// Built directly, rather than through buildSmileSimTestServer, so
	// cfg.SMSOutput can be set to a capturing buffer before the one
	// BuildServer call -- the console SMS sender this app wires reads
	// cfg.SMSOutput exactly once, at construction time.
	cfg := testConfig(t)
	cfg.AIGatewayImageBaseURL = imgServer.URL
	cfg.AIGatewayImageAPIKey = "sk-test-smilesim-notify-key"
	sms := &lockedBuffer{}
	cfg.SMSOutput = sms
	// The named recipient is a legitimate in-tenant recipient only when it
	// is an active member of the caller's tenant -- the simulate surface's
	// own gate (internal/app/smilesim.go's validateSimulateRecipient). The
	// fixture is granted membership in tenant-acme, the tenant this test's
	// caller signs into: the demo shape of a patient account in the same
	// clinic, without which the request would (correctly) be refused.
	cfg.Memberships.Grant(demo.DemoSmileSimRecipientUserID, "tenant-acme")

	handler, cleanup, _, err := app.BuildServer(t.Context(), cfg)
	if err != nil {
		t.Fatalf("BuildServer: %v", err)
	}
	t.Cleanup(func() {
		if cleanupErr := cleanup(); cleanupErr != nil {
			t.Errorf("cleanup: %v", cleanupErr)
		}
	})
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)

	token := registerAndAuthenticate(t, srv, cfg, "tenant-acme", "smilesim-notify-owner")

	photo := jpegWithExif(t)
	completedPhoto := uploadAndComplete(t, srv, token, photo, "")
	if completedPhoto.State != "completed" {
		t.Fatalf("photo state = %q, want completed", completedPhoto.State)
	}

	simulateBody, err := json.Marshal(map[string]string{
		"photo_object_id":   completedPhoto.ID,
		"recipient_user_id": demo.DemoSmileSimRecipientUserID,
	})
	if err != nil {
		t.Fatalf("marshal simulate request: %v", err)
	}
	resp := smileSimRequest(t, srv, http.MethodPost, smileSimulatePath, token, simulateBody)
	var simulateOut struct {
		JobID string `json:"job_id"`
	}
	if decodeErr := json.NewDecoder(resp.Body).Decode(&simulateOut); decodeErr != nil {
		resp.Body.Close()
		t.Fatalf("decode simulate response: %v", decodeErr)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusAccepted {
		t.Fatalf("POST %s status = %d, want %d", smileSimulatePath, resp.StatusCode, http.StatusAccepted)
	}

	final := waitForSmileSimSucceeded(t, srv, token, simulateOut.JobID, time.Now().Add(5*time.Second))
	if status, _ := final["status"].(string); status != "succeeded" {
		t.Fatalf("final job status = %v, want \"succeeded\"", final["status"])
	}

	// The delivery job runs asynchronously off the same StandaloneQueue --
	// the completion event is out by the time this point is reached (the
	// terminal signal drives it, and waitForSmileSimSucceeded's own
	// polling rides along as the second leg), but the notification.deliver
	// job it triggers still needs its own worker turn.
	eventually(t, 4*time.Second, "the simulation-ready SMS", func() bool {
		return len(smsLinesTo(sms, "+8613800138099")) == 1
	})
	// The demo module's copy renders in zh-CN (the fixed locale
	// internal/app/demo/demo_notification.go's subscription dispatches with -- demo users
	// carry no profile to negotiate a locale from, the same reasoning the
	// note-created subscription's own doc comment gives), so this
	// assertion checks only the line's structure -- never the rendered
	// text itself, mirroring notification_flow_test.go's own mailsTo-based
	// assertions, which check no literal message content either.
	lines := smsLinesTo(sms, "+8613800138099")
	if strings.TrimSpace(lines[0]) == "SMS to +8613800138099:" {
		t.Errorf("SMS line = %q, want non-empty rendered copy after the address", lines[0])
	}

	// A repeated poll of the same job (waitForSmileSimSucceeded already
	// issued several once it was terminal) must never send a second SMS --
	// NotifyOnCompletion's own once-only guarantee, proven here through the
	// real HTTP polling path rather than only at the unit level
	// (internal/smilesim's own service_test.go).
	if got := smsLinesTo(sms, "+8613800138099"); len(got) != 1 {
		t.Errorf("recorded %d SMS lines to the recipient, want exactly 1 (repeated polling must not double-send)", len(got))
	}
}

// TestSmileSimulation_TwoCompletionsForOneRecipient_BothDeliver pins the
// two-occurrence case: TWO simulations completed for the SAME
// recipient are two distinct occurrences, and each must deliver on its
// own. Before the fix, internal/app/demo/demo_notification.go's simulation-completed
// subscription dispatched with empty Params, so both dispatches derived
// the identical delivery key (same tenant, same type, same recipient,
// same channel, same params) and the notification module settled the
// second delivery job as a duplicate of the first -- one SMS for two
// completed simulations, silently dropped while each simulate route had
// answered 202. The dispatch must carry the completing job's own id in
// its Params -- the mirror of the note-created dispatch carrying
// note_id -- so the two occurrences derive distinct keys and both
// deliver.
//
// The legs are sequenced so the failure is deterministic: simulation
// one's delivery must be fully settled (its send record written) before
// simulation two's event dispatches, which is why the test waits for the
// first SMS before starting the second simulation -- otherwise the two
// delivery jobs could race and the duplicate-settling order would decide
// whether the bug showed.
func TestSmileSimulation_TwoCompletionsForOneRecipient_BothDeliver(t *testing.T) {
	imgServer := newFakeOpenAIImageServer(t)

	cfg := testConfig(t)
	cfg.AIGatewayImageBaseURL = imgServer.URL
	cfg.AIGatewayImageAPIKey = "sk-test-smilesim-notify-twice-key"
	sms := &lockedBuffer{}
	cfg.SMSOutput = sms
	cfg.Memberships.Grant(demo.DemoSmileSimRecipientUserID, "tenant-acme")

	handler, cleanup, _, err := app.BuildServer(t.Context(), cfg)
	if err != nil {
		t.Fatalf("BuildServer: %v", err)
	}
	t.Cleanup(func() {
		if cleanupErr := cleanup(); cleanupErr != nil {
			t.Errorf("cleanup: %v", cleanupErr)
		}
	})
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)

	token := registerAndAuthenticate(t, srv, cfg, "tenant-acme", "smilesim-notify-twice-owner")

	photo := jpegWithExif(t)
	completedPhoto := uploadAndComplete(t, srv, token, photo, "")
	if completedPhoto.State != "completed" {
		t.Fatalf("photo state = %q, want completed", completedPhoto.State)
	}

	simulateForRecipient := func() string {
		t.Helper()
		simulateBody, err := json.Marshal(map[string]string{
			"photo_object_id":   completedPhoto.ID,
			"recipient_user_id": demo.DemoSmileSimRecipientUserID,
		})
		if err != nil {
			t.Fatalf("marshal simulate request: %v", err)
		}
		resp := smileSimRequest(t, srv, http.MethodPost, smileSimulatePath, token, simulateBody)
		var simulateOut struct {
			JobID string `json:"job_id"`
		}
		if decodeErr := json.NewDecoder(resp.Body).Decode(&simulateOut); decodeErr != nil {
			resp.Body.Close()
			t.Fatalf("decode simulate response: %v", decodeErr)
		}
		resp.Body.Close()
		if resp.StatusCode != http.StatusAccepted {
			t.Fatalf("POST %s status = %d, want %d", smileSimulatePath, resp.StatusCode, http.StatusAccepted)
		}
		return simulateOut.JobID
	}

	// Simulation one: complete it and wait until its SMS has genuinely
	// been delivered and settled -- the first send record is what the
	// second delivery job's duplicate probe would find.
	job1 := simulateForRecipient()
	final1 := waitForSmileSimSucceeded(t, srv, token, job1, time.Now().Add(5*time.Second))
	if status, _ := final1["status"].(string); status != "succeeded" {
		t.Fatalf("first job status = %v, want \"succeeded\"", final1["status"])
	}
	eventually(t, 4*time.Second, "the first simulation-ready SMS", func() bool {
		return len(smsLinesTo(sms, "+8613800138099")) == 1
	})

	// Simulation two for the same recipient: a regenerate of the same
	// photo is an explicit NEW generation with its own job id, exactly the
	// "second occurrence" the bug collapsed into the first delivery.
	job2 := simulateForRecipient()
	if job2 == job1 {
		t.Fatalf("second simulate returned the same job id %q as the first -- each generation must be its own job", job1)
	}
	final2 := waitForSmileSimSucceeded(t, srv, token, job2, time.Now().Add(5*time.Second))
	if status, _ := final2["status"].(string); status != "succeeded" {
		t.Fatalf("second job status = %v, want \"succeeded\"", final2["status"])
	}

	// Both occurrences must deliver: without the fix the second delivery was
	// settled as a duplicate of the first and this wait timed out with the
	// recipient stuck at one SMS.
	eventually(t, 4*time.Second, "the second simulation-ready SMS", func() bool {
		return len(smsLinesTo(sms, "+8613800138099")) == 2
	})
	lines := smsLinesTo(sms, "+8613800138099")
	if len(lines) != 2 {
		t.Fatalf("recorded %d SMS lines to the recipient, want exactly 2 -- each completed simulation must deliver as its own occurrence", len(lines))
	}
	if lines[0] == lines[1] {
		t.Errorf("the two SMS lines are identical: %q -- each delivery's copy must name its own simulation", lines[0])
	}
}

// TestSmileSimulation_ParameterizedOptions_ReachTheVendorAndTheResultIndex
// is the parameterization end-to-end proof, in three legs over the real
// composed HTTP stack:
//
//  1. an options-carrying /simulate body (bright style, ultra-white shade,
//     strength 0.4) produces a job whose vendor prompt -- as recorded by
//     the fake image server -- renders exactly that option set's clauses,
//     ends with the verbatim preservation sentence, and names the exact
//     strength value, and whose job-status response echoes the recorded
//     options;
//  2. repeating the SAME photo and SAME options is a NEW generation (a
//     distinct job id) -- the regenerate decision, pinned at the HTTP
//     layer;
//  3. the per-photo enumeration route lists all three generations of this
//     photo -- the one made twice with the same options and a third with
//     different ones -- each carrying the options that produced it, its
//     status and its output object: the smile gallery's data source.
func TestSmileSimulation_ParameterizedOptions_ReachTheVendorAndTheResultIndex(t *testing.T) {
	imgServer := newFakeOpenAIImageServer(t)
	srv, cfg := buildSmileSimTestServer(t, imgServer)

	token := registerAndAuthenticate(t, srv, cfg, "tenant-acme", "smilesim-params-owner")

	photo := jpegWithExif(t)
	completedPhoto := uploadAndComplete(t, srv, token, photo, "")
	if completedPhoto.State != "completed" {
		t.Fatalf("photo state = %q, want completed", completedPhoto.State)
	}

	deadline := time.Now().Add(5 * time.Second)
	simulateBody := func(options map[string]any) []byte {
		t.Helper()
		body := map[string]any{"photo_object_id": completedPhoto.ID}
		if options != nil {
			body["options"] = options
		}
		raw, err := json.Marshal(body)
		if err != nil {
			t.Fatalf("marshal simulate body: %v", err)
		}
		return raw
	}

	// Leg 1: a fully-specified option set reaches the vendor's prompt and
	// comes back on the job-status response.
	brightOpts := map[string]any{"smile_style": "bright", "tooth_shade": "ultra-white", "strength": 0.4}
	final := smileSimulateBodyAndWait(t, srv, token, simulateBody(brightOpts), deadline)
	if status, _ := final["status"].(string); status != "succeeded" {
		t.Fatalf("final job status = %v, want \"succeeded\"", final["status"])
	}
	prompt := imgServer.lastPrompt
	for _, want := range []string{
		"Shape the mouth into a bright, open smile with clearly visible, evenly aligned teeth.",
		"Give the teeth a bright ultra-white shade.",
		"Apply the smile transformation at a strength of 0.4, where 1.0 means the complete simulated smile",
		"Preserve the patient's facial identity, proportions, skin tone, lip color and pose.",
	} {
		if !strings.Contains(prompt, want) {
			t.Errorf("vendor prompt missing %q:\n%s", want, prompt)
		}
	}
	if !strings.HasSuffix(prompt, "Keep the rest of the face, lighting and background unchanged.") {
		t.Errorf("vendor prompt does not end with the verbatim preservation sentence:\n%s", prompt)
	}
	assertOptionsIn(t, final, "bright", "ultra-white", 0.4)

	// Leg 2: the regenerate decision at the HTTP layer -- the same photo,
	// the same options, a distinct job id, and the same option clauses in
	// the vendor prompt (a second real vendor call, not a cached reply).
	promptBeforeRegenerate := imgServer.lastPrompt
	final2 := smileSimulateBodyAndWait(t, srv, token, simulateBody(brightOpts), deadline)
	if status, _ := final2["status"].(string); status != "succeeded" {
		t.Fatalf("second (regenerate) job status = %v, want \"succeeded\"", final2["status"])
	}
	if imgServer.lastPrompt != promptBeforeRegenerate {
		t.Errorf("regenerate with identical options rendered a different prompt:\nfirst: %s\nsecond: %s", promptBeforeRegenerate, imgServer.lastPrompt)
	}

	// Leg 3: different options on the same photo -- a subtle style with
	// everything else defaulted (natural shade, strength 1).
	final3 := smileSimulateBodyAndWait(t, srv, token, simulateBody(map[string]any{"smile_style": "subtle"}), deadline)
	if status, _ := final3["status"].(string); status != "succeeded" {
		t.Fatalf("third job status = %v, want \"succeeded\"", final3["status"])
	}
	if !strings.Contains(imgServer.lastPrompt, "subtle, gentle smile with only a slight curve") {
		t.Errorf("third vendor prompt missing the subtle style clause:\n%s", imgServer.lastPrompt)
	}
	assertOptionsIn(t, final3, "subtle", "natural", 1)

	// The per-photo enumeration lists all three generations, each with the
	// options that produced it, its status and its output object.
	sims := enumerateSimulations(t, srv, token, completedPhoto.ID)
	if len(sims) != 3 {
		t.Fatalf("enumeration returned %d simulations, want 3 (two same-option generations plus one different-option one)", len(sims))
	}
	byJob := make(map[string]map[string]any, len(sims))
	jobIDs := make(map[string]bool, len(sims))
	for _, sim := range sims {
		jobID, _ := sim["job_id"].(string)
		if jobID == "" {
			t.Fatalf("enumeration entry carries no job_id: %+v", sim)
		}
		jobIDs[jobID] = true
		byJob[jobID] = sim
		if photoID, _ := sim["photo_object_id"].(string); photoID != completedPhoto.ID {
			t.Errorf("enumeration entry photo_object_id = %q, want %q", photoID, completedPhoto.ID)
		}
		if status, _ := sim["status"].(string); status != "succeeded" {
			t.Errorf("enumeration entry status = %q, want succeeded (entry: %+v)", status, sim)
		}
		if out, _ := sim["output_object_id"].(string); out == "" {
			t.Errorf("enumeration entry for a succeeded job carries no output_object_id: %+v", sim)
		}
		if createdAt, _ := sim["created_at"].(string); createdAt == "" {
			t.Errorf("enumeration entry carries no created_at: %+v", sim)
		}
	}
	if len(jobIDs) != 3 {
		t.Fatalf("enumeration returned %d distinct job ids, want 3 -- a same-option regenerate must be a distinct generation", len(jobIDs))
	}
	// Match entries to what each leg asked for by their recorded options.
	byOptions := make(map[string][]string)
	for jobID, sim := range byJob {
		options, ok := sim["options"].(map[string]any)
		if !ok {
			t.Fatalf("enumeration entry carries no options: %+v", sim)
		}
		style, _ := options["smile_style"].(string)
		shade, _ := options["tooth_shade"].(string)
		strength, _ := options["strength"].(float64)
		key := style + "/" + shade + "/" + strengthTextForTest(strength)
		byOptions[key] = append(byOptions[key], jobID)
	}
	if got := byOptions["bright/ultra-white/0.4"]; len(got) != 2 {
		t.Errorf("same-option generations recorded = %v, want 2 (the regenerate must be recorded as its own generation)", got)
	}
	if got := byOptions["subtle/natural/1"]; len(got) != 1 {
		t.Errorf("defaulted-option generation recorded = %v, want exactly 1 with the documented defaults", got)
	}
}

// strengthTextForTest renders a decoded JSON strength value (float64) the
// way this test's option keys expect -- shortest decimal, no exponent --
// matching how the server itself stores and echoes the value.
func strengthTextForTest(v float64) string {
	return strconv.FormatFloat(v, 'f', -1, 64)
}

// TestSmileSimulation_InvalidOptions_RefusedWithCodedErrors pins the
// parameterization's rejection contract at the HTTP layer: an option
// outside the vocabulary or range is refused with its coded 400 error --
// never clamped, never silently replaced by a default -- and the refusal
// happens before go/ai-gateway (and therefore any real vendor) is ever
// reached, leaving no job and no per-photo record behind.
func TestSmileSimulation_InvalidOptions_RefusedWithCodedErrors(t *testing.T) {
	imgServer := newFakeOpenAIImageServer(t)
	srv, cfg := buildSmileSimTestServer(t, imgServer)

	token := registerAndAuthenticate(t, srv, cfg, "tenant-acme", "smilesim-invalid-owner")

	invalidBodies := []struct {
		name     string
		options  map[string]any
		wantCode string
	}{
		{name: "unknown smile style", options: map[string]any{"smile_style": "dazzling"}, wantCode: "smilesim.unsupported_smile_style"},
		{name: "unknown tooth shade", options: map[string]any{"tooth_shade": "grey"}, wantCode: "smilesim.unsupported_tooth_shade"},
		{name: "strength above the upper bound", options: map[string]any{"strength": 1.5}, wantCode: "smilesim.strength_out_of_range"},
		{name: "strength at the excluded lower bound", options: map[string]any{"strength": 0}, wantCode: "smilesim.strength_out_of_range"},
	}
	for _, tt := range invalidBodies {
		t.Run(tt.name, func(t *testing.T) {
			body, err := json.Marshal(map[string]any{
				"photo_object_id": "photo-does-not-matter",
				"options":         tt.options,
			})
			if err != nil {
				t.Fatalf("marshal body: %v", err)
			}
			resp := smileSimRequest(t, srv, http.MethodPost, smileSimulatePath, token, body)
			var out map[string]any
			if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
				resp.Body.Close()
				t.Fatalf("decode error response: %v", decErr)
			}
			resp.Body.Close()
			if resp.StatusCode != http.StatusBadRequest {
				t.Fatalf("POST status = %d, want %d; body = %+v", resp.StatusCode, http.StatusBadRequest, out)
			}
			if code, _ := out["code"].(string); code != tt.wantCode {
				t.Errorf("error code = %q, want %q; body = %+v", code, tt.wantCode, out)
			}
		})
	}

	// None of the refusals reached the vendor, and none left a per-photo
	// record or a job behind.
	if imgServer.requests != 0 {
		t.Errorf("fake vendor received %d requests, want 0 -- an invalid option set must never reach the provider", imgServer.requests)
	}
	if sims := enumerateSimulations(t, srv, token, "photo-does-not-matter"); len(sims) != 0 {
		t.Errorf("enumeration after refused simulations returned %d entries, want 0", len(sims))
	}
}

// TestSmileSimulation_CrossTenantRecipient_RefusedBeforeAnyEnqueue is the
// mandatory regression: a POST
// /simulate naming a recipient who does NOT belong to the caller's tenant
// must be refused with the app's coded error before Simulate enqueues
// anything -- no job, no per-photo record, no vendor call, and above all no
// delivery to the cross-tenant member's phone. The bug it pins: any
// recipient_user_id was accepted, so a member of one tenant could name a
// member of another and that member's phone received the simulation-ready
// SMS under the caller's tenant.
//
// DemoSmileSimRecipientUserID (the demo address table's phone-carrying
// fixture, internal/app/demo/demo_notification.go) is granted membership in tenant-globex
// ALONE here -- the tenant-B user whose phone the tenant-acme caller must
// not be able to reach. The bug-state leg below polls the accepted job to
// completion and records the SMS landing on that phone, so the failing run
// shows the actual harm rather than only the missing refusal.
func TestSmileSimulation_CrossTenantRecipient_RefusedBeforeAnyEnqueue(t *testing.T) {
	imgServer := newFakeOpenAIImageServer(t)

	cfg := testConfig(t)
	cfg.AIGatewayImageBaseURL = imgServer.URL
	cfg.AIGatewayImageAPIKey = "sk-test-smilesim-xtenant-key"
	sms := &lockedBuffer{}
	cfg.SMSOutput = sms
	cfg.Memberships.Grant(demo.DemoSmileSimRecipientUserID, "tenant-globex")

	handler, cleanup, _, err := app.BuildServer(t.Context(), cfg)
	if err != nil {
		t.Fatalf("BuildServer: %v", err)
	}
	t.Cleanup(func() {
		if cleanupErr := cleanup(); cleanupErr != nil {
			t.Errorf("cleanup: %v", cleanupErr)
		}
	})
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)

	// The caller: an ordinary member of tenant-acme.
	token := registerAndAuthenticate(t, srv, cfg, "tenant-acme", "smilesim-xtenant-owner")

	// A real, completed photo, so that in the bug state (the request being
	// accepted) the enqueued job genuinely succeeds and the completion
	// notification reaches the named recipient -- the exact harm the refusal prevents
	// refuses, reproduced rather than assumed.
	photo := jpegWithExif(t)
	completedPhoto := uploadAndComplete(t, srv, token, photo, "")
	if completedPhoto.State != "completed" {
		t.Fatalf("photo state = %q, want completed", completedPhoto.State)
	}

	simulateBody, err := json.Marshal(map[string]string{
		"photo_object_id":   completedPhoto.ID,
		"recipient_user_id": demo.DemoSmileSimRecipientUserID,
	})
	if err != nil {
		t.Fatalf("marshal simulate request: %v", err)
	}
	resp := smileSimRequest(t, srv, http.MethodPost, smileSimulatePath, token, simulateBody)
	var out struct {
		JobID string `json:"job_id"`
		Code  string `json:"code"`
	}
	if decErr := json.NewDecoder(resp.Body).Decode(&out); decErr != nil {
		resp.Body.Close()
		t.Fatalf("decode simulate response: %v", decErr)
	}
	resp.Body.Close()

	recipientPhone := demo.DemoUserAddresses[demo.DemoSmileSimRecipientUserID].Phone
	if recipientPhone == "" {
		t.Fatal("the demo recipient fixture carries no phone address -- the scenario needs one to demonstrate the harm")
	}

	// Bug-state evidence: an accepted request (202) runs the job to
	// completion and puts the simulation-ready SMS on the CROSS-TENANT
	// member's phone -- the delivery the refusal prevents. On the fixed
	// tree this branch is unreachable (the refusal comes first).
	if resp.StatusCode == http.StatusAccepted && out.JobID != "" {
		waitForSmileSimSucceeded(t, srv, token, out.JobID, time.Now().Add(5*time.Second))
		eventually(t, 4*time.Second, "the simulation-ready SMS to the cross-tenant member's phone (bug state)", func() bool {
			return len(smsLinesTo(sms, recipientPhone)) == 1
		})
		t.Fatalf("the simulate request naming a TENANT-B recipient was accepted with 202 -- the cross-tenant " +
			"delivery this round must refuse before any enqueue (its SMS reached the foreign member's phone)")
	}

	// The fixed state: the cross-tenant recipient is refused with the app's
	// coded error, before Simulate enqueues anything.
	if resp.StatusCode != http.StatusBadRequest || out.Code != "smilesim.recipient_not_in_tenant" {
		t.Fatalf("POST /simulate naming a tenant-B recipient: status = %d, code = %q, want 400 %q",
			resp.StatusCode, out.Code, "smilesim.recipient_not_in_tenant")
	}
	if imgServer.requests != 0 {
		t.Errorf("fake vendor received %d requests, want 0 -- a refused recipient must never reach the provider", imgServer.requests)
	}
	never(t, 3*time.Second, "an SMS to the cross-tenant member's phone after the refusal", func() bool {
		return len(smsLinesTo(sms, recipientPhone)) > 0
	})
}
