// Code generated by orval 8.17.0. DO NOT EDIT.
// Source: speed
// The mutator import in this file is rewritten to an explicit
// .js extension by web/scripts/orval-nodenext-fixup.mjs (nodenext
// builds); rerun it after every regeneration.
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { speedRequest } from './runtime.js';
import { speedRequestCredentialless } from './runtime.js';
export interface NotesCreateNoteRequest {
  /**
     * The note's placeholder content.
     * @minLength 1
     * @maxLength 4000
     */
  text: string;
}

export interface NotesNote {
  /** Application-generated UUID. */
  id?: string;
  text?: string;
  created_at?: string;
}

export interface NotesListNotesResponse {
  notes?: NotesNote[];
}

export type NotesErrorParams = { [key: string]: unknown };

/**
 * The structured {code, params} error envelope every speed API returns instead of localized text (backend coding standard §6.2; docs/internal/11-cross-cutting.md) -- a client resolves code through its own i18n catalog, populated from this module's Locales() resources for the codes documented in its error index.
 */
export interface NotesError {
  code?: string;
  params?: NotesErrorParams;
}

export interface AuthnRegisterRequest {
  email?: string;
  phone?: string;
  password: string;
  display_name?: string;
  locale?: string;
}

export interface AuthnUser {
  id?: string;
  email?: string;
  phone?: string;
  display_name?: string;
  locale?: string;
  email_verified?: boolean;
  phone_verified?: boolean;
  created_at?: string;
}

export interface AuthnLoginWithPasswordRequest {
  /** An email address or phone number. */
  identifier: string;
  password: string;
  /** Requests this tenant's first access token; empty means the caller's first tenant. A request, never a grant. */
  tenant_id?: string;
  device?: string;
}

export interface AuthnRequestSMSCodeRequest {
  phone: string;
}

export interface AuthnLoginWithSMSCodeRequest {
  phone: string;
  code: string;
  tenant_id?: string;
  device?: string;
}

export interface AuthnRefreshTokenRequest {
  refresh_token: string;
}

export interface AuthnPrincipal {
  user_id?: string;
  tenant_id?: string;
  session_id?: string;
  email?: string;
  amr?: string[];
}

export interface AuthnTokenPair {
  access_token?: string;
  access_expires_at?: string;
  /** Absent when this response did not mint a new refresh token (a tenant switch or a step-up, both of which reuse the caller's existing one). */
  refresh_token?: string;
  refresh_expires_at?: string;
  principal?: AuthnPrincipal;
}

export interface AuthnSocialAuthorizeResponse {
  authorize_url?: string;
}

export interface AuthnSocialCallbackRequest {
  code: string;
  state: string;
  tenant_id?: string;
}

export interface AuthnIdentity {
  id?: string;
  provider?: string;
  email?: string;
  display_name?: string;
  avatar_url?: string;
  created_at?: string;
  last_login_at?: string;
}

export interface AuthnSocialLoginResponse {
  user?: AuthnUser;
  identity?: AuthnIdentity;
  tokens?: AuthnTokenPair;
  created?: boolean;
  bound?: boolean;
  auto_linked?: boolean;
}

export interface AuthnListIdentitiesResponse {
  identities?: AuthnIdentity[];
}

export interface AuthnEnrollTOTPResponse {
  secret?: string;
  provisioning_uri?: string;
}

export interface AuthnConfirmTOTPRequest {
  code: string;
}

export interface AuthnRecoveryCodesResponse {
  recovery_codes?: string[];
}

export interface AuthnVerifyStepUpRequest {
  code: string;
}

export interface AuthnSwitchTenantRequest {
  tenant_id: string;
}

export interface AuthnSession {
  id?: string;
  status?: string;
  device?: string;
  user_agent?: string;
  ip?: string;
  amr?: string[];
  created_at?: string;
  last_seen_at?: string;
  is_current?: boolean;
}

export interface AuthnListSessionsResponse {
  sessions?: AuthnSession[];
}

export interface AuthnRevokeOtherSessionsResponse {
  revoked_count?: number;
}

export interface AuthnLoginAttempt {
  id?: string;
  method?: string;
  result?: string;
  failure_reason?: string;
  ip?: string;
  user_agent?: string;
  created_at?: string;
}

export interface AuthnListLoginHistoryResponse {
  attempts?: AuthnLoginAttempt[];
}

export type AuthnErrorParams = { [key: string]: unknown };

/**
 * The structured {code, params} error envelope every speed API returns instead of localized text (backend coding standard §6.2) -- a client resolves code through its own i18n catalog, populated from this module's Locales() resources for the codes documented on each operation above.
 */
export interface AuthnError {
  code?: string;
  params?: AuthnErrorParams;
}

/**
 * The template parameters that produced title and body, keyed by the names the templates' placeholders spell out.
 */
export type NotificationMessageParams = { [key: string]: unknown };

/**
 * One inbox row: a message rendered for this recipient at delivery time, in the recipient's locale. title and body are the rendered text -- never template ids, which a client cannot resolve -- and params is the interpolation map that produced them, for a client that renders its own richer copy from the type directory.
 */
export interface NotificationMessage {
  /** The message's id. */
  id: string;
  /** The notification type this message was rendered from, <module>.<entity>.<action>. */
  type_key: string;
  /** The message's group classification, taken from its type at delivery time. */
  group: string;
  /** The rendered headline of the message. */
  title: string;
  /** The rendered body of the message. */
  body: string;
  /** The template parameters that produced title and body, keyed by the names the templates' placeholders spell out. */
  params: NotificationMessageParams;
  /** The optional deep link the message points at; empty when the message has none. */
  link: string;
  /**
     * When the message stops counting as unread, server time; null when it never expires.
     * @nullable
     */
  expiry_at?: string | null;
  /**
     * When the recipient read the message; null while it is unread.
     * @nullable
     */
  read_at?: string | null;
  /** When the message was delivered into the inbox. */
  created_at: string;
}

/**
 * One page of the caller's inbox.
 */
export interface NotificationListMessagesResponse {
  /** The page's messages, newest first. */
  items: NotificationMessage[];
}

/**
 * The caller's unread message count.
 */
export interface NotificationUnreadCountResponse {
  /** The number of unread messages. */
  count: number;
}

/**
 * The outcome of a mark-all-read call.
 */
export interface NotificationReadAllResponse {
  /** The number of messages this call marked read. */
  read_count: number;
}

/**
 * One declared notification type. Unsubscribable=false marks delivery the host guarantees: the recipient cannot switch these channels off through a preference.
 */
export interface NotificationType {
  /** The type key, <module>.<entity>.<action>. */
  type_key: string;
  /** The type's inbox classification group. */
  group: string;
  /** The channels a recipient gets by default, before expressing any preference. The closed vocabulary: in_app, email, sms. */
  default_channels: string[];
  /** Whether the recipient may opt out of this type's channels. */
  unsubscribable: boolean;
  /** The type's copy, rendered from the declaring module's locale bundle in the negotiated language. */
  description: string;
}

/**
 * The deployment's declared notification types.
 */
export interface NotificationListTypesResponse {
  /** The declared types, in declaration order. */
  items: NotificationType[];
}

/**
 * The caller's effective channel state for one notification type: the set of channels the caller currently receives, the type's defaults reduced by the caller's opt-outs.
 */
export interface NotificationPreference {
  /** The type key this state belongs to. */
  type_key: string;
  /** The channels currently enabled for the caller, a subset of the type's vocabulary. */
  channels: string[];
}

/**
 * The caller's channel preferences per declared type.
 */
export interface NotificationListPreferencesResponse {
  /** One entry per declared type, effective channels merged with defaults. */
  items: NotificationPreference[];
}

/**
 * One channel toggle for one notification type.
 */
export interface NotificationUpdatePreferenceRequest {
  /** Whether the caller wants this type over this channel. */
  enabled: boolean;
}

/**
 * The address's channel.
 */
export type NotificationContactChannel = typeof NotificationContactChannel[keyof typeof NotificationContactChannel];


export const NotificationContactChannel = {
  email: 'email',
  sms: 'sms',
} as const;

/**
 * The contact's consent status: pending (code issued, awaiting verification), verified (consent proven), unsubscribed (consent withdrawn), or bounced (delivery failed hard).
 */
export type NotificationContactStatus = typeof NotificationContactStatus[keyof typeof NotificationContactStatus];


export const NotificationContactStatus = {
  pending: 'pending',
  verified: 'verified',
  unsubscribed: 'unsubscribed',
  bounced: 'bounced',
} as const;

/**
 * One contact row. The address itself never appears in this document's responses: plaintext addresses are PII and the blind-index would be an offline brute-force surface, so the API serves id, channel, status and timestamps only.
 */
export interface NotificationContact {
  /** The contact's id. */
  id: string;
  /** The address's channel. */
  channel: NotificationContactChannel;
  /** The contact's consent status: pending (code issued, awaiting verification), verified (consent proven), unsubscribed (consent withdrawn), or bounced (delivery failed hard). */
  status: NotificationContactStatus;
  /** When the contact was added. */
  created_at: string;
}

/**
 * The tenant's contacts, newest first.
 */
export interface NotificationListContactsResponse {
  items: NotificationContact[];
}

/**
 * The address's channel.
 */
export type NotificationCreateContactRequestChannel = typeof NotificationCreateContactRequestChannel[keyof typeof NotificationCreateContactRequestChannel];


export const NotificationCreateContactRequestChannel = {
  email: 'email',
  sms: 'sms',
} as const;

/**
 * A new contact address to register through double opt-in.
 */
export interface NotificationCreateContactRequest {
  /** The address's channel. */
  channel: NotificationCreateContactRequestChannel;
  /** The address itself: an email address, or a phone number in a form the module can normalize to E.164. Never logged; stored encrypted. */
  address: string;
}

/**
 * The code the contact's address received.
 */
export interface NotificationVerifyContactRequest {
  /** The verification code from the contact's message. */
  code: string;
}

export type NotificationErrorParams = { [key: string]: unknown };

/**
 * The structured {code, params} error envelope every speed API returns instead of localized text (backend coding standard §6.2; docs/internal/11-cross-cutting.md) -- a client resolves code through its own i18n catalog, populated from this module's Locales() resources for the codes documented in its error index.
 */
export interface NotificationError {
  code?: string;
  params?: NotificationErrorParams;
}

export type AuthnSocialAuthorizeParams = {
redirect_uri: string;
};

export type AuthnListLoginHistoryParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type NotificationListMessagesParams = {
/**
 * Return only messages of this notification group.
 */
group?: string;
/**
 * The maximum number of rows to return. The module's read surface caps the page at 200 rows; larger limits are refused rather than silently truncated.
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * The number of rows to skip before the returned page.
 * @minimum 0
 */
offset?: number;
};

/**
 * The tenant is always the one tenancy.Middleware already resolved from the request; there is no tenant_id field anywhere on this request, by design (root CLAUDE.md's multi-tenant isolation rule).
 * @summary Create a note for the caller's tenant.
 */
export const notesCreateNote = (
    notesCreateNoteRequest: NotesCreateNoteRequest,
 signal?: AbortSignal
) => {


      return speedRequest<NotesNote>(
      {url: `/api/v1/notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: notesCreateNoteRequest, signal
    },
      );
    }



export const getNotesCreateNoteMutationOptions = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext> => {

const mutationKey = ['notesCreateNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesCreateNote>>, {data: NotesCreateNoteRequest}> = (props) => {
          const {data} = props ?? {};

          return  notesCreateNote(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesCreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesCreateNote>>>
    export type NotesCreateNoteMutationBody = NotesCreateNoteRequest
    export type NotesCreateNoteMutationError = NotesError

    /**
 * @summary Create a note for the caller's tenant.
 */
export const useNotesCreateNote = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notesCreateNote>>,
        TError,
        {data: NotesCreateNoteRequest},
        TContext
      > => {
      return useMutation(getNotesCreateNoteMutationOptions(options));
    }

/**
 * @summary List every note belonging to the caller's tenant.
 */
export const notesListNotes = (

 signal?: AbortSignal
) => {


      return speedRequest<NotesListNotesResponse>(
      {url: `/api/v1/notes`, method: 'GET', signal
    },
      );
    }




export const getNotesListNotesQueryKey = () => {
    return [
    `/api/v1/notes`
    ] as const;
    }


export const getNotesListNotesQueryOptions = <TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotesListNotesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notesListNotes>>> = ({ signal }) => notesListNotes(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData> & { queryKey: QueryKey }
}

export type NotesListNotesQueryResult = NonNullable<Awaited<ReturnType<typeof notesListNotes>>>
export type NotesListNotesQueryError = unknown


/**
 * @summary List every note belonging to the caller's tenant.
 */

export function useNotesListNotes<TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotesListNotesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * At least one of email and phone must be present. The response is the created account with no password field, ever.
 * @summary Register a new account.
 */
export const authnRegister = (
    authnRegisterRequest: AuthnRegisterRequest,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnUser>(
      {url: `/api/v1/authn/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnRegisterRequest, signal
    },
      );
    }



export const getAuthnRegisterMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRegister>>, TError,{data: AuthnRegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnRegister>>, TError,{data: AuthnRegisterRequest}, TContext> => {

const mutationKey = ['authnRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnRegister>>, {data: AuthnRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnRegister(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authnRegister>>>
    export type AuthnRegisterMutationBody = AuthnRegisterRequest
    export type AuthnRegisterMutationError = AuthnError

    /**
 * @summary Register a new account.
 */
export const useAuthnRegister = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRegister>>, TError,{data: AuthnRegisterRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnRegister>>,
        TError,
        {data: AuthnRegisterRequest},
        TContext
      > => {
      return useMutation(getAuthnRegisterMutationOptions(options));
    }

/**
 * @summary Sign in with an email or phone identifier and a password.
 */
export const authnLoginWithPassword = (
    authnLoginWithPasswordRequest: AuthnLoginWithPasswordRequest,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnTokenPair>(
      {url: `/api/v1/authn/login/password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnLoginWithPasswordRequest, signal
    },
      );
    }



export const getAuthnLoginWithPasswordMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnLoginWithPassword>>, TError,{data: AuthnLoginWithPasswordRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnLoginWithPassword>>, TError,{data: AuthnLoginWithPasswordRequest}, TContext> => {

const mutationKey = ['authnLoginWithPassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnLoginWithPassword>>, {data: AuthnLoginWithPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnLoginWithPassword(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnLoginWithPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authnLoginWithPassword>>>
    export type AuthnLoginWithPasswordMutationBody = AuthnLoginWithPasswordRequest
    export type AuthnLoginWithPasswordMutationError = AuthnError

    /**
 * @summary Sign in with an email or phone identifier and a password.
 */
export const useAuthnLoginWithPassword = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnLoginWithPassword>>, TError,{data: AuthnLoginWithPasswordRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnLoginWithPassword>>,
        TError,
        {data: AuthnLoginWithPasswordRequest},
        TContext
      > => {
      return useMutation(getAuthnLoginWithPasswordMutationOptions(options));
    }

/**
 * Always answers 202 whether or not the phone number belongs to an account -- go/authn/verification.go's RequestSMSCode never discloses registration status. There is nothing here for a legitimate caller to branch on either way.
 * @summary Request a one-time SMS sign-in code for a phone number.
 */
export const authnRequestSMSCode = (
    authnRequestSMSCodeRequest: AuthnRequestSMSCodeRequest,
 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/authn/login/sms/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnRequestSMSCodeRequest, signal
    },
      );
    }



export const getAuthnRequestSMSCodeMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRequestSMSCode>>, TError,{data: AuthnRequestSMSCodeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnRequestSMSCode>>, TError,{data: AuthnRequestSMSCodeRequest}, TContext> => {

const mutationKey = ['authnRequestSMSCode'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnRequestSMSCode>>, {data: AuthnRequestSMSCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnRequestSMSCode(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnRequestSMSCodeMutationResult = NonNullable<Awaited<ReturnType<typeof authnRequestSMSCode>>>
    export type AuthnRequestSMSCodeMutationBody = AuthnRequestSMSCodeRequest
    export type AuthnRequestSMSCodeMutationError = AuthnError

    /**
 * @summary Request a one-time SMS sign-in code for a phone number.
 */
export const useAuthnRequestSMSCode = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRequestSMSCode>>, TError,{data: AuthnRequestSMSCodeRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnRequestSMSCode>>,
        TError,
        {data: AuthnRequestSMSCodeRequest},
        TContext
      > => {
      return useMutation(getAuthnRequestSMSCodeMutationOptions(options));
    }

/**
 * @summary Sign in with a phone number and the SMS code sent to it.
 */
export const authnLoginWithSMSCode = (
    authnLoginWithSMSCodeRequest: AuthnLoginWithSMSCodeRequest,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnTokenPair>(
      {url: `/api/v1/authn/login/sms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnLoginWithSMSCodeRequest, signal
    },
      );
    }



export const getAuthnLoginWithSMSCodeMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnLoginWithSMSCode>>, TError,{data: AuthnLoginWithSMSCodeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnLoginWithSMSCode>>, TError,{data: AuthnLoginWithSMSCodeRequest}, TContext> => {

const mutationKey = ['authnLoginWithSMSCode'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnLoginWithSMSCode>>, {data: AuthnLoginWithSMSCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnLoginWithSMSCode(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnLoginWithSMSCodeMutationResult = NonNullable<Awaited<ReturnType<typeof authnLoginWithSMSCode>>>
    export type AuthnLoginWithSMSCodeMutationBody = AuthnLoginWithSMSCodeRequest
    export type AuthnLoginWithSMSCodeMutationError = AuthnError

    /**
 * @summary Sign in with a phone number and the SMS code sent to it.
 */
export const useAuthnLoginWithSMSCode = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnLoginWithSMSCode>>, TError,{data: AuthnLoginWithSMSCodeRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnLoginWithSMSCode>>,
        TError,
        {data: AuthnLoginWithSMSCodeRequest},
        TContext
      > => {
      return useMutation(getAuthnLoginWithSMSCodeMutationOptions(options));
    }

/**
 * @summary Rotate a refresh token for a new access token.
 */
export const authnRefreshToken = (
    authnRefreshTokenRequest: AuthnRefreshTokenRequest,
 signal?: AbortSignal
) => {


      return speedRequestCredentialless<AuthnTokenPair>(
      {url: `/api/v1/authn/token/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnRefreshTokenRequest, signal
    },
      );
    }



export const getAuthnRefreshTokenMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRefreshToken>>, TError,{data: AuthnRefreshTokenRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnRefreshToken>>, TError,{data: AuthnRefreshTokenRequest}, TContext> => {

const mutationKey = ['authnRefreshToken'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnRefreshToken>>, {data: AuthnRefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnRefreshToken(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnRefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authnRefreshToken>>>
    export type AuthnRefreshTokenMutationBody = AuthnRefreshTokenRequest
    export type AuthnRefreshTokenMutationError = AuthnError

    /**
 * @summary Rotate a refresh token for a new access token.
 */
export const useAuthnRefreshToken = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRefreshToken>>, TError,{data: AuthnRefreshTokenRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnRefreshToken>>,
        TError,
        {data: AuthnRefreshTokenRequest},
        TContext
      > => {
      return useMutation(getAuthnRefreshTokenMutationOptions(options));
    }

/**
 * Revokes the session the caller's own access token belongs to. Every other device's session is untouched -- see revoke-others for that.
 * @summary Sign out the calling session.
 */
export const authnLogout = (

 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/authn/logout`, method: 'POST', signal
    },
      );
    }



export const getAuthnLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnLogout>>, TError,void, TContext> => {

const mutationKey = ['authnLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnLogout>>, void> = () => {


          return  authnLogout()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authnLogout>>>

    export type AuthnLogoutMutationError = unknown

    /**
 * @summary Sign out the calling session.
 */
export const useAuthnLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnLogout>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthnLogoutMutationOptions(options));
    }

/**
 * Signed in and calling this with a valid Principal turns the flow into BINDING a new identity to the caller's own account instead of signing in -- see the callback operation's response.
 * @summary Build the authorization URL for a social sign-in channel.
 */
export const authnSocialAuthorize = (
    provider: string,
    params: AuthnSocialAuthorizeParams,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnSocialAuthorizeResponse>(
      {url: `/api/v1/authn/social/${provider}/authorize`, method: 'GET',
        params, signal
    },
      );
    }




export const getAuthnSocialAuthorizeQueryKey = (provider: string,
    params?: AuthnSocialAuthorizeParams,) => {
    return [
    `/api/v1/authn/social/${provider}/authorize`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuthnSocialAuthorizeQueryOptions = <TData = Awaited<ReturnType<typeof authnSocialAuthorize>>, TError = AuthnError>(provider: string,
    params: AuthnSocialAuthorizeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnSocialAuthorize>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthnSocialAuthorizeQueryKey(provider,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authnSocialAuthorize>>> = ({ signal }) => authnSocialAuthorize(provider,params, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authnSocialAuthorize>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthnSocialAuthorizeQueryResult = NonNullable<Awaited<ReturnType<typeof authnSocialAuthorize>>>
export type AuthnSocialAuthorizeQueryError = AuthnError


/**
 * @summary Build the authorization URL for a social sign-in channel.
 */

export function useAuthnSocialAuthorize<TData = Awaited<ReturnType<typeof authnSocialAuthorize>>, TError = AuthnError>(
 provider: string,
    params: AuthnSocialAuthorizeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnSocialAuthorize>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthnSocialAuthorizeQueryOptions(provider,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Complete a social sign-in or account-binding authorization flow.
 */
export const authnSocialCallback = (
    provider: string,
    authnSocialCallbackRequest: AuthnSocialCallbackRequest,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnSocialLoginResponse>(
      {url: `/api/v1/authn/social/${provider}/callback`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnSocialCallbackRequest, signal
    },
      );
    }



export const getAuthnSocialCallbackMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnSocialCallback>>, TError,{provider: string;data: AuthnSocialCallbackRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnSocialCallback>>, TError,{provider: string;data: AuthnSocialCallbackRequest}, TContext> => {

const mutationKey = ['authnSocialCallback'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnSocialCallback>>, {provider: string;data: AuthnSocialCallbackRequest}> = (props) => {
          const {provider,data} = props ?? {};

          return  authnSocialCallback(provider,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnSocialCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof authnSocialCallback>>>
    export type AuthnSocialCallbackMutationBody = AuthnSocialCallbackRequest
    export type AuthnSocialCallbackMutationError = AuthnError

    /**
 * @summary Complete a social sign-in or account-binding authorization flow.
 */
export const useAuthnSocialCallback = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnSocialCallback>>, TError,{provider: string;data: AuthnSocialCallbackRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnSocialCallback>>,
        TError,
        {provider: string;data: AuthnSocialCallbackRequest},
        TContext
      > => {
      return useMutation(getAuthnSocialCallbackMutationOptions(options));
    }

/**
 * @summary List the caller's own bound external identities.
 */
export const authnListIdentities = (

 signal?: AbortSignal
) => {


      return speedRequest<AuthnListIdentitiesResponse>(
      {url: `/api/v1/authn/identities`, method: 'GET', signal
    },
      );
    }




export const getAuthnListIdentitiesQueryKey = () => {
    return [
    `/api/v1/authn/identities`
    ] as const;
    }


export const getAuthnListIdentitiesQueryOptions = <TData = Awaited<ReturnType<typeof authnListIdentities>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnListIdentities>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthnListIdentitiesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authnListIdentities>>> = ({ signal }) => authnListIdentities(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authnListIdentities>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthnListIdentitiesQueryResult = NonNullable<Awaited<ReturnType<typeof authnListIdentities>>>
export type AuthnListIdentitiesQueryError = unknown


/**
 * @summary List the caller's own bound external identities.
 */

export function useAuthnListIdentities<TData = Awaited<ReturnType<typeof authnListIdentities>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnListIdentities>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthnListIdentitiesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Unbind one of the caller's own external identities.
 */
export const authnUnbindIdentity = (
    identityId: string,
 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/authn/identities/${identityId}`, method: 'DELETE', signal
    },
      );
    }



export const getAuthnUnbindIdentityMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnUnbindIdentity>>, TError,{identityId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnUnbindIdentity>>, TError,{identityId: string}, TContext> => {

const mutationKey = ['authnUnbindIdentity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnUnbindIdentity>>, {identityId: string}> = (props) => {
          const {identityId} = props ?? {};

          return  authnUnbindIdentity(identityId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnUnbindIdentityMutationResult = NonNullable<Awaited<ReturnType<typeof authnUnbindIdentity>>>

    export type AuthnUnbindIdentityMutationError = AuthnError

    /**
 * @summary Unbind one of the caller's own external identities.
 */
export const useAuthnUnbindIdentity = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnUnbindIdentity>>, TError,{identityId: string}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnUnbindIdentity>>,
        TError,
        {identityId: string},
        TContext
      > => {
      return useMutation(getAuthnUnbindIdentityMutationOptions(options));
    }

/**
 * Replaces any existing TOTP factor (pending or active) with a fresh pending one, which must be confirmed with authn_confirmTOTP before it can satisfy a step-up.
 * @summary Start TOTP enrollment for the caller's account.
 */
export const authnEnrollTOTP = (

 signal?: AbortSignal
) => {


      return speedRequest<AuthnEnrollTOTPResponse>(
      {url: `/api/v1/authn/mfa/totp/enroll`, method: 'POST', signal
    },
      );
    }



export const getAuthnEnrollTOTPMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnEnrollTOTP>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnEnrollTOTP>>, TError,void, TContext> => {

const mutationKey = ['authnEnrollTOTP'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnEnrollTOTP>>, void> = () => {


          return  authnEnrollTOTP()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnEnrollTOTPMutationResult = NonNullable<Awaited<ReturnType<typeof authnEnrollTOTP>>>

    export type AuthnEnrollTOTPMutationError = unknown

    /**
 * @summary Start TOTP enrollment for the caller's account.
 */
export const useAuthnEnrollTOTP = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnEnrollTOTP>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnEnrollTOTP>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthnEnrollTOTPMutationOptions(options));
    }

/**
 * @summary Confirm a pending TOTP enrollment.
 */
export const authnConfirmTOTP = (
    authnConfirmTOTPRequest: AuthnConfirmTOTPRequest,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnRecoveryCodesResponse>(
      {url: `/api/v1/authn/mfa/totp/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnConfirmTOTPRequest, signal
    },
      );
    }



export const getAuthnConfirmTOTPMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnConfirmTOTP>>, TError,{data: AuthnConfirmTOTPRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnConfirmTOTP>>, TError,{data: AuthnConfirmTOTPRequest}, TContext> => {

const mutationKey = ['authnConfirmTOTP'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnConfirmTOTP>>, {data: AuthnConfirmTOTPRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnConfirmTOTP(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnConfirmTOTPMutationResult = NonNullable<Awaited<ReturnType<typeof authnConfirmTOTP>>>
    export type AuthnConfirmTOTPMutationBody = AuthnConfirmTOTPRequest
    export type AuthnConfirmTOTPMutationError = AuthnError

    /**
 * @summary Confirm a pending TOTP enrollment.
 */
export const useAuthnConfirmTOTP = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnConfirmTOTP>>, TError,{data: AuthnConfirmTOTPRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnConfirmTOTP>>,
        TError,
        {data: AuthnConfirmTOTPRequest},
        TContext
      > => {
      return useMutation(getAuthnConfirmTOTPMutationOptions(options));
    }

/**
 * Requires an ACTIVE TOTP factor; every previous code stops working at once.
 * @summary Discard the caller's recovery codes and issue a fresh batch.
 */
export const authnRegenerateRecoveryCodes = (

 signal?: AbortSignal
) => {


      return speedRequest<AuthnRecoveryCodesResponse>(
      {url: `/api/v1/authn/mfa/recovery-codes/regenerate`, method: 'POST', signal
    },
      );
    }



export const getAuthnRegenerateRecoveryCodesMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRegenerateRecoveryCodes>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnRegenerateRecoveryCodes>>, TError,void, TContext> => {

const mutationKey = ['authnRegenerateRecoveryCodes'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnRegenerateRecoveryCodes>>, void> = () => {


          return  authnRegenerateRecoveryCodes()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnRegenerateRecoveryCodesMutationResult = NonNullable<Awaited<ReturnType<typeof authnRegenerateRecoveryCodes>>>

    export type AuthnRegenerateRecoveryCodesMutationError = AuthnError

    /**
 * @summary Discard the caller's recovery codes and issue a fresh batch.
 */
export const useAuthnRegenerateRecoveryCodes = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRegenerateRecoveryCodes>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnRegenerateRecoveryCodes>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthnRegenerateRecoveryCodesMutationOptions(options));
    }

/**
 * Mints a fresh access token whose amr carries the factor just verified, without otherwise changing the session (the refresh token is untouched). The elevation lives only in that access token's own lifetime -- a later natural refresh reverts to the session's original amr.
 * @summary Re-prove a second factor for the caller's CURRENT session.
 */
export const authnVerifyStepUp = (
    authnVerifyStepUpRequest: AuthnVerifyStepUpRequest,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnTokenPair>(
      {url: `/api/v1/authn/mfa/step-up`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnVerifyStepUpRequest, signal
    },
      );
    }



export const getAuthnVerifyStepUpMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnVerifyStepUp>>, TError,{data: AuthnVerifyStepUpRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnVerifyStepUp>>, TError,{data: AuthnVerifyStepUpRequest}, TContext> => {

const mutationKey = ['authnVerifyStepUp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnVerifyStepUp>>, {data: AuthnVerifyStepUpRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnVerifyStepUp(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnVerifyStepUpMutationResult = NonNullable<Awaited<ReturnType<typeof authnVerifyStepUp>>>
    export type AuthnVerifyStepUpMutationBody = AuthnVerifyStepUpRequest
    export type AuthnVerifyStepUpMutationError = AuthnError

    /**
 * @summary Re-prove a second factor for the caller's CURRENT session.
 */
export const useAuthnVerifyStepUp = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnVerifyStepUp>>, TError,{data: AuthnVerifyStepUpRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnVerifyStepUp>>,
        TError,
        {data: AuthnVerifyStepUpRequest},
        TContext
      > => {
      return useMutation(getAuthnVerifyStepUpMutationOptions(options));
    }

/**
 * @summary Reissue an access token for a different tenant, reusing the session.
 */
export const authnSwitchTenant = (
    authnSwitchTenantRequest: AuthnSwitchTenantRequest,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnTokenPair>(
      {url: `/api/v1/authn/tenant/switch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authnSwitchTenantRequest, signal
    },
      );
    }



export const getAuthnSwitchTenantMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnSwitchTenant>>, TError,{data: AuthnSwitchTenantRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnSwitchTenant>>, TError,{data: AuthnSwitchTenantRequest}, TContext> => {

const mutationKey = ['authnSwitchTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnSwitchTenant>>, {data: AuthnSwitchTenantRequest}> = (props) => {
          const {data} = props ?? {};

          return  authnSwitchTenant(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnSwitchTenantMutationResult = NonNullable<Awaited<ReturnType<typeof authnSwitchTenant>>>
    export type AuthnSwitchTenantMutationBody = AuthnSwitchTenantRequest
    export type AuthnSwitchTenantMutationError = AuthnError

    /**
 * @summary Reissue an access token for a different tenant, reusing the session.
 */
export const useAuthnSwitchTenant = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnSwitchTenant>>, TError,{data: AuthnSwitchTenantRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnSwitchTenant>>,
        TError,
        {data: AuthnSwitchTenantRequest},
        TContext
      > => {
      return useMutation(getAuthnSwitchTenantMutationOptions(options));
    }

/**
 * @summary Return the caller's own authenticated identity.
 */
export const authnGetMe = (

 signal?: AbortSignal
) => {


      return speedRequest<AuthnPrincipal>(
      {url: `/api/v1/authn/me`, method: 'GET', signal
    },
      );
    }




export const getAuthnGetMeQueryKey = () => {
    return [
    `/api/v1/authn/me`
    ] as const;
    }


export const getAuthnGetMeQueryOptions = <TData = Awaited<ReturnType<typeof authnGetMe>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnGetMe>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthnGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authnGetMe>>> = ({ signal }) => authnGetMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authnGetMe>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthnGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof authnGetMe>>>
export type AuthnGetMeQueryError = unknown


/**
 * @summary Return the caller's own authenticated identity.
 */

export function useAuthnGetMe<TData = Awaited<ReturnType<typeof authnGetMe>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnGetMe>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthnGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Includes revoked sessions -- Status tells them apart -- so the owner can see which device they signed out and when. is_current marks the session the request's own access token belongs to.
 * @summary List every one of the caller's own sessions (their device list).
 */
export const authnListSessions = (

 signal?: AbortSignal
) => {


      return speedRequest<AuthnListSessionsResponse>(
      {url: `/api/v1/authn/sessions`, method: 'GET', signal
    },
      );
    }




export const getAuthnListSessionsQueryKey = () => {
    return [
    `/api/v1/authn/sessions`
    ] as const;
    }


export const getAuthnListSessionsQueryOptions = <TData = Awaited<ReturnType<typeof authnListSessions>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnListSessions>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthnListSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authnListSessions>>> = ({ signal }) => authnListSessions(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authnListSessions>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthnListSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof authnListSessions>>>
export type AuthnListSessionsQueryError = unknown


/**
 * @summary List every one of the caller's own sessions (their device list).
 */

export function useAuthnListSessions<TData = Awaited<ReturnType<typeof authnListSessions>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnListSessions>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthnListSessionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Sign out one of the caller's own devices.
 */
export const authnRevokeSession = (
    sessionId: string,
 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/authn/sessions/${sessionId}`, method: 'DELETE', signal
    },
      );
    }



export const getAuthnRevokeSessionMutationOptions = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRevokeSession>>, TError,{sessionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnRevokeSession>>, TError,{sessionId: string}, TContext> => {

const mutationKey = ['authnRevokeSession'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnRevokeSession>>, {sessionId: string}> = (props) => {
          const {sessionId} = props ?? {};

          return  authnRevokeSession(sessionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnRevokeSessionMutationResult = NonNullable<Awaited<ReturnType<typeof authnRevokeSession>>>

    export type AuthnRevokeSessionMutationError = AuthnError

    /**
 * @summary Sign out one of the caller's own devices.
 */
export const useAuthnRevokeSession = <TError = AuthnError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRevokeSession>>, TError,{sessionId: string}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnRevokeSession>>,
        TError,
        {sessionId: string},
        TContext
      > => {
      return useMutation(getAuthnRevokeSessionMutationOptions(options));
    }

/**
 * @summary Sign out every one of the caller's sessions except the current one.
 */
export const authnRevokeOtherSessions = (

 signal?: AbortSignal
) => {


      return speedRequest<AuthnRevokeOtherSessionsResponse>(
      {url: `/api/v1/authn/sessions/revoke-others`, method: 'POST', signal
    },
      );
    }



export const getAuthnRevokeOtherSessionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRevokeOtherSessions>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authnRevokeOtherSessions>>, TError,void, TContext> => {

const mutationKey = ['authnRevokeOtherSessions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authnRevokeOtherSessions>>, void> = () => {


          return  authnRevokeOtherSessions()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthnRevokeOtherSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof authnRevokeOtherSessions>>>

    export type AuthnRevokeOtherSessionsMutationError = unknown

    /**
 * @summary Sign out every one of the caller's sessions except the current one.
 */
export const useAuthnRevokeOtherSessions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authnRevokeOtherSessions>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof authnRevokeOtherSessions>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthnRevokeOtherSessionsMutationOptions(options));
    }

/**
 * @summary List the caller's own recent login attempts, successful or not.
 */
export const authnListLoginHistory = (
    params?: AuthnListLoginHistoryParams,
 signal?: AbortSignal
) => {


      return speedRequest<AuthnListLoginHistoryResponse>(
      {url: `/api/v1/authn/login-history`, method: 'GET',
        params, signal
    },
      );
    }




export const getAuthnListLoginHistoryQueryKey = (params?: AuthnListLoginHistoryParams,) => {
    return [
    `/api/v1/authn/login-history`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuthnListLoginHistoryQueryOptions = <TData = Awaited<ReturnType<typeof authnListLoginHistory>>, TError = unknown>(params?: AuthnListLoginHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnListLoginHistory>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthnListLoginHistoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authnListLoginHistory>>> = ({ signal }) => authnListLoginHistory(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authnListLoginHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthnListLoginHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof authnListLoginHistory>>>
export type AuthnListLoginHistoryQueryError = unknown


/**
 * @summary List the caller's own recent login attempts, successful or not.
 */

export function useAuthnListLoginHistory<TData = Awaited<ReturnType<typeof authnListLoginHistory>>, TError = unknown>(
 params?: AuthnListLoginHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authnListLoginHistory>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthnListLoginHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Returns the caller's own inbox rows (recipient_user_id matches the subject seam's caller), newest first, ordered by created_at then id so paging is stable. Messages whose expiry passed are still listed -- expiry governs the unread predicate only (read_at IS NULL AND expiry not passed), never list membership -- but a message that reached its expiry_at renders with the unread affordance already gone, which is what the frontend's per-row state derives from read_at. group filters to one notification group (a type-classification namespace like "appointments"); unknown groups answer an empty list, never an error.
 * @summary List the caller's inbox messages, newest first.
 */
export const notificationListMessages = (
    params?: NotificationListMessagesParams,
 signal?: AbortSignal
) => {


      return speedRequest<NotificationListMessagesResponse>(
      {url: `/api/v1/notifications/messages`, method: 'GET',
        params, signal
    },
      );
    }




export const getNotificationListMessagesQueryKey = (params?: NotificationListMessagesParams,) => {
    return [
    `/api/v1/notifications/messages`, ...(params ? [params] : [])
    ] as const;
    }


export const getNotificationListMessagesQueryOptions = <TData = Awaited<ReturnType<typeof notificationListMessages>>, TError = NotificationError>(params?: NotificationListMessagesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListMessages>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationListMessagesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationListMessages>>> = ({ signal }) => notificationListMessages(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationListMessages>>, TError, TData> & { queryKey: QueryKey }
}

export type NotificationListMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof notificationListMessages>>>
export type NotificationListMessagesQueryError = NotificationError


/**
 * @summary List the caller's inbox messages, newest first.
 */

export function useNotificationListMessages<TData = Awaited<ReturnType<typeof notificationListMessages>>, TError = NotificationError>(
 params?: NotificationListMessagesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListMessages>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotificationListMessagesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * The number of the caller's inbox rows whose read_at is still nil and whose expiry_at -- when set -- has not passed (the module's unread predicate, applied with the server's own clock). A message that is unread but expired does not count, and a read-then-expired message never counts twice.
 * @summary Count the caller's unread inbox messages.
 */
export const notificationGetUnreadCount = (

 signal?: AbortSignal
) => {


      return speedRequest<NotificationUnreadCountResponse>(
      {url: `/api/v1/notifications/messages/unread-count`, method: 'GET', signal
    },
      );
    }




export const getNotificationGetUnreadCountQueryKey = () => {
    return [
    `/api/v1/notifications/messages/unread-count`
    ] as const;
    }


export const getNotificationGetUnreadCountQueryOptions = <TData = Awaited<ReturnType<typeof notificationGetUnreadCount>>, TError = NotificationError>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationGetUnreadCount>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationGetUnreadCountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationGetUnreadCount>>> = ({ signal }) => notificationGetUnreadCount(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationGetUnreadCount>>, TError, TData> & { queryKey: QueryKey }
}

export type NotificationGetUnreadCountQueryResult = NonNullable<Awaited<ReturnType<typeof notificationGetUnreadCount>>>
export type NotificationGetUnreadCountQueryError = NotificationError


/**
 * @summary Count the caller's unread inbox messages.
 */

export function useNotificationGetUnreadCount<TData = Awaited<ReturnType<typeof notificationGetUnreadCount>>, TError = NotificationError>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationGetUnreadCount>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotificationGetUnreadCountQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Applies the same unread predicate as the unread count to the caller's own rows: every message that was still unread becomes read, expired or not (marking read is not gated on expiry, only counting is). The answer names how many rows the call actually flipped, so a client can distinguish "nothing was unread" from "everything was already read" without a second round trip.
 * @summary Mark every unread message of the caller as read.
 */
export const notificationMarkAllMessagesRead = (

 signal?: AbortSignal
) => {


      return speedRequest<NotificationReadAllResponse>(
      {url: `/api/v1/notifications/messages/read-all`, method: 'POST', signal
    },
      );
    }



export const getNotificationMarkAllMessagesReadMutationOptions = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationMarkAllMessagesRead>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationMarkAllMessagesRead>>, TError,void, TContext> => {

const mutationKey = ['notificationMarkAllMessagesRead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationMarkAllMessagesRead>>, void> = () => {


          return  notificationMarkAllMessagesRead()
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationMarkAllMessagesReadMutationResult = NonNullable<Awaited<ReturnType<typeof notificationMarkAllMessagesRead>>>

    export type NotificationMarkAllMessagesReadMutationError = NotificationError

    /**
 * @summary Mark every unread message of the caller as read.
 */
export const useNotificationMarkAllMessagesRead = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationMarkAllMessagesRead>>, TError,void, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationMarkAllMessagesRead>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getNotificationMarkAllMessagesReadMutationOptions(options));
    }

/**
 * Marks the named message read. Idempotent: a message already read answers 204 exactly like a first read. The row must be the caller's own and exist in the caller's tenant; a message id that is unknown, expired into a different tenant, or belongs to another recipient answers 404 -- never another user's message state.
 * @summary Mark one of the caller's messages as read.
 */
export const notificationMarkMessageRead = (
    messageId: string,
 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/notifications/messages/${messageId}/read`, method: 'POST', signal
    },
      );
    }



export const getNotificationMarkMessageReadMutationOptions = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationMarkMessageRead>>, TError,{messageId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationMarkMessageRead>>, TError,{messageId: string}, TContext> => {

const mutationKey = ['notificationMarkMessageRead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationMarkMessageRead>>, {messageId: string}> = (props) => {
          const {messageId} = props ?? {};

          return  notificationMarkMessageRead(messageId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationMarkMessageReadMutationResult = NonNullable<Awaited<ReturnType<typeof notificationMarkMessageRead>>>

    export type NotificationMarkMessageReadMutationError = NotificationError

    /**
 * @summary Mark one of the caller's messages as read.
 */
export const useNotificationMarkMessageRead = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationMarkMessageRead>>, TError,{messageId: string}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationMarkMessageRead>>,
        TError,
        {messageId: string},
        TContext
      > => {
      return useMutation(getNotificationMarkMessageReadMutationOptions(options));
    }

/**
 * The live type directory: every notification type every module of the host declared at bootstrap (the registry's frozen taxonomy -- new types arrive with a new release, never at runtime), each with its group classification, its default channel set for a recipient who has expressed no preference, and whether the recipient may opt out of it at all (the module's non-unsubscribable types carry delivery the host guarantees, such as security or billing receipts). description is the type's copy rendered from the declaring module's own locale bundle in the language the request negotiates (Accept-Language; zh-CN is the default when nothing negotiates), the same catalog delivery renders from -- the directory a client renders must be the copy its recipient would have received.
 * @summary List the notification types this tenant's deployment declares.
 */
export const notificationListTypes = (

 signal?: AbortSignal
) => {


      return speedRequest<NotificationListTypesResponse>(
      {url: `/api/v1/notifications/types`, method: 'GET', signal
    },
      );
    }




export const getNotificationListTypesQueryKey = () => {
    return [
    `/api/v1/notifications/types`
    ] as const;
    }


export const getNotificationListTypesQueryOptions = <TData = Awaited<ReturnType<typeof notificationListTypes>>, TError = NotificationError>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListTypes>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationListTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationListTypes>>> = ({ signal }) => notificationListTypes(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationListTypes>>, TError, TData> & { queryKey: QueryKey }
}

export type NotificationListTypesQueryResult = NonNullable<Awaited<ReturnType<typeof notificationListTypes>>>
export type NotificationListTypesQueryError = NotificationError


/**
 * @summary List the notification types this tenant's deployment declares.
 */

export function useNotificationListTypes<TData = Awaited<ReturnType<typeof notificationListTypes>>, TError = NotificationError>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListTypes>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotificationListTypesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * The caller's effective channel preference for every declared notification type: a type the caller never touched answers with its default channel set, one they opted out of on some channels answers the surviving set. Every declared type appears exactly once, so a client renders one row per type without merging against the type directory. Channel vocabulary is the module's closed set: in_app, email, sms.
 * @summary List the caller's channel preferences per notification type.
 */
export const notificationListPreferences = (

 signal?: AbortSignal
) => {


      return speedRequest<NotificationListPreferencesResponse>(
      {url: `/api/v1/notifications/preferences`, method: 'GET', signal
    },
      );
    }




export const getNotificationListPreferencesQueryKey = () => {
    return [
    `/api/v1/notifications/preferences`
    ] as const;
    }


export const getNotificationListPreferencesQueryOptions = <TData = Awaited<ReturnType<typeof notificationListPreferences>>, TError = NotificationError>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListPreferences>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationListPreferencesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationListPreferences>>> = ({ signal }) => notificationListPreferences(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationListPreferences>>, TError, TData> & { queryKey: QueryKey }
}

export type NotificationListPreferencesQueryResult = NonNullable<Awaited<ReturnType<typeof notificationListPreferences>>>
export type NotificationListPreferencesQueryError = NotificationError


/**
 * @summary List the caller's channel preferences per notification type.
 */

export function useNotificationListPreferences<TData = Awaited<ReturnType<typeof notificationListPreferences>>, TError = NotificationError>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListPreferences>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotificationListPreferencesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Sets whether the caller wants delivery over channel for typeKey. enabled=true restores a channel the caller had opted out of; enabled=false is the opt-out, refused for a type whose unsubscribable flag is false (delivery the host guarantees must not be switched off through a preference). The answer is the type's updated effective state (channels), so a client applying a toggle can overwrite its row from the response without recomputing the merge. Channel vocabulary is the module's closed set: in_app, email, sms.
 * @summary Enable or disable one channel of one notification type for the caller.
 */
export const notificationUpdatePreference = (
    typeKey: string,
    channel: 'in_app' | 'email' | 'sms',
    notificationUpdatePreferenceRequest: NotificationUpdatePreferenceRequest,
 signal?: AbortSignal
) => {


      return speedRequest<NotificationPreference>(
      {url: `/api/v1/notifications/preferences/${typeKey}/${channel}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: notificationUpdatePreferenceRequest, signal
    },
      );
    }



export const getNotificationUpdatePreferenceMutationOptions = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationUpdatePreference>>, TError,{typeKey: string;channel: 'in_app' | 'email' | 'sms';data: NotificationUpdatePreferenceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationUpdatePreference>>, TError,{typeKey: string;channel: 'in_app' | 'email' | 'sms';data: NotificationUpdatePreferenceRequest}, TContext> => {

const mutationKey = ['notificationUpdatePreference'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationUpdatePreference>>, {typeKey: string;channel: 'in_app' | 'email' | 'sms';data: NotificationUpdatePreferenceRequest}> = (props) => {
          const {typeKey,channel,data} = props ?? {};

          return  notificationUpdatePreference(typeKey,channel,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationUpdatePreferenceMutationResult = NonNullable<Awaited<ReturnType<typeof notificationUpdatePreference>>>
    export type NotificationUpdatePreferenceMutationBody = NotificationUpdatePreferenceRequest
    export type NotificationUpdatePreferenceMutationError = NotificationError

    /**
 * @summary Enable or disable one channel of one notification type for the caller.
 */
export const useNotificationUpdatePreference = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationUpdatePreference>>, TError,{typeKey: string;channel: 'in_app' | 'email' | 'sms';data: NotificationUpdatePreferenceRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationUpdatePreference>>,
        TError,
        {typeKey: string;channel: 'in_app' | 'email' | 'sms';data: NotificationUpdatePreferenceRequest},
        TContext
      > => {
      return useMutation(getNotificationUpdatePreferenceMutationOptions(options));
    }

/**
 * The tenant's external-recipient roster, newest first: every address this tenant has put through the module's consent flow. The list is tenant-scoped, not per-user -- a contact belongs to the tenant that verified it, so any identified caller of the tenant sees the roster the tenant's staff manages. A contact row never echoes its address: the plaintext address is PII and the blind-index column would be an offline brute-force surface, so a list consumer sees id, channel, status and timestamps only -- which is all the UI's manage-addresses surface needs (the address itself is shown at the moment of submission, never re-served).
 * @summary List the tenant's verified and pending contacts.
 */
export const notificationListContacts = (

 signal?: AbortSignal
) => {


      return speedRequest<NotificationListContactsResponse>(
      {url: `/api/v1/notifications/contacts`, method: 'GET', signal
    },
      );
    }




export const getNotificationListContactsQueryKey = () => {
    return [
    `/api/v1/notifications/contacts`
    ] as const;
    }


export const getNotificationListContactsQueryOptions = <TData = Awaited<ReturnType<typeof notificationListContacts>>, TError = NotificationError>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListContacts>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationListContactsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationListContacts>>> = ({ signal }) => notificationListContacts(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationListContacts>>, TError, TData> & { queryKey: QueryKey }
}

export type NotificationListContactsQueryResult = NonNullable<Awaited<ReturnType<typeof notificationListContacts>>>
export type NotificationListContactsQueryError = NotificationError


/**
 * @summary List the tenant's verified and pending contacts.
 */

export function useNotificationListContacts<TData = Awaited<ReturnType<typeof notificationListContacts>>, TError = NotificationError>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationListContacts>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotificationListContactsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Registers channel address as a contact of the tenant and starts the module's consent flow: the row is created pending and a verification code is sent to the address (the one message the module's security rule allows to an unverified address -- the verification message itself -- rate limited per tenant and per recipient). The address is normalized before storage (email lowercased, phone to E.164) and encrypted at rest under a blind-index column for exact-match dedupe. Submitting an address already on file (any status) answers the existing contact unchanged and sends nothing -- re-adding is not a resend, resend is its own operation. Codes expire; delivery to the address is refused until the contact is verified, by the delivery pipeline's send-time recheck, never only at enqueue time.
 * @summary Add a contact address to the tenant's roster through double opt-in.
 */
export const notificationCreateContact = (
    notificationCreateContactRequest: NotificationCreateContactRequest,
 signal?: AbortSignal
) => {


      return speedRequest<NotificationContact>(
      {url: `/api/v1/notifications/contacts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: notificationCreateContactRequest, signal
    },
      );
    }



export const getNotificationCreateContactMutationOptions = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationCreateContact>>, TError,{data: NotificationCreateContactRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationCreateContact>>, TError,{data: NotificationCreateContactRequest}, TContext> => {

const mutationKey = ['notificationCreateContact'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationCreateContact>>, {data: NotificationCreateContactRequest}> = (props) => {
          const {data} = props ?? {};

          return  notificationCreateContact(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationCreateContactMutationResult = NonNullable<Awaited<ReturnType<typeof notificationCreateContact>>>
    export type NotificationCreateContactMutationBody = NotificationCreateContactRequest
    export type NotificationCreateContactMutationError = NotificationError

    /**
 * @summary Add a contact address to the tenant's roster through double opt-in.
 */
export const useNotificationCreateContact = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationCreateContact>>, TError,{data: NotificationCreateContactRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationCreateContact>>,
        TError,
        {data: NotificationCreateContactRequest},
        TContext
      > => {
      return useMutation(getNotificationCreateContactMutationOptions(options));
    }

/**
 * Answers the code that was sent to the contact's address. A correct code within its expiry verifies the contact -- the consent record the delivery pipeline's send-time recheck demands -- and answers the verified row; a wrong or expired code leaves the contact pending and answers 400. The contact must be the tenant's own and still pending: resubmitting to one already verified answers 400 just like a wrong code -- wrong, expired, replayed and already-verified are deliberately one answer -- while an unsubscribed or bounced contact answers 409, its address never messaged again. Attempts are rate limited.
 * @summary Verify a pending contact with its code.
 */
export const notificationVerifyContact = (
    contactId: string,
    notificationVerifyContactRequest: NotificationVerifyContactRequest,
 signal?: AbortSignal
) => {


      return speedRequest<NotificationContact>(
      {url: `/api/v1/notifications/contacts/${contactId}/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: notificationVerifyContactRequest, signal
    },
      );
    }



export const getNotificationVerifyContactMutationOptions = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationVerifyContact>>, TError,{contactId: string;data: NotificationVerifyContactRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationVerifyContact>>, TError,{contactId: string;data: NotificationVerifyContactRequest}, TContext> => {

const mutationKey = ['notificationVerifyContact'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationVerifyContact>>, {contactId: string;data: NotificationVerifyContactRequest}> = (props) => {
          const {contactId,data} = props ?? {};

          return  notificationVerifyContact(contactId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationVerifyContactMutationResult = NonNullable<Awaited<ReturnType<typeof notificationVerifyContact>>>
    export type NotificationVerifyContactMutationBody = NotificationVerifyContactRequest
    export type NotificationVerifyContactMutationError = NotificationError

    /**
 * @summary Verify a pending contact with its code.
 */
export const useNotificationVerifyContact = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationVerifyContact>>, TError,{contactId: string;data: NotificationVerifyContactRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationVerifyContact>>,
        TError,
        {contactId: string;data: NotificationVerifyContactRequest},
        TContext
      > => {
      return useMutation(getNotificationVerifyContactMutationOptions(options));
    }

/**
 * Re-issues the verification code of a pending contact -- the flow for a code that expired before it was entered. Only a pending contact can be resent to: an unsubscribed or bounced contact answers 409, its address never messaged again, and one already verified answers 400 like a wrong code (deliberately one answer). The fresh code replaces the old one; rate limited like the original send.
 * @summary Issue a fresh verification code to a still-pending contact.
 */
export const notificationResendContactCode = (
    contactId: string,
 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/notifications/contacts/${contactId}/resend`, method: 'POST', signal
    },
      );
    }



export const getNotificationResendContactCodeMutationOptions = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationResendContactCode>>, TError,{contactId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationResendContactCode>>, TError,{contactId: string}, TContext> => {

const mutationKey = ['notificationResendContactCode'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationResendContactCode>>, {contactId: string}> = (props) => {
          const {contactId} = props ?? {};

          return  notificationResendContactCode(contactId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationResendContactCodeMutationResult = NonNullable<Awaited<ReturnType<typeof notificationResendContactCode>>>

    export type NotificationResendContactCodeMutationError = NotificationError

    /**
 * @summary Issue a fresh verification code to a still-pending contact.
 */
export const useNotificationResendContactCode = <TError = NotificationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationResendContactCode>>, TError,{contactId: string}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationResendContactCode>>,
        TError,
        {contactId: string},
        TContext
      > => {
      return useMutation(getNotificationResendContactCodeMutationOptions(options));
    }
