// Code generated by orval 8.17.0. DO NOT EDIT.
// Source: notes
// The mutator import in this file is rewritten to an explicit
// .js extension by web/scripts/orval-nodenext-fixup.mjs (nodenext
// builds); rerun it after every regeneration.
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { speedRequest } from './runtime.js';
export interface NotesCreateNoteRequest {
  /**
     * The note's placeholder content.
     * @minLength 1
     * @maxLength 4000
     */
  text: string;
}

export interface NotesNote {
  /** Application-generated UUID. */
  id?: string;
  text?: string;
  created_at?: string;
}

export interface NotesListNotesResponse {
  notes?: NotesNote[];
}

export type NotesErrorParams = { [key: string]: unknown };

/**
 * The structured {code, params} error envelope every speed API returns instead of localized text (backend coding standard §6.2; docs/internal/11-cross-cutting.md) -- a client resolves code through its own i18n catalog, populated from this module's Locales() resources for the codes documented in its error index.
 */
export interface NotesError {
  code?: string;
  params?: NotesErrorParams;
}

/**
 * The tenant is always the one tenancy.Middleware already resolved from the request; there is no tenant_id field anywhere on this request, by design (root CLAUDE.md's multi-tenant isolation rule).
 * @summary Create a note for the caller's tenant.
 */
export const notesCreateNote = (
    notesCreateNoteRequest: NotesCreateNoteRequest,
 signal?: AbortSignal
) => {


      return speedRequest<NotesNote>(
      {url: `/api/v1/notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: notesCreateNoteRequest, signal
    },
      );
    }



export const getNotesCreateNoteMutationOptions = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext> => {

const mutationKey = ['notesCreateNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesCreateNote>>, {data: NotesCreateNoteRequest}> = (props) => {
          const {data} = props ?? {};

          return  notesCreateNote(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesCreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesCreateNote>>>
    export type NotesCreateNoteMutationBody = NotesCreateNoteRequest
    export type NotesCreateNoteMutationError = NotesError

    /**
 * @summary Create a note for the caller's tenant.
 */
export const useNotesCreateNote = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof notesCreateNote>>,
        TError,
        {data: NotesCreateNoteRequest},
        TContext
      > => {
      return useMutation(getNotesCreateNoteMutationOptions(options));
    }

/**
 * @summary List every note belonging to the caller's tenant.
 */
export const notesListNotes = (

 signal?: AbortSignal
) => {


      return speedRequest<NotesListNotesResponse>(
      {url: `/api/v1/notes`, method: 'GET', signal
    },
      );
    }




export const getNotesListNotesQueryKey = () => {
    return [
    `/api/v1/notes`
    ] as const;
    }


export const getNotesListNotesQueryOptions = <TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotesListNotesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notesListNotes>>> = ({ signal }) => notesListNotes(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData> & { queryKey: QueryKey }
}

export type NotesListNotesQueryResult = NonNullable<Awaited<ReturnType<typeof notesListNotes>>>
export type NotesListNotesQueryError = unknown


/**
 * @summary List every note belonging to the caller's tenant.
 */

export function useNotesListNotes<TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotesListNotesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
