package org

import "strings"

// The materialized-path algebra, and the invariants that make a prefix scan
// over it return the identical row set on both supported dialects.
//
// # Grammar
//
// A node's Path is the separator-delimited sequence of node ids from the
// tenant root down to and including the node itself, with a LEADING and a
// TRAILING separator:
//
//	root                 "/6f1c.../"
//	child of root        "/6f1c.../a37b.../"
//	grandchild           "/6f1c.../a37b.../90de.../"
//
// The trailing separator is what makes "self and every descendant" a plain
// prefix test regardless of whether ids are fixed-length: "/a/" is not a
// prefix of "/ab/", while without the trailing separator "/a" would be.
//
// # Why a materialized path rather than a closure table or a recursive CTE
//
// A closure table costs O(depth) rows per node and rewrites O(subtree x
// depth) rows on every move, buying ancestor queries that the path already
// answers by splitting a string in Go. A recursive CTE would work on both
// engines today, but portability here is by construction, not by "both
// happen to support it": a LIKE prefix scan needs no such argument, and
// needs no dialect-specific SQL anywhere.
//
// # The dialect-identity proof
//
// The prefix scan is written as db.Where("path LIKE ?", prefix+"%") with the
// prefix built in Go and bound as one parameter. Four properties make the
// two engines agree exactly:
//
//  1. The id alphabet is [0-9a-f-] -- lowercase hex plus the hyphen, which
//     is exactly what uuid.NewString produces. Ids are generated by the
//     application, never by gen_random_uuid().
//
//  2. Neither LIKE metacharacter, '%' nor '_', is in that alphabet. No
//     escaped LIKE is ever needed, so no ESCAPE clause -- whose syntax and
//     default differ between the dialects -- is ever written.
//
//  3. Case divergence is structurally impossible. SQLite's LIKE is
//     ASCII-case-insensitive by default; PostgreSQL's is case-sensitive.
//     That is a real divergence, and the all-lowercase alphabet is what
//     neutralizes it: no two distinct stored paths can differ only by case,
//     so a case-insensitive match and a case-sensitive one select the same
//     rows. CHANGING THE ID SCHEME TO ANYTHING WITH UPPERCASE CHARACTERS
//     (a ULID in Crockford base32, say) BREAKS THIS PROOF and must not be
//     done without re-adjudicating the whole representation.
//
//  4. A move never rewrites paths in SQL. There is no replace() call and no
//     string expression anywhere -- TreeService.Move reads the subtree it
//     already had to read for its cycle check, recomputes each row's path
//     and depth here in Go, and writes the rows back. The only structurally
//     risky operation therefore carries zero dialect-specific SQL.
//
// validateNodeID and validatePath enforce property 1 (and with it 2 and 3)
// rather than assuming it, and path_test.go pins all of it.
const (
	// pathSeparator delimits ids inside a Path and terminates it. It is not
	// in the id alphabet, so it can never appear inside a segment.
	pathSeparator = "/"

	// maxDepth is the deepest Depth value a node may carry. The tenant root
	// sits at depth 0, so a tree holds at most maxDepth+1 levels.
	//
	// The bound is enforced here in Go, not by the path column's width,
	// because SQLite does not enforce VARCHAR(n) under type affinity: a
	// standalone-mode deployment would accept a path the distributed mode's
	// PostgreSQL would reject. Nine levels of 36-character UUIDs occupy
	// 9*37+1 = 334 characters, comfortably inside the VARCHAR(1024) column
	// the migrations declare.
	maxDepth = 8

	// idSegmentLen is how many characters one path segment costs: a
	// 36-character UUID (uuid.NewString's only output shape in this
	// package -- see the dialect-identity proof above) plus the one
	// pathSeparator that follows it.
	idSegmentLen = 37

	// pathColumnWidth mirrors the "path VARCHAR(1024)" column width the
	// postgres and sqlite migrations under migrations/0001_create_org_nodes.sql
	// both declare. It has no way to be checked against the migration files
	// themselves at compile time, so module_test.go's
	// TestModule_WithMaxDepth_CeilingMatchesPathColumnWidth greps them and
	// fails if this ever drifts from what is actually declared there.
	pathColumnWidth = 1024

	// maxDepthCeiling is the highest depth value WithMaxDepth may ever
	// configure -- independent of, and larger than, the maxDepth default
	// above, which only bounds the depth a host gets without configuring
	// one.
	//
	// A path of depth d holds d+1 segments (buildPath's leading separator
	// plus one idSegmentLen per level), so the largest d that still fits in
	// pathColumnWidth solves 1 + idSegmentLen*(d+1) <= pathColumnWidth: d+1
	// <= 27 (1 + 37*27 = 1000), so d <= 26. One level deeper already
	// overflows PostgreSQL's VARCHAR(1024) (1 + 37*28 = 1037) while
	// SQLite's type affinity would silently accept it -- exactly the
	// standalone/distributed divergence maxDepth's own bound above exists
	// to prevent, and precisely what a host-configurable override could
	// reintroduce without this ceiling. See WithMaxDepth.
	maxDepthCeiling = (pathColumnWidth-1)/idSegmentLen - 1

	// maxNameLen is the longest node name, in runes, org accepts. Bounded
	// in Go for the same SQLite type-affinity reason as maxDepth.
	maxNameLen = 200
)

// rootDepth is the Depth of a tenant's root node. Every other node's depth
// is its number of ancestors.
const rootDepth = 0

// buildPath returns the Path of a node with the given id whose parent has
// the given path. An empty parentPath builds a root path.
//
// It does not validate id; callers that accept an id from outside this
// package validate it with validateNodeID first.
func buildPath(parentPath, id string) string {
	if parentPath == "" {
		return pathSeparator + id + pathSeparator
	}
	return subtreePrefix(parentPath) + id + pathSeparator
}

// pathSegments returns path's ids, root first, self last. It returns nil for
// an empty or separator-only path.
func pathSegments(path string) []string {
	trimmed := strings.Trim(path, pathSeparator)
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, pathSeparator)
}

// depthOf returns the Depth a node with this path carries: its number of
// ancestors, so rootDepth for a one-segment path. A path with no segments
// has no depth and yields -1, which no valid node ever holds.
func depthOf(path string) int {
	n := len(pathSegments(path))
	if n == 0 {
		return -1
	}
	return n - 1
}

// subtreePrefix returns the string that, followed by the SQL LIKE wildcard,
// matches path's own node and every node beneath it. Because '%' matches the
// empty string, the match includes the node itself -- "self and descendants",
// which is what every scope query in this module wants.
//
// It appends the trailing separator when path lacks one, so the returned
// prefix always ends at an id boundary and "/a/" can never match "/ab/".
func subtreePrefix(path string) string {
	if strings.HasSuffix(path, pathSeparator) {
		return path
	}
	return path + pathSeparator
}

// isDescendantOf reports whether path lies strictly beneath ancestorPath. A
// node is not its own descendant.
func isDescendantOf(path, ancestorPath string) bool {
	if path == ancestorPath {
		return false
	}
	return strings.HasPrefix(path, subtreePrefix(ancestorPath))
}

// rebasePath returns path with oldAncestorPath's prefix replaced by
// newAncestorPath, for a node being carried along by a subtree move. It
// returns ok=false when path does not actually lie in oldAncestorPath's
// subtree, so a caller can never silently rewrite an unrelated row.
//
// The rewrite happens here, in Go, and never as a SQL replace() call -- see
// property 4 of the dialect-identity proof above.
func rebasePath(path, oldAncestorPath, newAncestorPath string) (string, bool) {
	oldPrefix := subtreePrefix(oldAncestorPath)
	if !strings.HasPrefix(path, oldPrefix) {
		return "", false
	}
	return subtreePrefix(newAncestorPath) + strings.TrimPrefix(path, oldPrefix), true
}

// validNodeIDByte reports whether b is in the id alphabet: lowercase hex
// digits and the hyphen, exactly the characters uuid.NewString emits.
func validNodeIDByte(b byte) bool {
	switch {
	case b >= '0' && b <= '9':
		return true
	case b >= 'a' && b <= 'f':
		return true
	case b == '-':
		return true
	default:
		return false
	}
}

// validateNodeID returns ErrInvalidNodeID unless id is a non-empty string
// drawn entirely from the id alphabet. It is what turns the dialect-identity
// proof's property 1 from an assumption into an enforced invariant: an
// uppercase character, a LIKE metacharacter ('%' or '_'), or a separator
// smuggled into an id would each break the prefix scan's equivalence across
// the two dialects, and each is rejected here.
//
// The id is echoed as a parameter: a node id is an application-generated
// UUID, never PII.
func validateNodeID(id string) error {
	if id == "" {
		return ErrInvalidNodeID.WithParam("node_id", id)
	}
	for i := 0; i < len(id); i++ {
		if !validNodeIDByte(id[i]) {
			return ErrInvalidNodeID.WithParam("node_id", id)
		}
	}
	return nil
}

// validatePath returns ErrInvalidNodeID unless path is a well-formed
// materialized path: leading and trailing separators, at least one segment,
// and every segment a valid node id.
//
// TreeService calls it on paths it reads back from storage before deriving
// anything from them, so a row hand-written into the table (a bad migration,
// a manual fix in production) surfaces as a loud error instead of silently
// producing a prefix that matches the wrong subtree.
func validatePath(path string) error {
	if !strings.HasPrefix(path, pathSeparator) || !strings.HasSuffix(path, pathSeparator) {
		return ErrInvalidNodeID.WithParam("path", path)
	}
	segments := pathSegments(path)
	if len(segments) == 0 {
		return ErrInvalidNodeID.WithParam("path", path)
	}
	for _, segment := range segments {
		if err := validateNodeID(segment); err != nil {
			return ErrInvalidNodeID.WithParam("path", path)
		}
	}
	return nil
}

// validateName returns the trimmed form of name, or an error when it is
// blank or longer than maxNameLen runes. Names are compared for sibling
// uniqueness exactly as stored, so trimming happens once, here, rather than
// leaving " Store" and "Store" as two distinct siblings.
func validateName(name string) (string, error) {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return "", ErrNodeNameRequired
	}
	if len([]rune(trimmed)) > maxNameLen {
		return "", ErrNodeNameTooLong.WithParam("max_length", maxNameLen)
	}
	return trimmed, nil
}
