//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AuthnConfirmTOTPRequest defines model for AuthnConfirmTOTPRequest.
type AuthnConfirmTOTPRequest struct {
	Code string `json:"code"`
}

// AuthnEnrollTOTPResponse defines model for AuthnEnrollTOTPResponse.
type AuthnEnrollTOTPResponse struct {
	ProvisioningURI *string `json:"provisioning_uri,omitempty"`
	Secret          *string `json:"secret,omitempty"`
}

// AuthnError The structured {code, params} error envelope every speed API returns instead of localized text (backend coding standard §6.2) -- a client resolves code through its own i18n catalog, populated from this module's Locales() resources for the codes documented on each operation above.
type AuthnError struct {
	// Code Example: authn.invalid_credentials
	Code   *string                 `json:"code,omitempty"`
	Params *map[string]interface{} `json:"params,omitempty"`
}

// AuthnIdentity defines model for AuthnIdentity.
type AuthnIdentity struct {
	AvatarURL   *string    `json:"avatar_url,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	DisplayName *string    `json:"display_name,omitempty"`
	Email       *string    `json:"email,omitempty"`
	ID          *string    `json:"id,omitempty"`
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	Provider    *string    `json:"provider,omitempty"`
}

// AuthnListIdentitiesResponse defines model for AuthnListIdentitiesResponse.
type AuthnListIdentitiesResponse struct {
	Identities *[]AuthnIdentity `json:"identities,omitempty"`
}

// AuthnListLoginHistoryResponse defines model for AuthnListLoginHistoryResponse.
type AuthnListLoginHistoryResponse struct {
	Attempts *[]AuthnLoginAttempt `json:"attempts,omitempty"`
}

// AuthnListSessionsResponse defines model for AuthnListSessionsResponse.
type AuthnListSessionsResponse struct {
	Sessions *[]AuthnSession `json:"sessions,omitempty"`
}

// AuthnLoginAttempt defines model for AuthnLoginAttempt.
type AuthnLoginAttempt struct {
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	FailureReason *string    `json:"failure_reason,omitempty"`
	ID            *string    `json:"id,omitempty"`
	IP            *string    `json:"ip,omitempty"`
	Method        *string    `json:"method,omitempty"`
	Result        *string    `json:"result,omitempty"`
	UserAgent     *string    `json:"user_agent,omitempty"`
}

// AuthnLoginWithPasswordRequest defines model for AuthnLoginWithPasswordRequest.
type AuthnLoginWithPasswordRequest struct {
	Device *string `json:"device,omitempty"`

	// Identifier An email address or phone number.
	Identifier string `json:"identifier"`
	Password   string `json:"password"`

	// TenantID Requests this tenant's first access token; empty means the caller's first tenant. A request, never a grant.
	TenantID *string `json:"tenant_id,omitempty"`
}

// AuthnLoginWithSMSCodeRequest defines model for AuthnLoginWithSMSCodeRequest.
type AuthnLoginWithSMSCodeRequest struct {
	Code     string  `json:"code"`
	Device   *string `json:"device,omitempty"`
	Phone    string  `json:"phone"`
	TenantID *string `json:"tenant_id,omitempty"`
}

// AuthnPrincipal defines model for AuthnPrincipal.
type AuthnPrincipal struct {
	Amr       *[]string `json:"amr,omitempty"`
	Email     *string   `json:"email,omitempty"`
	SessionID *string   `json:"session_id,omitempty"`
	TenantID  *string   `json:"tenant_id,omitempty"`
	UserID    *string   `json:"user_id,omitempty"`
}

// AuthnRecoveryCodesResponse defines model for AuthnRecoveryCodesResponse.
type AuthnRecoveryCodesResponse struct {
	RecoveryCodes *[]string `json:"recovery_codes,omitempty"`
}

// AuthnRefreshTokenRequest defines model for AuthnRefreshTokenRequest.
type AuthnRefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// AuthnRegisterRequest defines model for AuthnRegisterRequest.
type AuthnRegisterRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Email       *string `json:"email,omitempty"`
	Locale      *string `json:"locale,omitempty"`
	Password    string  `json:"password"`
	Phone       *string `json:"phone,omitempty"`
}

// AuthnRequestSMSCodeRequest defines model for AuthnRequestSMSCodeRequest.
type AuthnRequestSMSCodeRequest struct {
	Phone string `json:"phone"`
}

// AuthnRevokeOtherSessionsResponse defines model for AuthnRevokeOtherSessionsResponse.
type AuthnRevokeOtherSessionsResponse struct {
	RevokedCount *int `json:"revoked_count,omitempty"`
}

// AuthnSession defines model for AuthnSession.
type AuthnSession struct {
	Amr        *[]string  `json:"amr,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Device     *string    `json:"device,omitempty"`
	ID         *string    `json:"id,omitempty"`
	IP         *string    `json:"ip,omitempty"`
	IsCurrent  *bool      `json:"is_current,omitempty"`
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	Status     *string    `json:"status,omitempty"`
	UserAgent  *string    `json:"user_agent,omitempty"`
}

// AuthnSocialAuthorizeResponse defines model for AuthnSocialAuthorizeResponse.
type AuthnSocialAuthorizeResponse struct {
	AuthorizeURL *string `json:"authorize_url,omitempty"`
}

// AuthnSocialCallbackRequest defines model for AuthnSocialCallbackRequest.
type AuthnSocialCallbackRequest struct {
	Code     string  `json:"code"`
	State    string  `json:"state"`
	TenantID *string `json:"tenant_id,omitempty"`
}

// AuthnSocialLoginResponse defines model for AuthnSocialLoginResponse.
type AuthnSocialLoginResponse struct {
	AutoLinked *bool           `json:"auto_linked,omitempty"`
	Bound      *bool           `json:"bound,omitempty"`
	Created    *bool           `json:"created,omitempty"`
	Identity   *AuthnIdentity  `json:"identity,omitempty"`
	Tokens     *AuthnTokenPair `json:"tokens,omitempty"`
	User       *AuthnUser      `json:"user,omitempty"`
}

// AuthnSwitchTenantRequest defines model for AuthnSwitchTenantRequest.
type AuthnSwitchTenantRequest struct {
	TenantID string `json:"tenant_id"`
}

// AuthnTokenPair defines model for AuthnTokenPair.
type AuthnTokenPair struct {
	AccessExpiresAt  *time.Time      `json:"access_expires_at,omitempty"`
	AccessToken      *string         `json:"access_token,omitempty"`
	Principal        *AuthnPrincipal `json:"principal,omitempty"`
	RefreshExpiresAt *time.Time      `json:"refresh_expires_at,omitempty"`

	// RefreshToken Absent when this response did not mint a new refresh token (a tenant switch or a step-up, both of which reuse the caller's existing one).
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// AuthnUser defines model for AuthnUser.
type AuthnUser struct {
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	DisplayName   *string    `json:"display_name,omitempty"`
	Email         *string    `json:"email,omitempty"`
	EmailVerified *bool      `json:"email_verified,omitempty"`
	ID            *string    `json:"id,omitempty"`
	Locale        *string    `json:"locale,omitempty"`
	Phone         *string    `json:"phone,omitempty"`
	PhoneVerified *bool      `json:"phone_verified,omitempty"`
}

// AuthnVerifyStepUpRequest defines model for AuthnVerifyStepUpRequest.
type AuthnVerifyStepUpRequest struct {
	Code string `json:"code"`
}

// AuthnListLoginHistoryParams defines parameters for AuthnListLoginHistory.
type AuthnListLoginHistoryParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AuthnSocialAuthorizeParams defines parameters for AuthnSocialAuthorize.
type AuthnSocialAuthorizeParams struct {
	RedirectURI string `form:"redirect_uri" json:"redirect_uri"`
}

// AuthnLoginWithPasswordJSONRequestBody defines body for AuthnLoginWithPassword for application/json ContentType.
type AuthnLoginWithPasswordJSONRequestBody = AuthnLoginWithPasswordRequest

// AuthnLoginWithSMSCodeJSONRequestBody defines body for AuthnLoginWithSMSCode for application/json ContentType.
type AuthnLoginWithSMSCodeJSONRequestBody = AuthnLoginWithSMSCodeRequest

// AuthnRequestSMSCodeJSONRequestBody defines body for AuthnRequestSMSCode for application/json ContentType.
type AuthnRequestSMSCodeJSONRequestBody = AuthnRequestSMSCodeRequest

// AuthnVerifyStepUpJSONRequestBody defines body for AuthnVerifyStepUp for application/json ContentType.
type AuthnVerifyStepUpJSONRequestBody = AuthnVerifyStepUpRequest

// AuthnConfirmTOTPJSONRequestBody defines body for AuthnConfirmTOTP for application/json ContentType.
type AuthnConfirmTOTPJSONRequestBody = AuthnConfirmTOTPRequest

// AuthnRegisterJSONRequestBody defines body for AuthnRegister for application/json ContentType.
type AuthnRegisterJSONRequestBody = AuthnRegisterRequest

// AuthnSocialCallbackJSONRequestBody defines body for AuthnSocialCallback for application/json ContentType.
type AuthnSocialCallbackJSONRequestBody = AuthnSocialCallbackRequest

// AuthnSwitchTenantJSONRequestBody defines body for AuthnSwitchTenant for application/json ContentType.
type AuthnSwitchTenantJSONRequestBody = AuthnSwitchTenantRequest

// AuthnRefreshTokenJSONRequestBody defines body for AuthnRefreshToken for application/json ContentType.
type AuthnRefreshTokenJSONRequestBody = AuthnRefreshTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AuthnListIdentities List the caller's own bound external identities.
	// (GET /api/v1/authn/identities)
	AuthnListIdentities(w http.ResponseWriter, r *http.Request)
	// AuthnUnbindIdentity Unbind one of the caller's own external identities.
	// (DELETE /api/v1/authn/identities/{identityId})
	AuthnUnbindIdentity(w http.ResponseWriter, r *http.Request, identityID string)
	// AuthnListLoginHistory List the caller's own recent login attempts, successful or not.
	// (GET /api/v1/authn/login-history)
	AuthnListLoginHistory(w http.ResponseWriter, r *http.Request, params AuthnListLoginHistoryParams)
	// AuthnLoginWithPassword Sign in with an email or phone identifier and a password.
	// (POST /api/v1/authn/login/password)
	AuthnLoginWithPassword(w http.ResponseWriter, r *http.Request)
	// AuthnLoginWithSMSCode Sign in with a phone number and the SMS code sent to it.
	// (POST /api/v1/authn/login/sms)
	AuthnLoginWithSMSCode(w http.ResponseWriter, r *http.Request)
	// AuthnRequestSMSCode Request a one-time SMS sign-in code for a phone number.
	// (POST /api/v1/authn/login/sms/request)
	AuthnRequestSMSCode(w http.ResponseWriter, r *http.Request)
	// AuthnLogout Sign out the calling session.
	// (POST /api/v1/authn/logout)
	AuthnLogout(w http.ResponseWriter, r *http.Request)
	// AuthnGetMe Return the caller's own authenticated identity.
	// (GET /api/v1/authn/me)
	AuthnGetMe(w http.ResponseWriter, r *http.Request)
	// AuthnRegenerateRecoveryCodes Discard the caller's recovery codes and issue a fresh batch.
	// (POST /api/v1/authn/mfa/recovery-codes/regenerate)
	AuthnRegenerateRecoveryCodes(w http.ResponseWriter, r *http.Request)
	// AuthnVerifyStepUp Re-prove a second factor for the caller's CURRENT session.
	// (POST /api/v1/authn/mfa/step-up)
	AuthnVerifyStepUp(w http.ResponseWriter, r *http.Request)
	// AuthnConfirmTOTP Confirm a pending TOTP enrollment.
	// (POST /api/v1/authn/mfa/totp/confirm)
	AuthnConfirmTOTP(w http.ResponseWriter, r *http.Request)
	// AuthnEnrollTOTP Start TOTP enrollment for the caller's account.
	// (POST /api/v1/authn/mfa/totp/enroll)
	AuthnEnrollTOTP(w http.ResponseWriter, r *http.Request)
	// AuthnRegister Register a new account.
	// (POST /api/v1/authn/register)
	AuthnRegister(w http.ResponseWriter, r *http.Request)
	// AuthnListSessions List every one of the caller's own sessions (their device list).
	// (GET /api/v1/authn/sessions)
	AuthnListSessions(w http.ResponseWriter, r *http.Request)
	// AuthnRevokeOtherSessions Sign out every one of the caller's sessions except the current one.
	// (POST /api/v1/authn/sessions/revoke-others)
	AuthnRevokeOtherSessions(w http.ResponseWriter, r *http.Request)
	// AuthnRevokeSession Sign out one of the caller's own devices.
	// (DELETE /api/v1/authn/sessions/{sessionId})
	AuthnRevokeSession(w http.ResponseWriter, r *http.Request, sessionID string)
	// AuthnSocialAuthorize Build the authorization URL for a social sign-in channel.
	// (GET /api/v1/authn/social/{provider}/authorize)
	AuthnSocialAuthorize(w http.ResponseWriter, r *http.Request, provider string, params AuthnSocialAuthorizeParams)
	// AuthnSocialCallback Complete a social sign-in or account-binding authorization flow.
	// (POST /api/v1/authn/social/{provider}/callback)
	AuthnSocialCallback(w http.ResponseWriter, r *http.Request, provider string)
	// AuthnSwitchTenant Reissue an access token for a different tenant, reusing the session.
	// (POST /api/v1/authn/tenant/switch)
	AuthnSwitchTenant(w http.ResponseWriter, r *http.Request)
	// AuthnRefreshToken Rotate a refresh token for a new access token.
	// (POST /api/v1/authn/token/refresh)
	AuthnRefreshToken(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthnListIdentities operation middleware
func (siw *ServerInterfaceWrapper) AuthnListIdentities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnListIdentities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnUnbindIdentity operation middleware
func (siw *ServerInterfaceWrapper) AuthnUnbindIdentity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "identityId" -------------
	var identityID string

	err = runtime.BindStyledParameterWithOptions("simple", "identityId", r.PathValue("identityId"), &identityID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "identityId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnUnbindIdentity(w, r, identityID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnListLoginHistory operation middleware
func (siw *ServerInterfaceWrapper) AuthnListLoginHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthnListLoginHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnListLoginHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnLoginWithPassword operation middleware
func (siw *ServerInterfaceWrapper) AuthnLoginWithPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnLoginWithPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnLoginWithSMSCode operation middleware
func (siw *ServerInterfaceWrapper) AuthnLoginWithSMSCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnLoginWithSMSCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnRequestSMSCode operation middleware
func (siw *ServerInterfaceWrapper) AuthnRequestSMSCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnRequestSMSCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnLogout operation middleware
func (siw *ServerInterfaceWrapper) AuthnLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnGetMe operation middleware
func (siw *ServerInterfaceWrapper) AuthnGetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnGetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnRegenerateRecoveryCodes operation middleware
func (siw *ServerInterfaceWrapper) AuthnRegenerateRecoveryCodes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnRegenerateRecoveryCodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnVerifyStepUp operation middleware
func (siw *ServerInterfaceWrapper) AuthnVerifyStepUp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnVerifyStepUp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnConfirmTOTP operation middleware
func (siw *ServerInterfaceWrapper) AuthnConfirmTOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnConfirmTOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnEnrollTOTP operation middleware
func (siw *ServerInterfaceWrapper) AuthnEnrollTOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnEnrollTOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnRegister operation middleware
func (siw *ServerInterfaceWrapper) AuthnRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnListSessions operation middleware
func (siw *ServerInterfaceWrapper) AuthnListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnRevokeOtherSessions operation middleware
func (siw *ServerInterfaceWrapper) AuthnRevokeOtherSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnRevokeOtherSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnRevokeSession operation middleware
func (siw *ServerInterfaceWrapper) AuthnRevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionID string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnRevokeSession(w, r, sessionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnSocialAuthorize operation middleware
func (siw *ServerInterfaceWrapper) AuthnSocialAuthorize(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthnSocialAuthorizeParams

	// ------------- Required query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "redirect_uri", r.URL.Query(), &params.RedirectURI, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirect_uri"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnSocialAuthorize(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnSocialCallback operation middleware
func (siw *ServerInterfaceWrapper) AuthnSocialCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnSocialCallback(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnSwitchTenant operation middleware
func (siw *ServerInterfaceWrapper) AuthnSwitchTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnSwitchTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthnRefreshToken operation middleware
func (siw *ServerInterfaceWrapper) AuthnRefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthnRefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/register", wrapper.AuthnRegister)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/login/password", wrapper.AuthnLoginWithPassword)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/login/sms/request", wrapper.AuthnRequestSMSCode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/login/sms", wrapper.AuthnLoginWithSMSCode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/token/refresh", wrapper.AuthnRefreshToken)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/logout", wrapper.AuthnLogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/authn/social/{provider}/authorize", wrapper.AuthnSocialAuthorize)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/social/{provider}/callback", wrapper.AuthnSocialCallback)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/authn/identities", wrapper.AuthnListIdentities)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/authn/identities/{identityId}", wrapper.AuthnUnbindIdentity)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/mfa/totp/enroll", wrapper.AuthnEnrollTOTP)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/mfa/totp/confirm", wrapper.AuthnConfirmTOTP)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/mfa/recovery-codes/regenerate", wrapper.AuthnRegenerateRecoveryCodes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/mfa/step-up", wrapper.AuthnVerifyStepUp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/tenant/switch", wrapper.AuthnSwitchTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/authn/me", wrapper.AuthnGetMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/authn/sessions", wrapper.AuthnListSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/authn/sessions/{sessionId}", wrapper.AuthnRevokeSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/authn/sessions/revoke-others", wrapper.AuthnRevokeOtherSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/authn/login-history", wrapper.AuthnListLoginHistory)

	return m
}
