#!/usr/bin/env python3
"""Coverage gate for every released module.

Every released Go module -- the 23 go.work entries: the 22 go/* modules
plus the reference app -- must hold its unit-suite statement coverage
at or above an 80% floor and must not let it decline against a recorded
baseline. This script is the mechanism behind that rule: collect (run
`go test -count=1 -coverpkg=./... -coverprofile` from the module
directory and compute the module's exact total statement coverage --
the module's unit suite measured against the whole module, a quantity
the "why" section below defines), store
(tools/coverage-baselines.json, committed, regenerated by --update),
compare (fail when the measured total breaches either bound), and
self-check the baseline file's own health (--selfcheck).

History of the rule. docs/internal/20-quality-and-security.md once drew
the no-uniform-threshold line (a percentage target "breeds meaningless
tests") and asked only that the six foundation modules -- pkgcore,
dbkit, tenancy, rbac, billing, jobs -- keep "coverage must not decline
(against a baseline)". This script shipped exactly that decline
mechanism for those six. The product decision changed in 2026-09: every
released module must hold at least 80% statement coverage, measured
excluding generated files. The no-uniform-threshold argument is
superseded for the lower bound by that decision (docs/internal/20
records the change); the decline gate survives unchanged, so coverage
that merely slides within a high-but-falling band still fails, and a
deliberate re-baseline stays possible above the floor.

Generated files. The quantity the gate compares excludes statements
whose profile path contains ".gen.go" -- the committed oapi-codegen
output every spec-carrying module and the reference app ship. Generated
code is written by a pinned generator, not by a human, so its statements
are not a meaningful test target: including them would let a generator
change (or a spec growing more error paths) move the measured total
independently of the module's hand-written code. The exclusion applies
at both ends -- --update stores exclusion-rule numbers and --check
compares them -- so the baseline file was re-recorded in the same change
that defined the rule: baseline records travel with the change that
defines the quantity.

Why statement coverage of the module's whole unit suite, compared per
module

  * The rule is per module and both floor- and baseline-relative, so
    the measured quantity is one comparable number per module: total
    covered statements / total statements over the module's own unit
    suite (`go test -count=1 -coverpkg=./... -coverprofile ... ./...`
    from the module directory), parsed exactly from the merged
    profile -- never the rounded `go tool cover -func` total, whose
    0.1-point rounding would blind the gate to every change smaller
    than a tenth of a point.
  * The measured quantity is the module suite against the whole
    module, not the per-package sums go test produces by default:
    -coverpkg=./... instruments every module package in every test
    binary, so a block any unit test executes counts toward the
    package it lives in, no matter which package the test runs from.
    Plain per-package instrumentation -- go test's default -- counts
    only what a package's own tests execute, and the unit-test layout
    deliberately puts whole suite classes into directories of their
    own (go/<module>/unittest/ for no-target unit suites, an
    application's flowtests/ for composed assembly flows), which are
    exactly the suites per-package coverage would drop: such a
    directory holds no code of its own, and the packages its tests
    drive from outside the package boundary would score as
    unexecuted. Measuring the suite against the whole module makes
    the number independent of where a suite lives. The merged profile
    of such a run lists each block once per test binary that ran
    (every -coverpkg fragment carries the whole module's blocks), so
    the statement census counts each distinct block once and marks it
    covered when any binary's run executed it -- go test's own merge
    concatenates fragments rather than deduplicating them, and a
    line-by-line census over the concatenation would inflate the
    total by the number of binaries that ran.
  * Measurement is cache-free by construction: the -count=1 flag makes
    go test re-run every package. This is load-bearing, not paranoia --
    go test treats -coverprofile as a cacheable test flag (the stored
    profile is replayed on a cache hit, and CI restores the go build
    cache across runs), so a run without the flag can compare a
    replayed profile against the baseline instead of the current tree
    and fail or pass on cache state alone.
  * The unit suite only: the Docker-backed integration tiers
    (-tags=integration) are not part of a coverage gate on every run.
  * The comparison carries a tolerance applied identically to both
    bounds (effective_tolerance): a measured total more than the
    effective tolerance below the 80.0% floor fails, and one more than
    it below the recorded baseline fails. The statement census is
    fixed for a fixed tree, but which blocks a suite executes is not
    perfectly stable between runs: timing-sensitive tests reach
    different block sets when scheduling shifts. The measured upper
    edge of that jitter is ~0.12 points, in go/authn's MFA
    confirm-race suite -- eight goroutines confirming one pending TOTP
    factor over SQLite, where a losing confirm either hits the
    database's write-lock error or lands a clean zero-row update
    depending on scheduler luck, so the loser-branch statements are
    covered or not by scheduling alone. The main tolerance,
    TOLERANCE_POINTS, is 0.15 points, one notch above that edge.
  * The tolerance is calibrated by the module's statement count,
    because a fixed points-tolerance is not size-invariant: in a small
    module it can sit below one statement's worth of points --
    observability's 424-statement census makes one statement worth
    about 0.24 points, more than the whole 0.15-point band, so a run
    that merely skips a statement of scheduling-sensitive coverage
    would red the gate -- while in a large module the same points
    cover several statements, looser than the intended noise budget.
    effective_tolerance is the wider of TOLERANCE_POINTS and the
    points TOLERANCE_STATEMENTS statements are worth in the module
    under measurement (TOLERANCE_STATEMENTS * 100 / total_statements):
    the 2-statement floor makes the noise budget size-invariant, and
    the main tolerance still governs modules large enough that two
    statements are worth less than it (about 1334 statements and up;
    authn's 3076-statement census keeps 0.15). The cost stays bounded
    either way: the band is about four and a half statements in
    authn's census, while a single untested function of thirty
    statements costs authn about a point -- far below any decline that
    adding code without tests produces. One tolerance, two
    comparisons, one rule. The
    recorded TOOLCHAIN (the short `go version` form) is part of the
    baseline: a check run under a different Go than the baselines were
    recorded with fails with an update instruction -- a Go upgrade
    legitimately moves coverage totals, and the honest response is
    re-measuring, not guessing.

What a breach means and how to respond

  * A PR that adds code without tests drops the total and fails one or
    both comparisons, naming the module, the measured total, the
    effective tolerance it was compared under and the breached bound
    -- the intended signal ("write the tests"). The
    same failure prints the module's largest uncovered blocks and its
    total uncovered statements, so a breach names where the gap sits,
    not only how large it is. A suite that does not merely measure low
    but goes red raises instead, with both captured streams and the
    whole-stream failure extract -- each "--- FAIL: " verdict line
    with the indented test output beneath it -- so the failing test
    and the assertion that says why stay readable from CI even when a
    long tail buries them.
  * A change that deliberately lowers coverage (removing a test whose
    scenario is obsolete, restructuring) fails the decline comparison
    and must say so: re-run with --update to record the new baseline in
    the same change that lowered it, with the reason in the commit
    message. --update cannot record a total that breaches the floor,
    though: the floor is the product decision, not a baseline, so a
    sub-floor measurement fails the floor comparison no matter what the
    baseline file says, and the honest response is adding tests (or
    revisiting the decision, which means editing LOWER_BOUND_PP and
    docs/internal/20 together). The baseline file is a committed
    artifact, so a decline never disappears silently.

Modes

  --check (default): for --module X (or every gated module with
    --all), measure and compare against both bounds. A module outside
    the gated set prints a notice and passes: the gate scope is the
    released modules, and a CI row that names anything else is not a
    module this script has a rule for.
  --update [--module X | --all]: measure and rewrite the baseline file.
    Updates only ever touch gated modules' rows; the file is written
    atomically and its rows sorted. The module's suite must be green
    for the measurement to exist at all (go test fails otherwise), and
    a sub-floor measured total refuses to be recorded (above).
  --selfcheck: verify the baseline file itself -- every row names a
    gated module whose directory exists and carries a go.mod, and
    every gated module has a row. Runs in repo-checks; a dead or
    missing row goes red before any comparison can silently skip.

Usage:
    python3 tools/check_coverage_baseline.py --check --module go/pkgcore
    python3 tools/check_coverage_baseline.py --check --all
    python3 tools/check_coverage_baseline.py --update --all
    python3 tools/check_coverage_baseline.py --selfcheck

Exit codes: 0 = clean / nothing to do; 1 = a comparison failed, a
baseline is stale or missing, or the toolchain moved; 2 = usage error.
Standard library only, Python >= 3.11. Needs a Go toolchain on PATH.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile

# The released modules, mirrored from go.work's use list and from
# docs/internal/20-quality-and-security.md's coverage section (which
# named six foundation modules -- pkgcore, dbkit, tenancy, rbac, billing,
# jobs -- until the 2026-09 decision extended the gate to every module).
# Repo-root-relative module directories. Adding a module means editing
# go.work, this list and the doc together; --selfcheck refuses a
# baseline file that names anything else.
GATED_MODULES = [
    "examples/reference-app",
    "go/admin",
    "go/ai-gateway",
    "go/app",
    "go/authn",
    "go/billing",
    "go/compliance",
    "go/config",
    "go/dbkit",
    "go/integration",
    "go/jobs",
    "go/metering",
    "go/notification",
    "go/observability",
    "go/org",
    "go/pkgcore",
    "go/pki",
    "go/ratelimit",
    "go/rbac",
    "go/saasctl",
    "go/sharing",
    "go/storage",
    "go/tenancy",
]

BASELINE_FILE_NAME = "coverage-baselines.json"
DEFAULT_BASELINE = pathlib.Path(__file__).resolve().parent / BASELINE_FILE_NAME

# The floor every module's measured total must clear, in percentage
# points: the 2026-09 product decision (docs/internal/20). A measured
# total more than the effective tolerance (below) beneath it fails the
# floor comparison, and --update refuses to record one (see the module
# docstring).
LOWER_BOUND_PP = 80.0

# The tolerance band both comparisons carry, calibrated by module size
# (effective_tolerance below). TOLERANCE_POINTS is the main tolerance,
# in percentage points: a measured total more than the effective
# tolerance below the floor -- or below the recorded baseline -- fails,
# a smaller dip being measurement jitter (timing-sensitive tests reach
# different block sets between runs; the observed upper edge is ~0.12
# points, from go/authn's MFA confirm-race suite). TOLERANCE_STATEMENTS
# is the size floor of that band, in statements: the tolerance is never
# tighter than the points this many statements are worth in the module
# under measurement (TOLERANCE_STATEMENTS * 100 / total_statements),
# because a band below one statement's worth cannot absorb a single
# statement of jitter. See the module docstring.
TOLERANCE_POINTS = 0.15
TOLERANCE_STATEMENTS = 2

# The cap on the uncovered-block lines a failed comparison prints: the
# uncovered set of a large module runs to thousands of blocks, which
# would bury the CI log, so the list keeps only the largest
# contributors. The summary line after the list always carries the
# true totals (statements and blocks), so the cap hides size, never
# the aggregate.
DIAGNOSTIC_LIMIT = 30

# The cap, in characters, on each captured stream's retained tail in
# measure_module_coverage's failure message (captured_streams_report).
# A failing go test run prints the failing test's own output -- the
# "--- FAIL: TestName" line and the test's log -- to STDOUT, keeping
# stderr for go's own tooling errors, so the failure message must carry
# both streams or the failing test is invisible from CI. The tail keeps
# a run's closing verdict lines, which print at its end; the
# failure-line extract beside it (below) is what covers a failure line
# a long stream pushes past this window. Bounded so a huge log cannot
# bury the CI output.
STREAM_TAIL_LIMIT = 2000

# The line prefixes a captured stream's failure extract matches
# (captured_streams_report): "--- FAIL: " is the go test per-test
# verdict line -- the one that names a failing test -- while "panic: "
# and "fatal error: " open a test-binary crash report. The extract
# scans the whole stream, so a match beyond the retained tail still
# reaches the report.
STREAM_FAILURE_PREFIXES = ("--- FAIL: ", "panic: ", "fatal error: ")

# The prefix among STREAM_FAILURE_PREFIXES whose following indented
# lines are the failed test's own output: go test prints a failing
# test's buffered log -- the "file_test.go:123: ..." lines carrying
# the assertion text -- beneath its "--- FAIL: TestName" verdict line,
# which is exactly what a coverage red must show (the verdict names
# the test, the indented lines say why it failed) and exactly what a
# long clean tail can push past the retained window. The crash
# prefixes open no such block: "panic: " / "fatal error: " carry their
# message on the same line, and what follows is a goroutine dump, not
# the failing test's log.
STREAM_FAILURE_DETAIL_PREFIX = "--- FAIL: "

# The cap on extracted failure lines per captured stream
# (captured_streams_report): a pathological run (one "panic:" line per
# test in a crash loop, or a failing test logging one message per loop
# iteration) could otherwise fill the failure message with matches.
# The cap governs verdict lines and the detail lines beneath them
# alike. The extract's header names the true match count, so the cap
# hides volume, never the failure set's size.
STREAM_FAILURE_LINE_LIMIT = 40

# The profile format line for one function block:
#   go/pkgcore/kernel.go:12.17,18.2 3 2
# path:startline.startcol,endline.endcol <numstmt> <count>
# The block's position (path plus start/end column coordinates) is
# captured so identical blocks from different profile fragments can be
# recognized (see coverage_from_profile).
PROFILE_BLOCK = re.compile(
    r"^([^:]+):(\d+\.\d+,\d+\.\d+)\s+(\d+)\s+(\d+)\s*$"
)

TOOLCHAIN_RE = re.compile(r"^go version go(\S+)")


def short_toolchain(go_version_output: str) -> str:
    """The short toolchain form recorded beside each baseline
    ('go1.26.8' from 'go version go1.26.8 darwin/arm64')."""
    match = TOOLCHAIN_RE.match(go_version_output.strip())
    if not match:
        raise ValueError(
            "unrecognized go version output: %r" % go_version_output
        )
    return "go" + match.group(1)


def statement_census(
    profile_text: str,
) -> dict[tuple[str, str], tuple[int, bool]]:
    """The profile's function blocks, each distinct block counted once,
    as a (path, position) -> (statements, covered) census.

    A go test run over many packages writes one profile fragment per
    test binary, and under -coverpkg=./... every fragment carries the
    whole module's blocks -- each block appears once per binary that
    ran, with that binary's own count. The census therefore counts
    each distinct block once and marks it covered when any fragment's
    count is above zero: the suite executed it, whatever binary did.
    (A plain per-package run writes disjoint fragments, so no block
    repeats there; the same census applies.)

    Blocks whose path contains ".gen.go" are excluded from the census
    entirely: the committed oapi-codegen output is not a test target
    (see the module docstring)."""
    census: dict[tuple[str, str], tuple[int, bool]] = {}
    for line in profile_text.splitlines():
        match = PROFILE_BLOCK.match(line)
        if match is None:
            continue
        path, position, statements, count = match.groups()
        if ".gen.go" in path:
            continue
        statements = int(statements)
        count = int(count)
        key = (path, position)
        if key in census:
            statements, covered = census[key]
            census[key] = (statements, covered or count > 0)
        else:
            census[key] = (statements, count > 0)
    return census


def census_statements(
    census: dict[tuple[str, str], tuple[int, bool]],
) -> int:
    """The census's statement total -- the module's size, read off the
    same census as the coverage total, and the input the tolerance is
    calibrated against (effective_tolerance)."""
    return sum(statements for statements, _ in census.values())


def coverage_from_census(
    census: dict[tuple[str, str], tuple[int, bool]],
) -> float:
    """Total statement coverage percent from a statement census,
    computed exactly: covered statements (count > 0) over all
    statements across every block the census carries. Unrounded, so a
    comparison against a stored baseline is not quantized by the
    0.1-point rounding `go tool cover -func` applies to its output."""
    total = census_statements(census)
    covered = sum(
        statements
        for statements, was_covered in census.values()
        if was_covered
    )
    if total == 0:
        return 100.0
    return 100.0 * covered / total


def coverage_from_profile(profile_text: str) -> float:
    """coverage_from_census over the profile's own census.

    The blocks come from statement_census, the same census the failure
    diagnostics read, so the number a comparison fails on and the
    uncovered list printed beside it cannot disagree about what
    "uncovered" means."""
    return coverage_from_census(statement_census(profile_text))


def line_span(position: str) -> str:
    """A profile position's line span, for the failure diagnostics:
    '12.17,18.2' -> '12-18'."""
    start, end = position.split(",")
    return "%s-%s" % (start.split(".")[0], end.split(".")[0])


def uncovered_blocks_from_profile(
    profile_text: str,
) -> list[tuple[str, str, int]]:
    """The profile's uncovered blocks -- blocks no fragment ever
    executed, deduplicated and .gen.go-filtered exactly as the census
    does -- as (path, position, statements) triples sorted by
    statement count descending, ties by path then position, so a
    failed comparison names its largest gaps first and equal-size
    gaps keep a stable order."""
    census = statement_census(profile_text)
    blocks = [
        (path, position, statements)
        for (path, position), (statements, covered) in census.items()
        if not covered
    ]
    blocks.sort(key=lambda block: (-block[2], block[0], block[1]))
    return blocks


def uncovered_diagnostics(module_dir: str, profile_text: str) -> list[str]:
    """The diagnostic lines a failed comparison prints: the module's
    largest uncovered blocks, up to DIAGNOSTIC_LIMIT of them, one per
    line in the 'file:startLine-endLine (N stmts)' form, followed by a
    summary line carrying the true uncovered totals. Naming the blocks
    is what lets a breach be located -- an environment-specific gap
    between two runs shows up as a different uncovered set, which a
    bare percentage cannot show."""
    blocks = uncovered_blocks_from_profile(profile_text)
    lines = [
        "check_coverage_baseline: %s: uncovered blocks (showing %d of "
        "%d, largest first):"
        % (module_dir, min(len(blocks), DIAGNOSTIC_LIMIT), len(blocks))
    ]
    for path, position, statements in blocks[:DIAGNOSTIC_LIMIT]:
        lines.append(
            "%s:%s (%d stmts)" % (path, line_span(position), statements)
        )
    lines.append(
        "check_coverage_baseline: %s: %d uncovered statements in %d blocks"
        % (
            module_dir,
            sum(statements for _, _, statements in blocks),
            len(blocks),
        )
    )
    return lines


def effective_tolerance(total_statements: int) -> float:
    """The tolerance band for a module of this statement count, in
    percentage points: the wider of TOLERANCE_POINTS and the points
    TOLERANCE_STATEMENTS statements are worth over the module's census
    (TOLERANCE_STATEMENTS * 100 / total_statements).

    A fixed points-tolerance is not size-invariant (see the module
    docstring): in a small module it can sit below one statement's
    worth of points, so a run that merely skips a statement of
    scheduling-sensitive coverage would red the gate, while in a large
    module it covers several statements, looser than the intended
    noise budget. The statement floor makes the budget size-invariant,
    and the main tolerance governs the modules large enough that two
    statements are worth less than it."""
    if total_statements <= 0:
        return TOLERANCE_POINTS
    return max(
        TOLERANCE_POINTS,
        TOLERANCE_STATEMENTS * 100.0 / total_statements,
    )


def comparison_failures(
    measured: float,
    baseline: float | None,
    total_statements: int,
    floor: float = LOWER_BOUND_PP,
) -> list[str]:
    """The breached bounds for one measured total, in a fixed order
    (floor first, then the recorded baseline); empty means pass. Both
    comparisons share the same tolerance semantics: a measured total
    more than effective_tolerance(total_statements) below the bound
    fails it, and the failure text names the effective tolerance and
    the census it was calibrated against."""
    tolerance = effective_tolerance(total_statements)
    failures = []
    if measured + tolerance < floor:
        failures.append(
            "measured %.4f%% sits more than the effective %.4f-point "
            "tolerance of the module's %d-statement census (the wider "
            "of %.2f points and %d statements' worth) below the %.1f%% "
            "floor (the product decision; the response is adding tests "
            "-- --update cannot waive it)"
            % (
                measured,
                tolerance,
                total_statements,
                TOLERANCE_POINTS,
                TOLERANCE_STATEMENTS,
                floor,
            )
        )
    if baseline is not None and measured + tolerance < baseline:
        failures.append(
            "measured %.4f%% sits more than the effective %.4f-point "
            "tolerance of the module's %d-statement census (the wider "
            "of %.2f points and %d statements' worth) below the "
            "recorded baseline %.4f%% -- add tests, or record a "
            "deliberate decline with --update (with the reason in the "
            "commit message)"
            % (
                measured,
                tolerance,
                total_statements,
                TOLERANCE_POINTS,
                TOLERANCE_STATEMENTS,
                baseline,
            )
        )
    return failures


@dataclasses.dataclass(frozen=True)
class ModuleMeasurement:
    """One module's measurement: the exact total the gate compares, the
    module's statement census size -- the input its tolerance is
    calibrated against -- plus the profile text the two were computed
    from, so a failed comparison can list the uncovered blocks behind
    the total."""

    total: float
    total_statements: int
    profile_text: str


def failure_lines_from_stream(text: str) -> list[str]:
    """The stream's failure lines, in source order, exact duplicates
    collapsed: every line starting with STREAM_FAILURE_PREFIXES -- the
    go test per-test "--- FAIL: TestName" verdict and the "panic: " /
    "fatal error: " lines opening a test-binary crash report -- plus
    the indented test-output lines that follow a verdict line
    (STREAM_FAILURE_DETAIL_PREFIX): go test prints the failed test's
    buffered log there, so the assertion text saying WHY the test
    failed travels with the verdict line that names it. A detail block
    ends at the first line that is not indented -- the next verdict or
    crash line, a package verdict, the stream's trailer. Scanning the
    whole stream is what lets captured_streams_report keep the failure
    line when a long clean tail pushes it past the retained window."""
    seen: set[str] = set()
    extracted = []
    in_detail_block = False
    for line in text.splitlines():
        if line.startswith(STREAM_FAILURE_PREFIXES):
            in_detail_block = line.startswith(STREAM_FAILURE_DETAIL_PREFIX)
            keep = True
        elif in_detail_block and line.startswith((" ", "\t")):
            keep = True
        else:
            in_detail_block = False
            keep = False
        if keep and line not in seen:
            seen.add(line)
            extracted.append(line)
    return extracted


def captured_streams_report(stdout: str, stderr: str) -> str:
    """The labeled, bounded failure extract and tails for
    measure_module_coverage's failure message.

    `go test` prints a failing test's own output -- the "--- FAIL:
    TestName" line and the test's log -- to stdout, keeping stderr for
    go's own tooling errors; a message built from stderr alone left a
    red test run's failure body empty and the failing test unnameable
    from CI. Each stream contributes up to two labeled parts: first its
    failure lines extracted from the whole stream
    (failure_lines_from_stream -- each verdict line with the indented
    test output beneath it, so the failing assertion's own text
    travels with the test's name -- capped at
    STREAM_FAILURE_LINE_LIMIT with the true match count in the
    header), then the last STREAM_TAIL_LIMIT characters of the stream
    itself (a run's verdict lines print at its end). The extract is
    what guarantees the failure line survives truncation -- go test
    prints the verdict line at the point the test failed, so a long
    run's clean tail can push it beyond the tail window -- and the
    tail keeps showing how the run ended. A stream that captured
    nothing shows as "empty", and one with no failure line contributes
    only its tail -- so which stream carried the failure, and how much
    of it a truncated view shows, is readable from the message alone."""
    lines = []
    for name, text in (("stdout", stdout), ("stderr", stderr)):
        if text.strip() == "":
            lines.append("%s (empty)" % name)
            continue
        failures = failure_lines_from_stream(text)
        if failures:
            shown = failures[:STREAM_FAILURE_LINE_LIMIT]
            lines.append(
                "%s failure lines (showing %d of %d):\n%s"
                % (name, len(shown), len(failures), "\n".join(shown))
            )
        tail = text[-STREAM_TAIL_LIMIT:]
        if len(tail) < len(text):
            label = "%s (last %d of %d chars)" % (name, len(tail), len(text))
        else:
            label = "%s (%d chars)" % (name, len(text))
        lines.append("%s:\n%s" % (label, tail.rstrip("\n")))
    return "\n".join(lines)


def measure_module_coverage(
    root: pathlib.Path, module_dir: str
) -> ModuleMeasurement:
    """Run the module's unit suite under -coverprofile and return its
    measurement: the exact total statement coverage percent -- the
    module suite measured against the whole module -- the module's
    statement census size, which calibrates the comparison's tolerance,
    plus the profile text behind both, so a failed comparison can print
    the uncovered blocks (the profile temp file is gone by then).
    -coverpkg=./...
    instruments every module package in every test binary, so
    execution that crosses a package boundary counts toward the
    package whose code it runs: a suite that lives in a directory of
    its own (go/<module>/unittest/ for no-target unit suites, an
    application's flowtests/ for assembly flows) and drives another
    package from outside would contribute no coverage to that package
    at all under per-package instrumentation -- go test's default --
    which instruments only the package under test. The merged profile
    is written to a temp file inside the module
    directory (go test names profile paths relative to its working
    directory, but the parse only needs the statement census, so an
    absolute temp path works too) and removed afterwards. A failing
    suite fails the measurement -- a baseline can only ever be recorded
    against a green tree -- and the RuntimeError carries both captured
    streams (captured_streams_report), so the failing test's name, which
    go test prints to stdout, stays legible from CI.

    -count=1 forces every package to run for real. Without it the run
    is not a measurement: go test treats -coverprofile as a cacheable
    test flag and replays a previously stored profile on a cache hit
    (locally, and in CI whenever the restored build cache holds one),
    so the gate would compare cache state against the baseline rather
    than the tree."""
    module_path = root / module_dir
    if not (module_path / "go.mod").is_file():
        raise FileNotFoundError(
            "module %s has no go.mod at %s" % (module_dir, module_path)
        )
    fd, profile = tempfile.mkstemp(
        prefix="speed-cov-", suffix=".out", dir=str(module_path)
    )
    os.close(fd)
    try:
        proc = subprocess.run(
            [
                "go",
                "test",
                "-count=1",
                "-coverpkg=./...",
                "-coverprofile=%s" % profile,
                "./...",
            ],
            cwd=module_path,
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                "go test -coverprofile failed in %s (exit %d):\n%s"
                % (
                    module_dir,
                    proc.returncode,
                    captured_streams_report(proc.stdout, proc.stderr),
                )
            )
        profile_text = pathlib.Path(profile).read_text(encoding="utf-8")
    finally:
        pathlib.Path(profile).unlink(missing_ok=True)
    census = statement_census(profile_text)
    return ModuleMeasurement(
        coverage_from_census(census),
        census_statements(census),
        profile_text,
    )


def load_baselines(path: pathlib.Path) -> dict:
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def save_baselines(path: pathlib.Path, data: dict) -> None:
    text = json.dumps(
        data, indent=2, sort_keys=True
    ) + "\n"
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def current_toolchain() -> str:
    proc = subprocess.run(
        ["go", "version"], capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        raise RuntimeError("go version failed: %s" % proc.stderr)
    return short_toolchain(proc.stdout)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        default=True,
        help="measure and compare against the floor and the stored "
        "baseline (default)",
    )
    mode.add_argument(
        "--update", action="store_true", help="measure and record baselines"
    )
    mode.add_argument(
        "--selfcheck",
        action="store_true",
        help="verify the baseline file's rows against the gated set",
    )
    parser.add_argument(
        "--module",
        default=None,
        help="module directory (go/pkgcore, examples/reference-app); "
        "--all selects the gated set",
    )
    parser.add_argument(
        "--all", action="store_true", help="act on every gated module"
    )
    parser.add_argument(
        "--root",
        default=None,
        help="repository root (default: the tools/ directory's parent)",
    )
    args = parser.parse_args(argv)

    root = (
        pathlib.Path(args.root).resolve()
        if args.root
        else pathlib.Path(__file__).resolve().parent.parent
    )
    baseline_path = DEFAULT_BASELINE
    if args.root:
        baseline_path = root / "tools" / BASELINE_FILE_NAME

    if args.selfcheck:
        data = load_baselines(baseline_path)
        rows = data.get("baselines", {}) if isinstance(data, dict) else {}
        toolchain = data.get("toolchain") if isinstance(data, dict) else None
        problems: list[str] = []
        gated = set(GATED_MODULES)
        for module_dir in sorted(rows):
            if module_dir not in gated:
                problems.append(
                    "baseline row %s is not a gated module (the released-"
                    "module set names %s)"
                    % (module_dir, ", ".join(sorted(gated)))
                )
            elif not (root / module_dir / "go.mod").is_file():
                problems.append(
                    "baseline row %s has no go.mod at %s"
                    % (module_dir, root / module_dir)
                )
        for module_dir in GATED_MODULES:
            if module_dir not in rows:
                problems.append(
                    "gated module %s has no baseline row -- record one "
                    "with --update" % module_dir
                )
        if toolchain != current_toolchain():
            problems.append(
                "baselines recorded under %r, this toolchain is %r -- "
                "re-record with --update"
                % (toolchain, current_toolchain())
            )
        if problems:
            for problem in problems:
                print("check_coverage_baseline: %s" % problem, file=sys.stderr)
            return 1
        print(
            "coverage-baselines.json: rows match the gated set "
            "(%d modules)" % len(GATED_MODULES)
        )
        return 0

    selected: list[str]
    if args.module is not None:
        if args.all:
            print("--module and --all are mutually exclusive", file=sys.stderr)
            return 2
        selected = [args.module]
    elif args.all:
        selected = list(GATED_MODULES)
    else:
        print("one of --module X or --all is required", file=sys.stderr)
        return 2

    toolchain = current_toolchain()
    data = load_baselines(baseline_path)
    rows = data.get("baselines", {}) if isinstance(data, dict) else {}
    recorded_toolchain = (
        data.get("toolchain") if isinstance(data, dict) else None
    )

    if args.update:
        measured_by_module: dict[str, float] = {}
        refusals: list[str] = []
        for module_dir in selected:
            if module_dir not in GATED_MODULES:
                print(
                    "update refuses %s: the baseline gate covers the "
                    "released modules only (%d of them: go.work's use "
                    "list plus examples/reference-app)"
                    % (module_dir, len(GATED_MODULES)),
                    file=sys.stderr,
                )
                return 1
            measurement = measure_module_coverage(root, module_dir)
            measured_by_module[module_dir] = measurement.total
            if comparison_failures(
                measurement.total,
                baseline=None,
                total_statements=measurement.total_statements,
            ):
                refusals.append(
                    "update refuses to record %s at %.4f%%: the measured "
                    "total breaches the %.1f%% floor, and the floor is "
                    "the product decision -- not a baseline -- so the "
                    "response is adding tests, not re-recording"
                    % (module_dir, measurement.total, LOWER_BOUND_PP)
                )
        if refusals:
            for refusal in refusals:
                print(
                    "check_coverage_baseline: %s" % refusal, file=sys.stderr
                )
            return 1
        for module_dir, total in measured_by_module.items():
            rows[module_dir] = round(total, 6)
            print("recorded %s: %.4f%%" % (module_dir, total))
        save_baselines(
            baseline_path,
            {"toolchain": toolchain, "baselines": rows},
        )
        return 0

    # --check (default)
    failures = 0
    for module_dir in selected:
        if module_dir not in GATED_MODULES:
            print(
                "%s: outside the coverage gate (the released modules: "
                "go.work's use list plus examples/reference-app) -- "
                "nothing to compare"
                % module_dir
            )
            continue
        if module_dir not in rows:
            print(
                "check_coverage_baseline: %s has no baseline row -- record "
                "one with --update" % module_dir,
                file=sys.stderr,
            )
            failures += 1
            continue
        if recorded_toolchain != toolchain:
            print(
                "check_coverage_baseline: %s baseline recorded under %r, "
                "measured under %r -- re-record with --update before "
                "comparing" % (module_dir, recorded_toolchain, toolchain),
                file=sys.stderr,
            )
            failures += 1
            continue
        measurement = measure_module_coverage(root, module_dir)
        baseline = rows[module_dir]
        reasons = comparison_failures(
            measurement.total, baseline, measurement.total_statements
        )
        if reasons:
            for reason in reasons:
                print(
                    "check_coverage_baseline: FAIL %s: %s"
                    % (module_dir, reason),
                    file=sys.stderr,
                )
            for line in uncovered_diagnostics(
                module_dir, measurement.profile_text
            ):
                print(line, file=sys.stderr)
            failures += 1
        else:
            print(
                "%s: %.4f%% (floor %.1f%%, baseline %.4f%%)"
                % (module_dir, measurement.total, LOWER_BOUND_PP, baseline)
            )
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
