// Code generated by orval 8.17.0. DO NOT EDIT.
// Source: reference-app
// The mutator import in this file is rewritten to an explicit
// .js extension by web/scripts/orval-nodenext-fixup.mjs (nodenext
// builds); rerun it after every regeneration.
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { speedRequest } from './runtime.js';
export interface NotesCreateNoteRequest {
  /**
     * The note's placeholder content.
     * @minLength 1
     * @maxLength 4000
     */
  text: string;
}

export interface NotesNote {
  /** Application-generated UUID. */
  id?: string;
  text?: string;
  created_at?: string;
}

export interface NotesListNotesResponse {
  notes?: NotesNote[];
}

export type NotesErrorParams = { [key: string]: unknown };

/**
 * The structured {code, params} error envelope every speed API returns instead of localized text: code is a stable machine-readable identifier naming exactly one failure, and params carries the structured per-code details when the failure has any. The server never renders a message -- a client maps each code to its own locale's text.
 */
export interface NotesError {
  code?: string;
  params?: NotesErrorParams;
}

/**
 * The create route's request body.
 */
export interface CasesCreateCaseRequest {
  /**
     * The patient's display name as the clinic entered it at intake. Required, length-bounded in the application (SQLite does not enforce a VARCHAR length limit, so the check lives in the service).
     * @minLength 1
     * @maxLength 200
     */
  patient_name: string;
  /**
     * The optional clinic-given identifier for the patient (a chart number, an internal reference). An absent or empty value means the clinic gave none.
     * @maxLength 64
     */
  patient_ref?: string;
  /**
     * The case's initial photos, in attachment order: references to already-uploaded go/storage objects of the caller's tenant. Optional -- an absent or empty list creates a case with no photos yet. Each entry must be a non-empty object id, unique within the list and not already attached to another case of the same tenant.
     * @maxItems 50
     * @items.minLength 1
     */
  photo_object_ids?: string[];
}

/**
 * One photo of a case, as a case read answers it.
 */
export interface CasesPhoto {
  /** The referenced go/storage photo object's id -- the value that feeds the smile-simulation surface's per-photo enumeration. */
  object_id: string;
}

/**
 * A case as the create answer, the list entries and the detail answer all render it -- one shape a P3 view renders with one component.
 */
export interface CasesCase {
  /** The case's application-generated id. */
  id: string;
  /** The patient's display name as the clinic entered it. */
  patient_name: string;
  /** The clinic-given patient reference; empty means the clinic gave none. */
  patient_ref: string;
  /** The user id of the staff member who created the case, as the host's SubjectResolver seam attributed the create request. Recorded on the row for the case's history; the clinic's case list is NOT filtered by it (every member of the tenant sees every case of the tenant). */
  creator_user_id: string;
  /** When the case was created, whole seconds, UTC. */
  created_at: string;
  /** The case's photos in attachment order. Always present -- an empty list for a case whose photos arrive later. */
  photos: CasesPhoto[];
}

/**
 * The list route's 200 answer.
 */
export interface CasesListResponse {
  /** The caller's tenant's cases, newest first. */
  cases: CasesCase[];
}

/**
 * The photo-upload route's request body.
 */
export interface CasesUploadPhotoRequest {
  /**
     * The photo's bytes, base64-encoded (standard alphabet with padding, as the browser's FileReader data URL carries them). The decoded bytes must be non-empty and at most the surface's upload bound; storage's own probe of the stored bytes decides whether they are an acceptable image.
     * @minLength 1
     */
  content_base64: string;
}

/**
 * The photo-upload route's 201 answer.
 */
export interface CasesUploadPhotoResponse {
  /** The completed go/storage photo object's id -- the value a case create's photo_object_ids list references to attach the photo to a case. */
  object_id: string;
}

/**
 * The photo-content route's 200 answer.
 */
export interface CasesPhotoContent {
  /** The media type storage's probe assigned to the bytes at complete time (the sanitized form), e.g. image/jpeg. */
  media_type: string;
  /** The photo's stored bytes, base64-encoded -- the value a case view decodes into a blob URL it renders. */
  content_base64: string;
}

export type CasesErrorParams = { [key: string]: unknown };

/**
 * The structured {code, params} error envelope every speed API returns instead of localized text: code is a stable machine-readable identifier naming exactly one failure, and params carries the structured per-code details when the failure has any. The server never renders a message -- a client maps each code to its own locale's text.
 */
export interface CasesError {
  code?: string;
  params?: CasesErrorParams;
}

/**
 * The character of the simulated smile. Defaults to natural when omitted.
 */
export type SmilesimSimulationOptionsSmileStyle = typeof SmilesimSimulationOptionsSmileStyle[keyof typeof SmilesimSimulationOptionsSmileStyle];


export const SmilesimSimulationOptionsSmileStyle = {
  subtle: 'subtle',
  natural: 'natural',
  bright: 'bright',
} as const;

/**
 * The tooth color the simulated smile is asked to show. Defaults to natural when omitted.
 */
export type SmilesimSimulationOptionsToothShade = typeof SmilesimSimulationOptionsToothShade[keyof typeof SmilesimSimulationOptionsToothShade];


export const SmilesimSimulationOptionsToothShade = {
  natural: 'natural',
  white: 'white',
  'ultra-white': 'ultra-white',
} as const;

/**
 * One simulation's parameterized option set, shared by the simulate route's request body and by every response that echoes the effective options a simulation was generated with.
 */
export interface SmilesimSimulationOptions {
  /** The character of the simulated smile. Defaults to natural when omitted. */
  smile_style?: SmilesimSimulationOptionsSmileStyle;
  /** The tooth color the simulated smile is asked to show. Defaults to natural when omitted. */
  tooth_shade?: SmilesimSimulationOptionsToothShade;
  /**
     * How strongly the transformation moves the photo toward the requested smile: the lower bound is exclusive (0 is a billed no-op and is refused) and 1 is the complete simulated smile. Defaults to full strength when omitted.
     * @maximum 1
     * @exclusiveMinimum 0
     */
  strength?: number;
}

/**
 * The simulate route's request body. Every options field is a pointer-shaped optional: an omitted field inherits the service's documented default, while an explicitly present field -- including an out-of-range strength of 0 -- is passed through verbatim and refused by the service's own validation rather than silently replaced by a default.
 */
export interface SmilesimSimulateRequest {
  /**
     * The completed go/storage object id of the patient photo to simulate.
     * @minLength 1
     */
  photo_object_id: string;
  /** The user id of the recipient to notify once the job reaches a terminal status. Omitted (or empty) enqueues the job with no notification. */
  recipient_user_id?: string;
  options?: SmilesimSimulationOptions;
}

/**
 * The simulate route's 202 answer: a reference to the async job, which has not run yet.
 */
export interface SmilesimJobRef {
  /** The enqueued go/jobs job's id -- the value the job-status route's {jobID} path parameter takes. */
  job_id: string;
}

/**
 * The real vendor usage a succeeded job recorded.
 */
export interface SmilesimUsage {
  /** How many images the vendor generated for the job. */
  image_count: number;
  /** The inference step count the vendor reported. */
  steps: number;
  /** The resolution tier the vendor generated at (its normalized size string). */
  resolution_tier: string;
}

/**
 * The job's live go/jobs status.
 */
export type SmilesimJobStatusStatus = typeof SmilesimJobStatusStatus[keyof typeof SmilesimJobStatusStatus];


export const SmilesimJobStatusStatus = {
  pending: 'pending',
  running: 'running',
  retrying: 'retrying',
  succeeded: 'succeeded',
  dead_letter: 'dead_letter',
  cancelled: 'cancelled',
} as const;

/**
 * The job-status route's 200 answer for one job.
 */
export interface SmilesimJobStatus {
  /** The job's live go/jobs status. */
  status: SmilesimJobStatusStatus;
  /** The effective options the job was generated with, present when a durable per-photo record exists for it. */
  options?: SmilesimSimulationOptions;
  /** The generated image's go/storage object id, present once the job has succeeded. */
  output_object_id?: string;
  /** The real vendor usage the job recorded, present once it has succeeded. */
  usage?: SmilesimUsage;
  /** The job's recorded failure message, present when the job carries one (dead-lettered, cancelled after a failed attempt, or retrying). */
  error?: string;
}

/**
 * The job's live status, read from the queue at call time -- never a snapshot stored by the service, so an enumeration always reflects what a job-status poll would answer right now.
 */
export type SmilesimSimulationStatus = typeof SmilesimSimulationStatus[keyof typeof SmilesimSimulationStatus];


export const SmilesimSimulationStatus = {
  pending: 'pending',
  running: 'running',
  retrying: 'retrying',
  succeeded: 'succeeded',
  dead_letter: 'dead_letter',
  cancelled: 'cancelled',
} as const;

/**
 * One simulation in the per-photo enumeration.
 */
export interface SmilesimSimulation {
  /** The generation job's id. */
  job_id: string;
  /** The go/storage object id of the photo the simulation was generated from -- the enumeration's grouping key, echoed per entry for a caller rendering a row on its own. */
  photo_object_id: string;
  /** The effective option set that produced this simulation. */
  options: SmilesimSimulationOptions;
  /** The job's live status, read from the queue at call time -- never a snapshot stored by the service, so an enumeration always reflects what a job-status poll would answer right now. */
  status: SmilesimSimulationStatus;
  /** When the generation was requested, whole seconds, UTC. */
  created_at: string;
  /** The generated image's go/storage object id, present only when the job has succeeded and its result names one. */
  output_object_id?: string;
  /** The job's recorded failure message, present only when the job carries one. */
  error?: string;
}

/**
 * The per-photo enumeration route's 200 answer.
 */
export interface SmilesimPhotoSimulations {
  /** The photo's simulations, newest first. */
  simulations: SmilesimSimulation[];
}

/**
 * The simulation-content read's 200 answer for one generated image.
 */
export interface SmilesimSimulationContent {
  /** The media type go/storage's probe assigned to the stored bytes at complete time. */
  media_type: string;
  /** The stored bytes, base64-encoded -- the same JSON-carried transport the cases surface's photo-content route uses. */
  content_base64: string;
}

export type SmilesimErrorParams = { [key: string]: unknown };

/**
 * The structured {code, params} error envelope every speed API returns instead of localized text: code is a stable machine-readable identifier naming exactly one failure, and params carries the structured per-code details when the failure has any. The server never renders a message -- a client maps each code to its own locale's text.
 */
export interface SmilesimError {
  code?: string;
  params?: SmilesimErrorParams;
}

/**
 * The tenant is always the one tenancy.Middleware already resolved from the request; there is no tenant_id field anywhere on this request -- the tenant comes from the resolved request context, never from anything the caller sends.
 * @summary Create a note for the caller's tenant.
 */
export const notesCreateNote = (
    notesCreateNoteRequest: NotesCreateNoteRequest,
 signal?: AbortSignal
) => {


      return speedRequest<NotesNote>(
      {url: `/api/v1/notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: notesCreateNoteRequest, signal
    },
      );
    }



export const getNotesCreateNoteMutationOptions = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext> => {

const mutationKey = ['notesCreateNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesCreateNote>>, {data: NotesCreateNoteRequest}> = (props) => {
          const {data} = props ?? {};

          return  notesCreateNote(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesCreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesCreateNote>>>
    export type NotesCreateNoteMutationBody = NotesCreateNoteRequest
    export type NotesCreateNoteMutationError = NotesError

    /**
 * @summary Create a note for the caller's tenant.
 */
export const useNotesCreateNote = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesCreateNote>>, TError,{data: NotesCreateNoteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesCreateNote>>,
        TError,
        {data: NotesCreateNoteRequest},
        TContext
      > => {
      return useMutation(getNotesCreateNoteMutationOptions(options), queryClient);
    }

/**
 * @summary List every note belonging to the caller's tenant.
 */
export const notesListNotes = (

 signal?: AbortSignal
) => {


      return speedRequest<NotesListNotesResponse>(
      {url: `/api/v1/notes`, method: 'GET', signal
    },
      );
    }




export const getNotesListNotesQueryKey = () => {
    return [
    `/api/v1/notes`
    ] as const;
    }


export const getNotesListNotesQueryOptions = <TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotesListNotesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notesListNotes>>> = ({ signal }) => notesListNotes(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotesListNotesQueryResult = NonNullable<Awaited<ReturnType<typeof notesListNotes>>>
export type NotesListNotesQueryError = unknown


export function useNotesListNotes<TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notesListNotes>>,
          TError,
          Awaited<ReturnType<typeof notesListNotes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotesListNotes<TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notesListNotes>>,
          TError,
          Awaited<ReturnType<typeof notesListNotes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotesListNotes<TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List every note belonging to the caller's tenant.
 */

export function useNotesListNotes<TData = Awaited<ReturnType<typeof notesListNotes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesListNotes>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotesListNotesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * The tenant is always the one tenancy.Middleware already resolved from the request, and the note id names a note belonging to that tenant alone -- never a tenant_id request field: the tenant comes from the resolved request context, never from anything the caller sends. The delete is a mark-delete (dbkit.SoftDeletable): the row stays in place with deleted_at/deleted_by set, hidden from the list operation, and restorable through notes_restoreNote until a retention sweep physically reaps it. Deleting an already-deleted note answers 404 exactly like an unknown or another tenant's id -- the refusal is uniform, so a caller cannot learn which case it hit.
 * @summary Mark a note as deleted for the caller's tenant.
 */
export const notesDeleteNote = (
    noteId: string,
 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/notes/${noteId}`, method: 'DELETE', signal
    },
      );
    }



export const getNotesDeleteNoteMutationOptions = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesDeleteNote>>, TError,{noteId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notesDeleteNote>>, TError,{noteId: string}, TContext> => {

const mutationKey = ['notesDeleteNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesDeleteNote>>, {noteId: string}> = (props) => {
          const {noteId} = props ?? {};

          return  notesDeleteNote(noteId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesDeleteNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesDeleteNote>>>

    export type NotesDeleteNoteMutationError = NotesError

    /**
 * @summary Mark a note as deleted for the caller's tenant.
 */
export const useNotesDeleteNote = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesDeleteNote>>, TError,{noteId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesDeleteNote>>,
        TError,
        {noteId: string},
        TContext
      > => {
      return useMutation(getNotesDeleteNoteMutationOptions(options), queryClient);
    }

/**
 * The inverse of notes_deleteNote: clears the mark-delete's deleted_at/deleted_by so the note is visible to the list operation again, with its text and creator untouched. Restoring a note that is not currently deleted -- because it was never deleted, is unknown to this tenant, or belongs to another tenant -- answers 404 uniformly (notes.note_not_found), so a caller cannot learn which case it hit.
 * @summary Restore a previously deleted note for the caller's tenant.
 */
export const notesRestoreNote = (
    noteId: string,
 signal?: AbortSignal
) => {


      return speedRequest<void>(
      {url: `/api/v1/notes/${noteId}/restore`, method: 'POST', signal
    },
      );
    }



export const getNotesRestoreNoteMutationOptions = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesRestoreNote>>, TError,{noteId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notesRestoreNote>>, TError,{noteId: string}, TContext> => {

const mutationKey = ['notesRestoreNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesRestoreNote>>, {noteId: string}> = (props) => {
          const {noteId} = props ?? {};

          return  notesRestoreNote(noteId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesRestoreNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesRestoreNote>>>

    export type NotesRestoreNoteMutationError = NotesError

    /**
 * @summary Restore a previously deleted note for the caller's tenant.
 */
export const useNotesRestoreNote = <TError = NotesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesRestoreNote>>, TError,{noteId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesRestoreNote>>,
        TError,
        {noteId: string},
        TContext
      > => {
      return useMutation(getNotesRestoreNoteMutationOptions(options), queryClient);
    }

/**
 * The case groups one patient (the clinic-given name required, the optional clinic-given reference) with the photos of the case as already-uploaded go/storage object ids, in attachment order. Both the photo list and the reference may be absent or empty -- a case can be created for an intake whose photos arrive later. There is deliberately no tenant_id field and no creator field anywhere on the request: the tenant is the one tenancy.Middleware already resolved into the request context, and the creator comes from the host's SubjectResolver seam, never from the request (a request no resolver can attribute is refused with cases.subject_unresolved before the body is even read).
 * @summary Create a case under the caller's tenant.
 */
export const casesCreateCase = (
    casesCreateCaseRequest: CasesCreateCaseRequest,
 signal?: AbortSignal
) => {


      return speedRequest<CasesCase>(
      {url: `/api/v1/cases`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: casesCreateCaseRequest, signal
    },
      );
    }



export const getCasesCreateCaseMutationOptions = <TError = CasesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof casesCreateCase>>, TError,{data: CasesCreateCaseRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof casesCreateCase>>, TError,{data: CasesCreateCaseRequest}, TContext> => {

const mutationKey = ['casesCreateCase'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof casesCreateCase>>, {data: CasesCreateCaseRequest}> = (props) => {
          const {data} = props ?? {};

          return  casesCreateCase(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CasesCreateCaseMutationResult = NonNullable<Awaited<ReturnType<typeof casesCreateCase>>>
    export type CasesCreateCaseMutationBody = CasesCreateCaseRequest
    export type CasesCreateCaseMutationError = CasesError

    /**
 * @summary Create a case under the caller's tenant.
 */
export const useCasesCreateCase = <TError = CasesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof casesCreateCase>>, TError,{data: CasesCreateCaseRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof casesCreateCase>>,
        TError,
        {data: CasesCreateCaseRequest},
        TContext
      > => {
      return useMutation(getCasesCreateCaseMutationOptions(options), queryClient);
    }

/**
 * Lists every case of the caller's tenant, newest first -- the clinic-scoped list: everyone who treats a patient together in one practice sees the same cases, and only the tenant boundary hides a case (proven by the cross-tenant refusal tests, never by the creator column). Each entry carries its photos in attachment order (an empty list for a case whose photos arrive later). The list needs no creator attribution at all: any authenticated member of the tenant may read it, and the creator a create request is attributed with is recorded on the case row, never used to hide or filter the clinic's list.
 * @summary List every case of the caller's tenant.
 */
export const casesListCases = (

 signal?: AbortSignal
) => {


      return speedRequest<CasesListResponse>(
      {url: `/api/v1/cases`, method: 'GET', signal
    },
      );
    }




export const getCasesListCasesQueryKey = () => {
    return [
    `/api/v1/cases`
    ] as const;
    }


export const getCasesListCasesQueryOptions = <TData = Awaited<ReturnType<typeof casesListCases>>, TError = CasesError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesListCases>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCasesListCasesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof casesListCases>>> = ({ signal }) => casesListCases(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof casesListCases>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CasesListCasesQueryResult = NonNullable<Awaited<ReturnType<typeof casesListCases>>>
export type CasesListCasesQueryError = CasesError


export function useCasesListCases<TData = Awaited<ReturnType<typeof casesListCases>>, TError = CasesError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesListCases>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof casesListCases>>,
          TError,
          Awaited<ReturnType<typeof casesListCases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCasesListCases<TData = Awaited<ReturnType<typeof casesListCases>>, TError = CasesError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesListCases>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof casesListCases>>,
          TError,
          Awaited<ReturnType<typeof casesListCases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCasesListCases<TData = Awaited<ReturnType<typeof casesListCases>>, TError = CasesError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesListCases>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List every case of the caller's tenant.
 */

export function useCasesListCases<TData = Awaited<ReturnType<typeof casesListCases>>, TError = CasesError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesListCases>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCasesListCasesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Uploads one patient photo as a go/storage object of the caller's tenant and returns its object id -- the value a case create's photo_object_ids list then references. The operation is this surface's one-shot form of go/storage's three-step upload protocol: the handler runs create/upload/complete itself, computing the declared size and checksum from the decoded bytes (so no declared-vs-arrived mismatch is possible) and letting storage's own probe of the stored bytes decide the media type and refuse what is not an acceptable image. The bytes travel base64-encoded in JSON because this surface's frontend transport (the generated operations over @speed/api-client) is JSON-only; the upload page decodes nothing -- the browser file's bytes are base64-encoded once, client-side. An uploaded photo is NOT yet attached to any case: attachment happens when a case create names the object id, and the one-tenant-one-case-per-photo rule (cases.photo_already_attached) then applies like it does to any other object id. A photo never attached to a case is reclaimed by go/storage's own expiry sweep like any other object.
 * @summary Upload one patient photo to the caller's tenant.
 */
export const casesUploadPhoto = (
    casesUploadPhotoRequest: CasesUploadPhotoRequest,
 signal?: AbortSignal
) => {


      return speedRequest<CasesUploadPhotoResponse>(
      {url: `/api/v1/cases/photos/upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: casesUploadPhotoRequest, signal
    },
      );
    }



export const getCasesUploadPhotoMutationOptions = <TError = CasesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof casesUploadPhoto>>, TError,{data: CasesUploadPhotoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof casesUploadPhoto>>, TError,{data: CasesUploadPhotoRequest}, TContext> => {

const mutationKey = ['casesUploadPhoto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof casesUploadPhoto>>, {data: CasesUploadPhotoRequest}> = (props) => {
          const {data} = props ?? {};

          return  casesUploadPhoto(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CasesUploadPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof casesUploadPhoto>>>
    export type CasesUploadPhotoMutationBody = CasesUploadPhotoRequest
    export type CasesUploadPhotoMutationError = CasesError

    /**
 * @summary Upload one patient photo to the caller's tenant.
 */
export const useCasesUploadPhoto = <TError = CasesError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof casesUploadPhoto>>, TError,{data: CasesUploadPhotoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof casesUploadPhoto>>,
        TError,
        {data: CasesUploadPhotoRequest},
        TContext
      > => {
      return useMutation(getCasesUploadPhotoMutationOptions(options), queryClient);
    }

/**
 * Reads one photo of one case of the caller's tenant -- the bytes of the go/storage object a case photo references, base64-encoded in JSON with the media type storage's probe assigned at complete time, so the case view can render it (a blob URL built from the decoded bytes). The photo is addressed by its object id -- the value the case detail's photos entries carry -- never by a position the client would have to guess. An unknown case id, and a case of another tenant, both answer cases.not_found; a photo object id the case does not carry -- or whose object no longer exists in storage -- answers cases.photo_not_found; both refusals are deliberately indistinguishable from the same answer an unrelated request would get, so a caller can never probe another tenant's attachments.
 * @summary Read one photo of one case of the caller's tenant.
 */
export const casesGetPhotoContent = (
    caseId: string,
    photoObjectID: string,
 signal?: AbortSignal
) => {


      return speedRequest<CasesPhotoContent>(
      {url: `/api/v1/cases/${caseId}/photos/${photoObjectID}/content`, method: 'GET', signal
    },
      );
    }




export const getCasesGetPhotoContentQueryKey = (caseId: string,
    photoObjectID: string,) => {
    return [
    `/api/v1/cases/${caseId}/photos/${photoObjectID}/content`
    ] as const;
    }


export const getCasesGetPhotoContentQueryOptions = <TData = Awaited<ReturnType<typeof casesGetPhotoContent>>, TError = CasesError>(caseId: string,
    photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetPhotoContent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCasesGetPhotoContentQueryKey(caseId,photoObjectID);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof casesGetPhotoContent>>> = ({ signal }) => casesGetPhotoContent(caseId,photoObjectID, signal);





   return  { queryKey, queryFn, enabled: caseId !== null && caseId !== undefined && photoObjectID !== null && photoObjectID !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof casesGetPhotoContent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CasesGetPhotoContentQueryResult = NonNullable<Awaited<ReturnType<typeof casesGetPhotoContent>>>
export type CasesGetPhotoContentQueryError = CasesError


export function useCasesGetPhotoContent<TData = Awaited<ReturnType<typeof casesGetPhotoContent>>, TError = CasesError>(
 caseId: string,
    photoObjectID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetPhotoContent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof casesGetPhotoContent>>,
          TError,
          Awaited<ReturnType<typeof casesGetPhotoContent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCasesGetPhotoContent<TData = Awaited<ReturnType<typeof casesGetPhotoContent>>, TError = CasesError>(
 caseId: string,
    photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetPhotoContent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof casesGetPhotoContent>>,
          TError,
          Awaited<ReturnType<typeof casesGetPhotoContent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCasesGetPhotoContent<TData = Awaited<ReturnType<typeof casesGetPhotoContent>>, TError = CasesError>(
 caseId: string,
    photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetPhotoContent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read one photo of one case of the caller's tenant.
 */

export function useCasesGetPhotoContent<TData = Awaited<ReturnType<typeof casesGetPhotoContent>>, TError = CasesError>(
 caseId: string,
    photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetPhotoContent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCasesGetPhotoContentQueryOptions(caseId,photoObjectID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Reads one case of the caller's tenant with its photos in attachment order. An unknown case id, and a case of another tenant, both answer cases.not_found -- never a cross-tenant confirmation of a case's existence.
 * @summary Read one case of the caller's tenant.
 */
export const casesGetCase = (
    caseId: string,
 signal?: AbortSignal
) => {


      return speedRequest<CasesCase>(
      {url: `/api/v1/cases/${caseId}`, method: 'GET', signal
    },
      );
    }




export const getCasesGetCaseQueryKey = (caseId: string,) => {
    return [
    `/api/v1/cases/${caseId}`
    ] as const;
    }


export const getCasesGetCaseQueryOptions = <TData = Awaited<ReturnType<typeof casesGetCase>>, TError = CasesError>(caseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetCase>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCasesGetCaseQueryKey(caseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof casesGetCase>>> = ({ signal }) => casesGetCase(caseId, signal);





   return  { queryKey, queryFn, enabled: caseId !== null && caseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof casesGetCase>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CasesGetCaseQueryResult = NonNullable<Awaited<ReturnType<typeof casesGetCase>>>
export type CasesGetCaseQueryError = CasesError


export function useCasesGetCase<TData = Awaited<ReturnType<typeof casesGetCase>>, TError = CasesError>(
 caseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetCase>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof casesGetCase>>,
          TError,
          Awaited<ReturnType<typeof casesGetCase>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCasesGetCase<TData = Awaited<ReturnType<typeof casesGetCase>>, TError = CasesError>(
 caseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetCase>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof casesGetCase>>,
          TError,
          Awaited<ReturnType<typeof casesGetCase>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCasesGetCase<TData = Awaited<ReturnType<typeof casesGetCase>>, TError = CasesError>(
 caseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetCase>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read one case of the caller's tenant.
 */

export function useCasesGetCase<TData = Awaited<ReturnType<typeof casesGetCase>>, TError = CasesError>(
 caseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof casesGetCase>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCasesGetCaseQueryOptions(caseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * The photo must be an existing, completed go/storage object of the caller's own tenant; the job itself is async -- the 202 answer carries only its job id, and the job-status route below is how its outcome is observed. Options are optional: an absent options object (or an absent field inside it) inherits the service's documented default for that dimension, while an explicitly present out-of-vocabulary or out-of-range value is refused with its coded smilesim.* 400 before anything is reserved or enqueued. A recipient_user_id, when given, receives a completion notification once the job reaches a terminal status. There is deliberately no tenant_id field anywhere on this request: the tenant is the one tenancy.Middleware already resolved into the request context -- never a caller-supplied value.
 * @summary Enqueue one smile-simulation job for a completed photo.
 */
export const smilesimSimulate = (
    smilesimSimulateRequest: SmilesimSimulateRequest,
 signal?: AbortSignal
) => {


      return speedRequest<SmilesimJobRef>(
      {url: `/api/v1/smile-simulation/simulate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: smilesimSimulateRequest, signal
    },
      );
    }



export const getSmilesimSimulateMutationOptions = <TError = SmilesimError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof smilesimSimulate>>, TError,{data: SmilesimSimulateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof smilesimSimulate>>, TError,{data: SmilesimSimulateRequest}, TContext> => {

const mutationKey = ['smilesimSimulate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof smilesimSimulate>>, {data: SmilesimSimulateRequest}> = (props) => {
          const {data} = props ?? {};

          return  smilesimSimulate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SmilesimSimulateMutationResult = NonNullable<Awaited<ReturnType<typeof smilesimSimulate>>>
    export type SmilesimSimulateMutationBody = SmilesimSimulateRequest
    export type SmilesimSimulateMutationError = SmilesimError

    /**
 * @summary Enqueue one smile-simulation job for a completed photo.
 */
export const useSmilesimSimulate = <TError = SmilesimError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof smilesimSimulate>>, TError,{data: SmilesimSimulateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof smilesimSimulate>>,
        TError,
        {data: SmilesimSimulateRequest},
        TContext
      > => {
      return useMutation(getSmilesimSimulateMutationOptions(options), queryClient);
    }

/**
 * Answers the same jobs.Queue this app shares with go/ai-gateway: the status is the job's live status, an unknown or another tenant's job id answers 404 exactly like an unknown one. Once the job has succeeded, the answer carries the generated image's go/storage object id and the real vendor usage the job recorded; when a durable per-photo record exists for the job, it also echoes the effective options the simulation was generated with.
 * @summary Poll one smile-simulation job's live status.
 */
export const smilesimGetJob = (
    jobID: string,
 signal?: AbortSignal
) => {


      return speedRequest<SmilesimJobStatus>(
      {url: `/api/v1/smile-simulation/jobs/${jobID}`, method: 'GET', signal
    },
      );
    }




export const getSmilesimGetJobQueryKey = (jobID: string,) => {
    return [
    `/api/v1/smile-simulation/jobs/${jobID}`
    ] as const;
    }


export const getSmilesimGetJobQueryOptions = <TData = Awaited<ReturnType<typeof smilesimGetJob>>, TError = SmilesimError>(jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetJob>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSmilesimGetJobQueryKey(jobID);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof smilesimGetJob>>> = ({ signal }) => smilesimGetJob(jobID, signal);





   return  { queryKey, queryFn, enabled: jobID !== null && jobID !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof smilesimGetJob>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SmilesimGetJobQueryResult = NonNullable<Awaited<ReturnType<typeof smilesimGetJob>>>
export type SmilesimGetJobQueryError = SmilesimError


export function useSmilesimGetJob<TData = Awaited<ReturnType<typeof smilesimGetJob>>, TError = SmilesimError>(
 jobID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetJob>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof smilesimGetJob>>,
          TError,
          Awaited<ReturnType<typeof smilesimGetJob>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSmilesimGetJob<TData = Awaited<ReturnType<typeof smilesimGetJob>>, TError = SmilesimError>(
 jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetJob>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof smilesimGetJob>>,
          TError,
          Awaited<ReturnType<typeof smilesimGetJob>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSmilesimGetJob<TData = Awaited<ReturnType<typeof smilesimGetJob>>, TError = SmilesimError>(
 jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetJob>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Poll one smile-simulation job's live status.
 */

export function useSmilesimGetJob<TData = Awaited<ReturnType<typeof smilesimGetJob>>, TError = SmilesimError>(
 jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetJob>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSmilesimGetJobQueryOptions(jobID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Lists every simulation generated from the photo under the caller's tenant, newest first -- the P3 gallery's data source for one case photo. Each entry carries the effective options it was generated with, its live status and, once the job succeeded, its output object id. An unknown photo id is an empty list, not an error: this route reads the durable per-photo result index, which simply holds no rows for a photo nothing was generated from.
 * @summary List every simulation generated from one photo.
 */
export const smilesimListPhotoSimulations = (
    photoObjectID: string,
 signal?: AbortSignal
) => {


      return speedRequest<SmilesimPhotoSimulations>(
      {url: `/api/v1/smile-simulation/photos/${photoObjectID}/simulations`, method: 'GET', signal
    },
      );
    }




export const getSmilesimListPhotoSimulationsQueryKey = (photoObjectID: string,) => {
    return [
    `/api/v1/smile-simulation/photos/${photoObjectID}/simulations`
    ] as const;
    }


export const getSmilesimListPhotoSimulationsQueryOptions = <TData = Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError = SmilesimError>(photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSmilesimListPhotoSimulationsQueryKey(photoObjectID);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>> = ({ signal }) => smilesimListPhotoSimulations(photoObjectID, signal);





   return  { queryKey, queryFn, enabled: photoObjectID !== null && photoObjectID !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SmilesimListPhotoSimulationsQueryResult = NonNullable<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>>
export type SmilesimListPhotoSimulationsQueryError = SmilesimError


export function useSmilesimListPhotoSimulations<TData = Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError = SmilesimError>(
 photoObjectID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof smilesimListPhotoSimulations>>,
          TError,
          Awaited<ReturnType<typeof smilesimListPhotoSimulations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSmilesimListPhotoSimulations<TData = Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError = SmilesimError>(
 photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof smilesimListPhotoSimulations>>,
          TError,
          Awaited<ReturnType<typeof smilesimListPhotoSimulations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSmilesimListPhotoSimulations<TData = Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError = SmilesimError>(
 photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List every simulation generated from one photo.
 */

export function useSmilesimListPhotoSimulations<TData = Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError = SmilesimError>(
 photoObjectID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimListPhotoSimulations>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSmilesimListPhotoSimulationsQueryOptions(photoObjectID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Serves the stored bytes of the image one simulation job generated, base64-encoded in JSON with the media type go/storage's probe assigned -- the same JSON-only transport the cases surface's photo-content route uses, so the comparison view can render the result beside the original photo. The simulation is addressed the way the per-photo enumeration lists it: by its generation job's id under the photo it was generated from. The job-status route stays the poll for the outcome; this route is the read of the bytes once the job has succeeded. A job the photo has no record of under the caller's tenant answers 404 (smilesim.simulation_not_found), a job that has not succeeded answers 404 (smilesim.output_not_ready), and a succeeded simulation whose stored bytes no longer exist answers 404 (smilesim.output_not_found) -- each refusal the same outward shape, never probing whether another tenant's object still exists.
 * @summary Read one simulation's generated image content.
 */
export const smilesimGetSimulationContent = (
    photoObjectID: string,
    jobID: string,
 signal?: AbortSignal
) => {


      return speedRequest<SmilesimSimulationContent>(
      {url: `/api/v1/smile-simulation/photos/${photoObjectID}/simulations/${jobID}/content`, method: 'GET', signal
    },
      );
    }




export const getSmilesimGetSimulationContentQueryKey = (photoObjectID: string,
    jobID: string,) => {
    return [
    `/api/v1/smile-simulation/photos/${photoObjectID}/simulations/${jobID}/content`
    ] as const;
    }


export const getSmilesimGetSimulationContentQueryOptions = <TData = Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError = SmilesimError>(photoObjectID: string,
    jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSmilesimGetSimulationContentQueryKey(photoObjectID,jobID);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof smilesimGetSimulationContent>>> = ({ signal }) => smilesimGetSimulationContent(photoObjectID,jobID, signal);





   return  { queryKey, queryFn, enabled: photoObjectID !== null && photoObjectID !== undefined && jobID !== null && jobID !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SmilesimGetSimulationContentQueryResult = NonNullable<Awaited<ReturnType<typeof smilesimGetSimulationContent>>>
export type SmilesimGetSimulationContentQueryError = SmilesimError


export function useSmilesimGetSimulationContent<TData = Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError = SmilesimError>(
 photoObjectID: string,
    jobID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof smilesimGetSimulationContent>>,
          TError,
          Awaited<ReturnType<typeof smilesimGetSimulationContent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSmilesimGetSimulationContent<TData = Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError = SmilesimError>(
 photoObjectID: string,
    jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof smilesimGetSimulationContent>>,
          TError,
          Awaited<ReturnType<typeof smilesimGetSimulationContent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSmilesimGetSimulationContent<TData = Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError = SmilesimError>(
 photoObjectID: string,
    jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read one simulation's generated image content.
 */

export function useSmilesimGetSimulationContent<TData = Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError = SmilesimError>(
 photoObjectID: string,
    jobID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof smilesimGetSimulationContent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSmilesimGetSimulationContentQueryOptions(photoObjectID,jobID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
