/**
 * SimulationDownloadAction contract -- the keep-the-result acceptance
 * shape at the component level, driven the same way the block-B panel
 * suite drives its own: the case detail page mounted over the real
 * api-client rig answering from the demo responder's genuine Response
 * objects. A completed simulation's comparison carries a download
 * link; the link's href is a blob URL over exactly the bytes the
 * content read served, its download attribute carries a filename named
 * for the patient, and the materialized URL is revoked when the page
 * leaves. The action shares the comparison image's own content read --
 * one network request serves both -- and a refused read offers no
 * download at all: the refusal's text speaks where the image belongs,
 * never a control that would save an error page.
 */

import { waitFor, within } from '@testing-library/react'
import type { CasesCase } from '@speed/api-sdk'
import { describe, expect, it, vi } from 'vitest'
import { demoServer } from '../test-utils/demo-server.js'
import { makeRealClientRig, signInWithPassword } from '../test-utils/real-client.js'
import { renderWithAppServices } from '../test-utils/render.js'
import { CaseDetailView } from './case-detail-view.js'
import {
  simulationDownloadFileName,
} from './simulation-download-action.js'

const DEMO_CREATED_AT = '2026-09-04T00:00:00Z'

/** A case with one attached photo, as the demo server serves it. */
function caseWithPhoto(): CasesCase {
  return {
    id: 'case-1',
    patient_name: 'Anna Meyer',
    patient_ref: 'CH-1001',
    creator_user_id: 'user-1',
    created_at: DEMO_CREATED_AT,
    photos: [{ object_id: 'photo-1' }],
  }
}

/** The blob-URL stand-ins (jsdom implements neither createObjectURL
 * nor revokeObjectURL), recording every blob the page materialized and
 * every URL it revoked -- the panel suite's counting double, copied
 * here the way each layer's rig keeps its own copy. */
function installBlobURLDouble(): {
  readonly blobs: Blob[]
  readonly revoked: string[]
  restore: () => void
} {
  const originalCreate = URL.createObjectURL
  const originalRevoke = URL.revokeObjectURL
  const blobs: Blob[] = []
  const revoked: string[] = []
  URL.createObjectURL = vi.fn<(blob: Blob) => string>((blob) => {
    blobs.push(blob)
    return `blob:download-${blobs.length}`
  }) as typeof URL.createObjectURL
  URL.revokeObjectURL = vi.fn<(url: string) => void>((url) => {
    revoked.push(url)
  }) as typeof URL.revokeObjectURL
  return {
    blobs,
    revoked,
    restore: () => {
      URL.createObjectURL = originalCreate
      URL.revokeObjectURL = originalRevoke
    },
  }
}

/** Mounts the case detail page -- the surface the download action
 * lives on -- over the real-client rig and signs the owner in. */
async function renderCaseDetailForDownload(
  options: Parameters<typeof demoServer>[0] = {},
): Promise<
  ReturnType<typeof renderWithAppServices> & {
    readonly calls: ReturnType<typeof makeRealClientRig>['calls']
  }
> {
  const rig = makeRealClientRig(demoServer(options))
  await signInWithPassword(rig)
  const view = renderWithAppServices(
    <CaseDetailView caseId="case-1" onBack={vi.fn()} />,
    { session: rig.session, api: rig.api },
    { language: 'en-US' },
  )
  return { ...view, calls: rig.calls }
}

/** The simulation-content reads the rig observed: the GETs of a
 * succeeded job's generated bytes. */
function contentReads(
  view: Awaited<ReturnType<typeof renderCaseDetailForDownload>>,
): number {
  return view.calls.filter(
    (call) =>
      call.method === 'GET' &&
      call.path.includes('/smile-simulation/') &&
      call.path.endsWith('/content'),
  ).length
}

describe('SimulationDownloadAction', () => {
  it('offers the completed simulation as a real, named download link over the served bytes (the keep-the-result shape)', async () => {
    const blobDouble = installBlobURLDouble()
    try {
      const view = await renderCaseDetailForDownload({
        initialCases: [caseWithPhoto()],
      })

      // No download control exists before a simulation completes.
      expect(
        view.queryByRole('link', { name: 'Download image' }),
      ).not.toBeInTheDocument()

      // The photo's automatic first generation completes into the
      // comparison (the auto-preview's one-shot run, the shape every
      // case journey rides on).
      const comparison = await view.findByRole(
        'region',
        { name: 'Before and after' },
        { timeout: 8000 },
      )
      await waitFor(
        () => expect(within(comparison).getAllByRole('img')).toHaveLength(2),
        { timeout: 8000 },
      )

      // The download control: a real link whose download attribute
      // carries the filename -- the patient's own name, what the file
      // is, and the extension the served media type's bytes carry --
      // and whose href is a blob URL the page materialized from the
      // served bytes.
      const download = await within(comparison).findByRole('link', {
        name: 'Download image',
      })
      expect(download.getAttribute('href')).toMatch(/^blob:/)
      expect(download).toHaveAttribute(
        'download',
        'Anna Meyer smile simulation.png',
      )

      // The page materialized four URLs for one completed result: the
      // original photo twice (the photo column and the comparison), the
      // comparison's result image once, and this download link last --
      // each from a blob of the media type and bytes its read served.
      expect(blobDouble.blobs).toHaveLength(4)
      expect(await blobDouble.blobs[3]?.text()).toBe(
        'simulation-result-bytes',
      )
      expect(blobDouble.blobs[3]?.type).toBe('image/png')
      expect(download.getAttribute('href')).toBe('blob:download-4')

      // The action shares the comparison image's own content read: one
      // network request served both halves of the surface, so saving
      // the image costs the practice nothing the comparison did not
      // already pay.
      expect(contentReads(view)).toBe(1)

      // The URLs this page created are revoked when it unmounts: a
      // session that opens and closes cases never leaks blob URLs.
      view.unmount()
      await waitFor(() =>
        expect(blobDouble.revoked).toHaveLength(blobDouble.blobs.length),
      )
    } finally {
      blobDouble.restore()
    }
  })

  it('offers no download while the result content is refused -- the refusal text speaks instead', async () => {
    const view = await renderCaseDetailForDownload({
      initialCases: [caseWithPhoto()],
      simulationContentRefusal: {
        status: 404,
        code: 'smilesim.output_not_found',
      },
    })

    // The photo's automatic generation completes into the comparison,
    // whose result-image read is refused by the route's answer.
    await view.findByRole('button', { name: 'Simulate smile' })
    const comparison = await view.findByRole(
      'region',
      { name: 'Before and after' },
      { timeout: 8000 },
    )

    // The original still renders; the missing result answers with its
    // refusal's bilingual text -- and no download control exists, so
    // nothing offers to save bytes that do not exist.
    await waitFor(() =>
      expect(
        within(comparison).getByText(
          'The result image is no longer available.',
        ),
      ).toBeInTheDocument(),
    )
    expect(
      within(comparison).queryByRole('link', { name: 'Download image' }),
    ).not.toBeInTheDocument()
    expect(
      within(comparison).getByRole('img', { name: 'Patient photo 1' }),
    ).toBeInTheDocument()
  })
})

describe('simulationDownloadFileName', () => {
  it('names the file for the patient, what it is, and the served media type', () => {
    expect(simulationDownloadFileName('Anna Meyer', 'image/png')).toBe(
      'Anna Meyer smile simulation.png',
    )
    expect(simulationDownloadFileName('Anna Meyer', 'image/jpeg')).toBe(
      'Anna Meyer smile simulation.jpg',
    )
    expect(simulationDownloadFileName('Anna Meyer', 'image/webp')).toBe(
      'Anna Meyer smile simulation.webp',
    )
  })

  it('keeps a name a filesystem accepts when the patient name carries hostile characters', () => {
    expect(simulationDownloadFileName('Anna/Meyer: The "Great"?', 'image/png')).toBe(
      'Anna Meyer The Great smile simulation.png',
    )
  })

  it('falls back to what the file is when no patient name is available', () => {
    expect(simulationDownloadFileName('', 'image/png')).toBe(
      'smile simulation.png',
    )
    expect(simulationDownloadFileName('   ', 'image/png')).toBe(
      'smile simulation.png',
    )
  })

  it('carries no extension for a media type outside the map, still downloadable', () => {
    expect(
      simulationDownloadFileName('Anna Meyer', 'application/octet-stream'),
    ).toBe('Anna Meyer smile simulation')
  })
})
