/**
 * Generation configuration for the frontend-contract half of the API
 * pipeline (docs/internal/21-api-contract.md): the @speed/api-sdk
 * package's src/ is orval output from each module's openapi fragment.
 *
 * orval version pinned: 8.17.0. Every runner invokes the same command
 * from this directory -- the Taskfile `api:gen` frontend leg and the
 * api-contract.yml regen step both run
 * `pnpm dlx orval@8.17.0 --config orval.config.ts` -- so the two cannot
 * drift. orval itself is never a workspace dependency: pnpm dlx fetches
 * it on demand and it stays out of pnpm-lock.yaml. A version bump must
 * land in the Taskfile, this comment and api-contract.yml together, and
 * shows up as a diff in the regenerated header (which stamps the
 * version).
 *
 * Input is the committed merged document, build/openapi/speed.yaml,
 * produced by redocly's `join` of the module fragments (Taskfile's
 * api:merge task -- `task api:gen` depends on it, so a fragment edit can
 * never regenerate from a stale committed merge). The merge currently
 * covers the notes and authn fragments; org's fragment is deliberately
 * not part of it (docs/internal/21-api-contract.md's org note -- it
 * predates the merge machinery). Output covers types AND TanStack Query
 * hooks (client: react-query), written to src/index.ts; generated
 * files carry the DO-NOT-EDIT header below.
 *
 * HTTP transport: httpClient 'axios' selects the axios-shaped mutator
 * call -- one options object `{url, method, headers, params, data,
 * signal}` -- routed to the exported `speedRequest` adapter in
 * packages/api-sdk/src/runtime.ts. That seam (the package's only
 * hand-written file) forwards every call to the request function the
 * host binds from @speed/api-client, so no generated file and no bridge
 * file performs HTTP itself. One operation overrides the mutator:
 * `authn_refreshToken`, the session-refresh operation, routes through
 * `speedRequestCredentialless` instead, which declares the request
 * credential-less (`omitAccessToken` on @speed/api-client's
 * RequestOptions). A session's refresh authenticates with the refresh
 * token in its body and must never present an access token; declaring
 * that per request beats clearing the host's token store for the
 * refresh's duration, which would leave concurrent requests
 * momentarily token-less and turn their bearer-valid 401s into
 * spurious auth failures under the client's bearer-only refresh rule
 * (see the refreshAccessToken doc in @speed/api-client's client.ts).
 * Three orval behaviours are worked around here and documented in the
 * package AGENTS.md: orval emits each mutator import without a file
 * extension (breaking nodenext builds), which
 * web/scripts/orval-nodenext-fixup.mjs rewrites deterministically after
 * every run; the same script's rewrite now covers every mutator name
 * the per-operation override can emit; and query keys carry no tenant
 * prefix by design -- tenant query-key namespacing is an M1
 * consumer-shell discipline.
 *
 * Config paths are relative to this file's directory (web/).
 */

export default {
  speed: {
    input: {
      target: '../build/openapi/speed.yaml',
    },
    output: {
      target: './packages/api-sdk/src/index.ts',
      client: 'react-query',
      httpClient: 'axios',
      mode: 'single',
      override: {
        // Trailing newline is load-bearing: orval concatenates the
        // header with the file body, so the last line must end in \n.
        header: (info: { title: string }): string =>
          `// Code generated by orval 8.17.0. DO NOT EDIT.\n` +
          `// Source: ${info.title}\n` +
          `// The mutator import in this file is rewritten to an explicit\n` +
          `// .js extension by web/scripts/orval-nodenext-fixup.mjs (nodenext\n` +
          `// builds); rerun it after every regeneration.\n`,
        mutator: {
          path: './packages/api-sdk/src/runtime.ts',
          name: 'speedRequest',
        },
        operations: {
          // The one credential-less operation in the surface: a
          // session's refresh authenticates with the refresh token in
          // its body and must never present an access token -- declared
          // per request (`speedRequestCredentialless` sets
          // omitAccessToken) so the host's token store is never cleared
          // for it (rationale above and in runtime.ts).
          authn_refreshToken: {
            mutator: {
              path: './packages/api-sdk/src/runtime.ts',
              name: 'speedRequestCredentialless',
            },
          },
        },
      },
    },
  },
}
