/**
 * Generation configuration for the frontend-contract half of the API
 * pipeline (docs/internal/21-api-contract.md): the @speed/api-sdk
 * package's src/ is orval output from each module's openapi fragment.
 *
 * orval version pinned: 8.17.0. Every runner invokes the same command
 * from this directory -- the Taskfile `api:gen` frontend leg and the
 * api-contract.yml regen step both run
 * `pnpm dlx orval@8.17.0 --config orval.config.ts` -- so the two cannot
 * drift. orval itself is never a workspace dependency: pnpm dlx fetches
 * it on demand and it stays out of pnpm-lock.yaml. A version bump must
 * land in the Taskfile, this comment and api-contract.yml together, and
 * shows up as a diff in the regenerated header (which stamps the
 * version).
 *
 * Input is the notes module's openapi fragment only: redocly's
 * merge of the module fragments into speed.yaml is deferred to M1, when
 * the second fragment appears. Output covers types AND TanStack Query
 * hooks (client: react-query), written to src/index.ts; generated
 * files carry the DO-NOT-EDIT header below.
 *
 * HTTP transport: httpClient 'axios' selects the axios-shaped mutator
 * call -- one options object `{url, method, headers, params, data,
 * signal}` -- routed to the exported `speedRequest` adapter in
 * packages/api-sdk/src/runtime.ts. That seam (the package's only
 * hand-written file) forwards every call to the request function the
 * host binds from @speed/api-client, so no generated file and no bridge
 * file performs HTTP itself. Two orval behaviours are worked around
 * here and documented in the package AGENTS.md: orval emits the mutator
 * import without a file extension (breaking nodenext builds), which
 * web/scripts/orval-nodenext-fixup.mjs rewrites deterministically after
 * every run; and query keys carry no tenant prefix by design -- tenant
 * query-key namespacing is an M1 consumer-shell discipline.
 *
 * Config paths are relative to this file's directory (web/).
 */

export default {
  notes: {
    input: {
      target: '../examples/reference-app/internal/notes/api/openapi.yaml',
    },
    output: {
      target: './packages/api-sdk/src/index.ts',
      client: 'react-query',
      httpClient: 'axios',
      mode: 'single',
      override: {
        // Trailing newline is load-bearing: orval concatenates the
        // header with the file body, so the last line must end in \n.
        header: (info: { title: string }): string =>
          `// Code generated by orval 8.17.0. DO NOT EDIT.\n` +
          `// Source: ${info.title}\n` +
          `// The mutator import in this file is rewritten to an explicit\n` +
          `// .js extension by web/scripts/orval-nodenext-fixup.mjs (nodenext\n` +
          `// builds); rerun it after every regeneration.\n`,
        mutator: {
          path: './packages/api-sdk/src/runtime.ts',
          name: 'speedRequest',
        },
      },
    },
  },
}
